-- Placeholder building sprites for the machines that have no art of their own.
--
-- THIS IS THE REPOSITORY'S OWN WORK and carries the repository's own licence. It is deliberately
-- NOT in graphics/krastorio-2/ -- nothing here derives from Krastorio 2 or from either predecessor,
-- which is the whole reason mockups were reached for. #45 ran out of clean sources: Krastorio 2 has
-- no building at these shapes, and the predecessor's exact 5x15 heat exchanger sheet is unmarked
-- art whose provenance ADR 0001 will not let us assume. A rectangle we drew has no such problem.
--
-- The PNGs are generated by scripts/make-mockup-art.ps1. Change a size there and re-run it rather
-- than editing a file by hand; the sizes are still being settled.
--
-- WHAT A MOCKUP IS FOR. It states the footprint, marks every pipe connection where the prototype
-- actually declares one, and names the machine. That is strictly more than the vanilla sprite it
-- replaces was telling anyone: a vanilla heat exchanger on a 5x15 building looks finished and lies
-- about both its size and where its pipes are. These are meant to be replaced -- #108 for the heat
-- exchanger, and whatever follows it for the rest.
--
-- THE ENGINE ROTATES NOTHING. A boiler wants a picture per direction and a generator one per axis,
-- so each oblong machine has a sideways sheet as well, named "-h". A square machine is its own
-- rotation and every direction shares one sheet.

local DIRECTORY = "__realistic-fusion-refreshed__/graphics/mockup/"

-- 64 pixels to the tile at scale 0.5, which is what make-mockup-art.ps1 draws and what vanilla and
-- Krastorio 2 both use. Stated once here so the two cannot drift apart silently.
local PIXELS_PER_TILE = 64
local SCALE = 0.5

--- A sprite for one sheet, sized from the footprint it was drawn for.
--
-- @param file   basename inside graphics/mockup/, without .png
-- @param tiles_w  width in tiles
-- @param tiles_h  height in tiles
local function sheet(file, tiles_w, tiles_h)
  return {
    layers = {
      {
        filename = DIRECTORY .. file .. ".png",
        priority = "extra-high",
        width = tiles_w * PIXELS_PER_TILE,
        height = tiles_h * PIXELS_PER_TILE,
        scale = SCALE,
      },
      {
        filename = DIRECTORY .. file .. "-shadow.png",
        priority = "extra-high",
        width = tiles_w * PIXELS_PER_TILE,
        height = tiles_h * PIXELS_PER_TILE,
        scale = SCALE,
        draw_as_shadow = true,
      },
    },
  }
end

local M = {}

--- A BoilerPictureSet built from one upright sheet and one sideways one.
--
-- North and south share the upright sheet, east and west the sideways one. A real building would
-- differ between the two of each pair -- a machine seen from the front is not the same as from
-- behind -- but a labelled rectangle is symmetric and pretending otherwise would be drawing detail
-- that is not there.
--
-- Only `structure` is given. Vanilla's boiler pictures also carry `fire` and `fire_glow` layers,
-- and dropping them is deliberate: those are drawn for the firebox of vanilla's own sprite and
-- would sit in the wrong place on anything else.
function M.boiler(file, tiles_w, tiles_h)
  local upright  = sheet(file, tiles_w, tiles_h)
  local sideways = (tiles_w == tiles_h) and upright or sheet(file .. "-h", tiles_h, tiles_w)
  return {
    north = { structure = upright },
    south = { structure = upright },
    east  = { structure = sideways },
    west  = { structure = sideways },
  }
end

--- The two animations a generator wants, as single frames.
function M.generator(file, tiles_w, tiles_h)
  return {
    vertical   = sheet(file, tiles_w, tiles_h),
    horizontal = (tiles_w == tiles_h) and sheet(file, tiles_w, tiles_h)
                 or sheet(file .. "-h", tiles_h, tiles_w),
  }
end

--- One sprite, for something that does not rotate.
function M.still(file, tiles_w, tiles_h)
  return sheet(file, tiles_w, tiles_h)
end

--- A reactor's lit core, as the animation prototype scripts/reactor-animation.lua draws.
--
-- IT HAS TO EXIST. That file records the failure if it does not: a reactor whose "<name>-core"
-- animation is missing crashes rendering.draw_animation the first time it starts fusing, on a live
-- save. So a reactor on mockup art needs a mockup core rather than simply going without.
--
-- A single frame declared as an animation, which is enough to say the machine is running without
-- inventing motion that is not drawn. No shadow: it is a glow over the building, not a solid.
--
-- @param name     the prototype name, which must be the reactor's plus "-core"
-- @param file     basename inside graphics/mockup/
-- @param tiles    the reactor's footprint, which the sheet is drawn square to
function M.core_animation(name, file, tiles)
  return {
    type = "animation",
    name = name,
    filename = DIRECTORY .. file .. ".png",
    priority = "extra-high",
    width = tiles * PIXELS_PER_TILE,
    height = tiles * PIXELS_PER_TILE,
    scale = SCALE,
    draw_as_glow = true,
    blend_mode = "additive",
  }
end

return M
