require("prototypes.categories")
require("prototypes.fluids")
require("prototypes.items")
require("prototypes.entities")
require("prototypes.recipes.deuterium")
require("prototypes.technology.deuterium")
