-- Reaction rate computation.
--
-- Pure Lua. It touches no Factorio API -- no data, no game, no storage, no settings, and none of
-- table_size, serpent, log or localised_print -- which is what makes it testable outside the game
-- (tests/test-reactivity.lua) and what ADR 0005 requires: the rate computation is isolated from
-- the tick cadence, so throttling to on_nth_tick is a change in control.lua alone.
--
-- Written to Lua 5.2.1, which is what Factorio 2.0.77 runs, and verified on standalone 5.4.6:
-- no "//", no math.type, no reliance on integer subtypes.
--
-- Reactivities are generated by tools/derive-reactivities.py from ENDF/B-VIII.0 cross-sections;
-- see that script for why the predecessor's tables were not reused.

local datasets = require("cross-section-data.reactivities")

local M = {}

-- v1's reactions, in progression order (ADR 0010). The two D-D branches are also present in the
-- dataset under "D-D_T" and "D-D_He3" and can be asked for by name; they are not listed here
-- because they are not separately selectable reactions, they are how D-D breeds its by-products.
M.reactions = { "D-D", "D-T", "D-He3", "He3-He3" }

-- Reactions between identical nuclei. Each pair of particles is one reaction, so counting
-- n * n would count every pair twice; the rate carries a factor of one half. Getting this wrong
-- silently doubles D-D and He3-He3 output.
local LIKE_SPECIES = {
  ["D-D"] = true, ["D-D_T"] = true, ["D-D_He3"] = true, ["He3-He3"] = true,
}

--- Linear interpolation over a table of {x, y} pairs, ascending in x.
--
-- Out of range clamps rather than extrapolating: below threshold an extrapolated reactivity goes
-- negative, and above the table it grows without bound. Both are worse than a flat answer.
function M.interpolate(dataset, x)
  local n = #dataset
  if n == 0 then return 0 end
  if n == 1 then return dataset[1][2] end
  if x <= dataset[1][1] then return dataset[1][2] end
  if x >= dataset[n][1] then return dataset[n][2] end

  local lo, hi = 1, n
  while hi - lo > 1 do
    -- math.floor rather than "//": integer division does not exist in Lua 5.2 and would be a
    -- syntax error the moment Factorio loaded this file.
    local mid = math.floor((lo + hi) / 2)
    if dataset[mid][1] <= x then lo = mid else hi = mid end
  end

  local x0, y0 = dataset[lo][1], dataset[lo][2]
  local x1, y1 = dataset[hi][1], dataset[hi][2]
  local dx = x1 - x0
  -- Unreachable as written: the loop above ends with dataset[lo][1] <= x < dataset[hi][1], so
  -- x0 < x1 strictly and dx is never zero -- duplicated x values included, which the
  -- predecessor's dataset did contain. Kept because the cost is one comparison and the failure
  -- it guards against is silent: dividing by a zero-width span yields NaN, and NaN then
  -- propagates through every downstream number without erroring anywhere. A future rewrite of
  -- this search that loses the invariant would reintroduce exactly that.
  if dx == 0 then return y0 end
  return y0 + (y1 - y0) * (x - x0) / dx
end

--- Maxwellian-averaged reactivity <sigma.v>, in m^3/s, at a plasma temperature in kelvin.
function M.reactivity(reaction, temperature_k)
  local dataset = datasets[reaction]
  if not dataset then
    error("unknown reaction: " .. tostring(reaction))
  end
  if not temperature_k or temperature_k <= 0 then return 0 end
  return M.interpolate(dataset, temperature_k)
end

--- Reactions per cubic metre per second, from the two reactant number densities in m^-3.
function M.rate(reaction, temperature_k, density_a, density_b)
  local sv = M.reactivity(reaction, temperature_k)
  if sv <= 0 then return 0 end
  local rate = density_a * density_b * sv
  if LIKE_SPECIES[reaction] then rate = rate * 0.5 end
  return rate
end

--- Fusion power out over heating power in.
--
-- Zero heating power returns zero rather than infinity. A reactor that is off is not infinitely
-- efficient, and an infinity here would travel straight into a circuit signal and into whatever
-- the player wired to it.
function M.q_factor(fusion_power, heating_power)
  if not heating_power or heating_power <= 0 then return 0 end
  if not fusion_power or fusion_power <= 0 then return 0 end
  return fusion_power / heating_power
end

return M
