#Requires -Version 7
<#
.SYNOPSIS
    Checks that the D-T tier works end to end: the mix becomes plasma, the same reactor burns it,
    and it pays far more than D-D for it. Discharges #28.

.DESCRIPTION
    tests/test-reactor-logic.lua asserts the physics outside Factorio. This asserts that the physics
    reaches a reactor -- which for this tier is a different claim from the last one, because #28
    changed a prototype rather than only adding one.

    THE THING MOST LIKELY TO BE WRONG

    rf-reactor's input fluid box used to be filtered to rf-d-d-plasma. ADR 0010 names one reactor for
    both tiers, and a filter takes exactly one fluid, so #28 removed it. That is a change to the
    entity every existing reactor is, and its failure mode is quiet: a filter left in place does not
    error, it just means a D-T pipe will not connect and the reactor reports itself starved on a
    perfectly good rig. The `dt` cell below is what would catch it.

    WHAT IS BUILT

      dt        A reactor fed rf-d-t-plasma at a temperature D-D can also reach. It must fuse, and
                it must run up to the top of the plasma's range -- D-T ignites at this reactor's
                density and confinement time, which is the tier's defining behaviour rather than a
                balance number. See docs/research/d-t-ignition.md.
      dd        The same reactor, the same feed temperature, on D-D. The pair is the acceptance
                criterion: a materially different rate and output at the same temperature.
      heater    An rf-heater running rf-d-t-plasma on Core's rf-d-t-mix, which is the chain step
                between the two tiers and the one that crosses the module seam.
      collector An rf-isotope-collector bolted to the D-T reactor. It must stay EMPTY: D-T leaves an
                alpha and a neutron, neither of which is a fluid this mod defines, so the tier
                breeds nothing and needs no collector. A row copied from D-D without editing its
                products would fill this.

    The technology gate is checked without building anything, off the force's own technology and
    recipe tables: rf-tritium-breeding must come before rf-d-t-fusion, and the plasma recipe must be
    locked until the second one is researched.

.PARAMETER FactorioExe
    Path to Factorio.exe. Defaults to $env:FACTORIO_EXE, then the Steam install on this machine.

.PARAMETER Ticks
    Ticks to run before checking. The default is far longer than D-T needs -- it ignites within a
    minute of game time -- and is kept in step with check-breeding.ps1 so the two are comparable.

.PARAMETER KeepTemp
    Keep the save, the rig mod and the captured output.

.EXAMPLE
    pwsh -File scripts/check-d-t.ps1
#>
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [ValidateRange(600, 200000)] [int] $Ticks = 7200,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/factorio-lib.ps1"

$repoRoot = Split-Path $PSScriptRoot -Parent
$ourMods  = @('RealisticFusionCore', 'RealisticFusion')
$rigName  = 'rf-d-t-rig'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-dt-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

function Write-Rig {
    @{
        name = $rigName; version = '0.0.1'; title = 'D-T tier check'
        author = 'check-d-t.ps1'; factorio_version = '2.0'
        dependencies = @('base >= 2.0.77', 'RealisticFusion', 'RealisticFusionCore')
    } | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

    $feed = Write-PlasmaFeed -RigDirectory $rigDir

    $lua = @'
-- Generated by scripts/check-d-t.ps1. Nothing here ships.

local CHECK_AT = __TICKS__

local DD   = "rf-d-d-plasma"
local DT   = "rf-d-t-plasma"
local MIX  = "rf-d-t-mix"
local FEED = "__PLASMAFEED__"

-- The temperature both cells are fed at. Chosen because D-D actually fuses there -- it is roughly
-- where the shipped reactor settles -- so the comparison is against D-D at its best rather than
-- against a D-D reactor that happens to be cold.
local BOTH_AT = 6e8

-- Results live in storage rather than in an upvalue, because on_init and the check tick are not the
-- same run of this file: on_init happens under --create and the benchmark then LOADS that save, so
-- anything the gate checks recorded in a local would be quietly gone by the time the report is
-- printed. It was, and the report simply came out six lines shorter with nothing to say it had.
local function record(ok, name, detail)
  storage.report = storage.report or { lines = {}, failures = 0 }
  if not ok then storage.report.failures = storage.report.failures + 1 end
  storage.report.lines[#storage.report.lines + 1] = string.format("%s  %s%s",
    ok and "ok  " or "FAIL", name, detail and ("  -- " .. detail) or "")
end

local function must(entity, what)
  if not entity then error(what .. " refused") end
  return entity
end

local function holds(entity, fluid)
  local total = 0
  for index = 1, #entity.fluidbox do
    local contents = entity.fluidbox[index]
    if contents and contents.name == fluid then total = total + contents.amount end
  end
  return total
end

local function box_of(entity, fluid)
  for index = 1, #entity.fluidbox do
    local filter = entity.fluidbox.get_filter(index)
    if filter and filter.name == fluid then return index end
  end
  return nil
end

local function power(surface, force, at)
  must(surface.create_entity({ name = "substation", position = at, force = force }), "substation")
  local eei = must(surface.create_entity({
    name = "electric-energy-interface", position = { at[1] + 2.5, at[2] + 0.5 }, force = force,
  }), "power source")
  eei.power_production = 8e6
end

--- A reactor on a plasma feed, at `ox`. Geometry is read off the prototypes rather than written
--- down: #49 is what happens when a rig remembers a machine's size and the machine changes.
---
--- The feed carries the plasma set's connection category (#26) and the reactor's input box carries
--- no filter (#28), so which plasma a reactor burns is decided entirely by what is plumbed to it.
--- That is the arrangement under test.
local function reactor_at(surface, force, ox, plasma)
  local reactor = must(surface.create_entity({
    name = "rf-reactor", position = { ox, 0.5 }, force = force, raise_built = true,
  }), "rf-reactor")
  local west = reactor.fluidbox.get_pipe_connections(1)[1].target_position
  local feed = must(surface.create_entity({
    name = FEED, position = { west.x, west.y }, force = force,
  }), "plasma feed")
  feed.set_infinity_pipe_filter({
    name = plasma, percentage = 1, temperature = BOTH_AT, mode = "at-least",
  })
  return reactor
end

script.on_init(function()
  local surface = game.surfaces[1]
  local force   = game.forces.player

  -- ------------------------------------------------------------------ the technology gate
  --
  -- Read before research_all_technologies, which is the only moment the locked state exists. The
  -- order is a property of the prerequisite graph rather than of what a player did, so it is asked
  -- of the technologies themselves.
  local breeding = force.technologies["rf-tritium-breeding"]
  local fusion   = force.technologies["rf-d-t-fusion"]
  record(breeding ~= nil and fusion ~= nil, "both gating technologies exist")
  -- Guarded rather than read straight through. Everything below indexes these two, so a renamed or
  -- missing technology -- which is exactly what the check above exists to catch -- would throw out
  -- of on_init instead, the save would never be created, and the harness would report only that the
  -- rig never reached its check tick. A check that turns its own finding into a mystery is worse
  -- than no check.
  if breeding and fusion then
    record(fusion.prerequisites["rf-tritium-breeding"] ~= nil,
      "rf-d-t-fusion requires rf-tritium-breeding, so they unlock in that order")
    record(breeding.prerequisites["rf-d-d-fusion"] ~= nil,
      "and rf-tritium-breeding requires the tier that does the breeding")
    -- Core's, and the direction ADR 0010 allows: Power may depend on Core, never the reverse.
    -- Without it a player researches D-T fusion and has no way to make its only ingredient.
    record(fusion.prerequisites["rf-gas-mixing"] ~= nil,
      "and the mixer that makes its only ingredient")
  end
  record(not force.recipes["rf-d-t-plasma"].enabled,
    "the D-T plasma recipe is locked until it is researched")
  record(not force.recipes["rf-isotope-collector"].enabled,
    "and so is the collector, which moved to rf-tritium-breeding")

  force.research_all_technologies()

  surface.request_to_generate_chunks({ 0, 0 }, 8)
  surface.force_generate_chunk_requests()
  local tiles = {}
  for x = -80, 120 do
    for y = -30, 40 do tiles[#tiles + 1] = { name = "landfill", position = { x, y } } end
  end
  surface.set_tiles(tiles)
  for _, e in pairs(surface.find_entities_filtered({ area = { { -80, -30 }, { 120, 40 } } })) do
    if e.type ~= "character" then e.destroy() end
  end

  -- ------------------------------------------------------------------ dt and dd
  --
  -- Identical rigs, identical feed temperature, one fluid different. Everything the comparison
  -- claims rests on their being otherwise the same, so they are built by the same function.
  local dt = reactor_at(surface, force, 0.5, DT)
  power(surface, force, { 12, 5 })
  local dd = reactor_at(surface, force, -60.5, DD)
  power(surface, force, { -48, 5 })

  -- A collector bolted to the D-T reactor, flush against its south face the way check-breeding
  -- does it. It must stay empty.
  local rbox = prototypes.entity["rf-reactor"].selection_box
  local cbox = prototypes.entity["rf-isotope-collector"].selection_box
  local collector = must(surface.create_entity({
    name = "rf-isotope-collector",
    position = {
      dt.position.x,
      dt.position.y + rbox.right_bottom.y + (cbox.right_bottom.y - cbox.left_top.y) / 2,
    },
    force = force, direction = defines.direction.south, raise_built = true,
  }), "rf-isotope-collector")

  -- ------------------------------------------------------------------ heater
  --
  -- The chain step between the tiers: Core's rf-d-t-mix into Power's rf-d-t-plasma, in the machine
  -- the D-D tier already built. Fed by an infinity pipe so this measures the recipe rather than
  -- whatever is upstream of it.
  local heater = must(surface.create_entity({
    name = "rf-heater", position = { 100.5, 0.5 }, force = force,
  }), "rf-heater")
  heater.set_recipe("rf-d-t-plasma")
  power(surface, force, { 108, 5 })
  local index = box_of(heater, MIX)
  if not index then error("the heater has no box that will take " .. MIX) end
  for _, connection in pairs(heater.fluidbox.get_pipe_connections(index)) do
    local supply = must(surface.create_entity({
      name = "infinity-pipe", position = connection.target_position, force = force,
    }), "supply for " .. MIX)
    supply.set_infinity_pipe_filter({ name = MIX, percentage = 1, mode = "at-least" })
  end

  storage.rig = { dt = dt, dd = dd, collector = collector, heater = heater }
  storage.sold = { dt = 0, dd = 0 }
  log("DT-RIG built")
end)

-- Drain both reactors' output boxes and keep the running total.
--
-- Without this there is nothing to compare. A reactor's energy box is 1000 units and both reactors
-- fill theirs within a second, so reading the boxes at the end compares two saturated buffers and
-- returns 1000 against 1000 whatever the reaction is doing -- which is exactly what the first
-- version of this rig reported. Draining is also what a heat exchanger does, so this measures the
-- reactor rather than perturbing it.
script.on_event(defines.events.on_tick, function()
  local r = storage.rig
  if not r then return end
  for key, reactor in pairs({ dt = r.dt, dd = r.dd }) do
    local produced = reactor.fluidbox[2]
    if produced then
      storage.sold[key] = storage.sold[key] + produced.amount
      reactor.fluidbox[2] = nil
    end
  end
end)

script.on_nth_tick(CHECK_AT, function()
  if game.tick == 0 or storage.done then return end
  storage.done = true
  local r = storage.rig

  -- ------------------------------------------------------------ the reactor burns D-T at all
  --
  -- The claim #28 turns on, and the one a leftover fluid box filter would break silently: an
  -- unfiltered input box means a reactor burns whichever plasma is plumbed to it.
  local plasma = r.dt.fluidbox[1]
  record(plasma ~= nil and plasma.name == DT,
    "the reactor accepts D-T plasma through the box that used to be filtered to D-D",
    plasma and plasma.name or "nothing in the box")

  local dt_max = prototypes.fluid[DT].max_temperature
  record(plasma ~= nil and plasma.temperature >= dt_max * 0.999,
    "and ignites: the plasma runs up to the top of its range and parks there",
    plasma and string.format("%.4g C against a ceiling of %.4g", plasma.temperature, dt_max) or "no plasma")

  -- ------------------------------------------------------------ materially different from D-D
  --
  -- Both reactors are fed at the same temperature and have run for the same time, so the only thing
  -- separating these two numbers is the reaction. Compared on reactor energy because that is what a
  -- player is paid; the temperature above already says the two plasmas are in different regimes.
  local dd_plasma = r.dd.fluidbox[1]
  record(dd_plasma ~= nil and dd_plasma.name == DD, "the D-D reactor beside it is unchanged",
    dd_plasma and string.format("%s at %.4g C", dd_plasma.name, dd_plasma.temperature) or "nothing")

  -- Totals off the drain above, in megajoules: one unit of rf-reactor-energy is one MJ.
  local dt_sold, dd_sold = storage.sold.dt, storage.sold.dd
  record(dt_sold > 0 and dd_sold > 0, "both reactors sold energy over the run",
    string.format("D-T %.4g MJ, D-D %.4g MJ", dt_sold, dd_sold))
  -- Five times is loose on purpose. It exists to catch a fuel row copied from D-D and not edited,
  -- which would make the two identical; the actual figure is reported so a rebalance shows up as a
  -- number moving rather than as a check that still passes.
  record(dt_sold > 5 * dd_sold, "D-T yields materially more than D-D at the same feed temperature",
    string.format("%.1fx  (%.4g MW against %.4g MW)",
      dt_sold / dd_sold, dt_sold / (CHECK_AT / 60), dd_sold / (CHECK_AT / 60)))

  -- ------------------------------------------------------------ D-T breeds nothing
  --
  -- The alpha is helium-4, which ADR 0010's fluid set does not contain, and the neutron is what
  -- this mod already sells as reactor energy. A products table copied from D-D and not edited would
  -- fill this collector; nothing else in this rig would notice.
  local bred = holds(r.collector, "rf-tritium") + holds(r.collector, "rf-helium-3")
  record(bred == 0, "a D-T reactor breeds nothing, so its collector stays empty",
    string.format("%.6g units in the collector bolted to it", bred))

  -- ------------------------------------------------------------ the heater makes the fuel
  local made = holds(r.heater, DT)
  local status = "unknown"
  for name, value in pairs(defines.entity_status) do
    if value == r.heater.status then status = name end
  end
  record(made > 0, "the plasma heater turns Core's D-T mix into D-T plasma",
    string.format("%.6g units of %s, status %s", made, DT, status))

  local report = storage.report
  report.lines[#report.lines + 1] = string.format("%s: %d checks, %d failures",
    report.failures == 0 and "PASS" or "FAIL", #report.lines, report.failures)
  for _, line in ipairs(report.lines) do log("DT-RIG " .. line) end
end)
'@
    Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') `
        -Value $lua.Replace('__PLASMAFEED__', $feed).Replace('__TICKS__', "$Ticks")
}

$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }

try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled @() -Mods ($ourMods + $rigName)
    Write-Rig

    $save = Join-Path $temp 'd-t.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', "$($Ticks + 60)", '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'DT-RIG (ok|FAIL|PASS)' |
        ForEach-Object { ($_ -split 'DT-RIG ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the rig reported nothing; it never reached its check tick.' }

    foreach ($line in $reported) { Write-Host "  $line" }

    $verdict = $reported | Where-Object { $_ -match '^(PASS|FAIL): ' } | Select-Object -Last 1
    if (-not $verdict)              { throw 'the rig produced no verdict line.' }
    if ($verdict -notmatch '^PASS') { throw "the D-T tier is broken: $verdict" }

    Write-Host ''
    Write-Host 'OK - the same reactor burns D-T, it ignites, it breeds nothing, and the heater makes its fuel.'
}
finally {
    if ($KeepTemp) { Write-Host ''; Write-Host "temp kept at: $temp" }
    Remove-ModJunctions -ModDirectory $modDir
    if (-not $KeepTemp) { Remove-TempDirectory -Path $temp -Label 'check-d-t' }
}
