#Requires -Version 7
<#
.SYNOPSIS
    Checks that the high-capacity steam pair delivers what it declares, and that it is ten times the
    ordinary pair measured rather than asserted. Discharges #32.

.DESCRIPTION
    THE FAILURE THIS RIG EXISTS FOR is silent and is one field wide.

    A generator's real output is fluid_usage_per_tick x 60 x (maximum_temperature -
    default_temperature) x heat_capacity x effectivity. `max_power_output` is a SEPARATE field.
    Multiply the fluid usage by ten and leave max_power_output alone and the machine eats ten times
    the steam for the same power -- for ever, with no error, no status change and a tooltip that
    reads correctly. Vanilla's steam turbine sidesteps it by declaring no max_power_output at all and
    letting the engine derive one; this repository pins every stat that affects balance, so it
    declares one and has to prove the two agree.

    So the arithmetic is checked against the prototypes AND the machines are measured running. The
    first would pass on a mod that never worked; the second would pass on a lucky cancellation.

    WHAT IS BUILT

      turbines    An rf-hc-turbine and a vanilla steam-turbine, each on its own infinity pipe of
                  500 C steam, on one electric network with a load large enough that neither is
                  throttled by demand. Production is read per prototype out of the network's own
                  statistics, so the two are separated without isolating them.
      exchangers  An rf-hc-exchanger and an rf-heat-exchanger, each fed water and reactor energy by
                  infinity pipes, with their steam drained and totalled every tick. Draining is what
                  makes the measurement mean anything: both fill their output box in under a second,
                  so reading the box at the end compares two saturated buffers.
      chain       An rf-hc-exchanger with an rf-hc-turbine directly on its steam outlet and nothing
                  between them, which is the pair as a player builds it. It must produce power from
                  real exchanger steam rather than from an infinity pipe.

    The technology gate and the prerequisite closure are checked off the force's own tables before
    anything is researched.

.PARAMETER FactorioExe
    Path to Factorio.exe. Defaults to $env:FACTORIO_EXE, then the Steam install on this machine.

.PARAMETER Ticks
    Ticks to run before checking.

.PARAMETER Quality
    Also enable Wube's bundled Quality mod and report what quality does to the pair. ADR 0003
    tolerates Space Age rather than targeting it, so the default run is base-only like every other
    rig here; this switch exists because the predecessor's author warned that "certain buildings in
    this mod get insanely overpowered with quality" without naming them, and rfp-hc-turbine is the
    obvious suspect. Reported rather than asserted -- see the note in the rig.

.PARAMETER KeepTemp
    Keep the save, the rig mod and the captured output.

.EXAMPLE
    pwsh -File scripts/check-hc.ps1
    pwsh -File scripts/check-hc.ps1 -Quality
#>
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [ValidateRange(600, 200000)] [int] $Ticks = 3600,
    [switch] $Quality,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/factorio-lib.ps1"

$repoRoot = Split-Path $PSScriptRoot -Parent
$ourMods  = @('realistic-fusion-refreshed-core', 'realistic-fusion-refreshed')
$rigName  = 'rf-hc-rig'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-hc-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

function Write-Rig {
    @{
        name = $rigName; version = '0.0.1'; title = 'High-capacity generation check'
        author = 'check-hc.ps1'; factorio_version = '2.0'
        dependencies = @('base >= 2.0.77', 'realistic-fusion-refreshed', 'realistic-fusion-refreshed-core')
    } | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

    $lua = @'
-- Generated by scripts/check-hc.ps1. Nothing here ships.

local CHECK_AT = __TICKS__
local WITH_QUALITY = __QUALITY__

local HC_EXCHANGER = "rf-hc-exchanger"
local HC_TURBINE   = "rf-hc-turbine"
local EXCHANGER    = "rf-heat-exchanger"
local TURBINE      = "steam-turbine"
local ENERGY       = "rf-reactor-energy"

local function record(ok, name, detail)
  storage.report = storage.report or { lines = {}, failures = 0 }
  if not ok then storage.report.failures = storage.report.failures + 1 end
  storage.report.lines[#storage.report.lines + 1] = string.format("%s  %s%s",
    ok and "ok  " or "FAIL", name, detail and ("  -- " .. detail) or "")
end

--- Reported without a pass or fail, for facts that are worth having on the record but are not this
--- ticket's to bound -- see the quality section.
local function note(name, detail)
  storage.report = storage.report or { lines = {}, failures = 0 }
  storage.report.lines[#storage.report.lines + 1] = string.format("note  %s  -- %s", name, detail)
end

local function near(actual, expected, tolerance, name, unit)
  local ok = expected ~= 0 and math.abs(actual - expected) / math.abs(expected) <= tolerance
  record(ok, name, string.format("%.6g against %.6g %s (%.2f%%)",
    actual, expected, unit or "", expected ~= 0 and 100 * math.abs(actual - expected) / math.abs(expected) or 0))
end

local function must(entity, what)
  if not entity then error(what .. " refused") end
  return entity
end

local function box_of(entity, fluid)
  for index = 1, #entity.fluidbox do
    local filter = entity.fluidbox.get_filter(index)
    if filter and filter.name == fluid then return index end
  end
  return nil
end

--- Feed every connection of the box carrying `fluid` from an infinity pipe, so the machine is never
--- limited by what is upstream of it -- which is the whole point: this rig measures the machine.
local function feed(surface, force, entity, fluid, temperature)
  local index = box_of(entity, fluid)
  if not index then error(entity.name .. " has no box that takes " .. fluid) end
  for _, connection in pairs(entity.fluidbox.get_pipe_connections(index)) do
    local supply = must(surface.create_entity({
      name = "infinity-pipe", position = connection.target_position, force = force,
    }), "supply of " .. fluid .. " for " .. entity.name)
    supply.set_infinity_pipe_filter({
      name = fluid, percentage = 1, temperature = temperature, mode = "at-least",
    })
  end
  return index
end

--- A substation and a load. The load matters: a generator with nothing drawing from it throttles
--- itself back, so measuring output against an idle network measures the network.
local function power(surface, force, at, draw)
  local pole = must(surface.create_entity({
    name = "substation", position = at, force = force,
  }), "substation")
  local eei = must(surface.create_entity({
    name = "electric-energy-interface", position = { at[1] + 2.5, at[2] + 0.5 }, force = force,
  }), "load")
  eei.power_production = 0
  eei.power_usage = draw
  return pole
end

script.on_init(function()
  local surface = game.surfaces[1]
  local force   = game.forces.player

  -- ------------------------------------------------------------------ the technology gate
  local fusion = force.technologies["rf-d-t-fusion"]
  record(fusion ~= nil, "rf-d-t-fusion exists to unlock the pair")
  for _, recipe in ipairs({ HC_EXCHANGER, HC_TURBINE }) do
    record(not force.recipes[recipe].enabled, recipe .. " is locked until it is researched")
  end

  -- The prerequisite closure, the way scripts/check-blanket.ps1 enforces it for the blanket: every
  -- item these recipes consume has to be craftable inside rf-d-t-fusion's OWN prerequisites, or a
  -- player researches the tier and cannot build it.
  local function research_closure(name, seen)
    if seen[name] then return end
    seen[name] = true
    local tech = force.technologies[name]
    if not tech then return end
    for prerequisite in pairs(tech.prerequisites) do research_closure(prerequisite, seen) end
    tech.researched = true
  end
  research_closure("rf-d-t-fusion", {})

  local outside, checked = {}, 0
  for _, machine in ipairs({ HC_EXCHANGER, HC_TURBINE }) do
    for _, ingredient in pairs(prototypes.recipe[machine].ingredients) do
      local recipe = force.recipes[ingredient.name]
      if recipe then
        checked = checked + 1
        if not recipe.enabled then
          outside[#outside + 1] = machine .. " needs " .. ingredient.name
        end
      end
    end
  end
  record(#outside == 0, "both recipes are craftable inside rf-d-t-fusion's own prerequisites",
    #outside == 0 and string.format("%d ingredients checked", checked)
      or table.concat(outside, "; "))
  -- The count, because a closure check that matched nothing would pass in silence. Both recipes
  -- take four ingredients and every one of them is an item named after its own recipe.
  record(checked == 8, "and it looked at all eight ingredients", string.format("%d checked", checked))

  force.research_all_technologies()

  surface.request_to_generate_chunks({ 0, 0 }, 10)
  surface.force_generate_chunk_requests()
  local tiles = {}
  for x = -40, 90 do
    for y = -30, 70 do tiles[#tiles + 1] = { name = "landfill", position = { x, y } } end
  end
  surface.set_tiles(tiles)
  for _, e in pairs(surface.find_entities_filtered({ area = { { -40, -30 }, { 90, 70 } } })) do
    if e.type ~= "character" then e.destroy() end
  end

  -- ------------------------------------------------------------------ the two turbines
  --
  -- On ONE network on purpose. Production is attributed per prototype by the game's own statistics,
  -- so putting them together removes every difference between the two measurements except the
  -- machine -- and the load is far larger than both together, so neither is throttled.
  local hc_turbine = must(surface.create_entity({
    name = HC_TURBINE, position = { 0.5, 0.5 }, force = force,
  }), HC_TURBINE)
  feed(surface, force, hc_turbine, "steam", 500)

  local turbine = must(surface.create_entity({
    name = TURBINE, position = { 20.5, 0.5 }, force = force,
  }), TURBINE)
  feed(surface, force, turbine, "steam", 500)

  local pole = power(surface, force, { 8, 0 }, 500e6)
  power(surface, force, { 20, 8 }, 0)

  -- ------------------------------------------------------------------ the two exchangers
  --
  -- Fed water and reactor energy from infinity pipes, with the steam drained every tick and totalled
  -- (see on_tick). Both fill their output box in well under a second, so an end-of-run reading would
  -- compare two full buffers and report them equal whatever they actually make.
  local hc_exchanger = must(surface.create_entity({
    name = HC_EXCHANGER, position = { 0.5, 40.5 }, force = force,
  }), HC_EXCHANGER)
  feed(surface, force, hc_exchanger, "water", nil)
  feed(surface, force, hc_exchanger, ENERGY, nil)

  local exchanger = must(surface.create_entity({
    name = EXCHANGER, position = { 40.5, 40 }, force = force,
  }), EXCHANGER)
  feed(surface, force, exchanger, "water", nil)
  feed(surface, force, exchanger, ENERGY, nil)

  -- ------------------------------------------------------------------ the pair, coupled
  --
  -- An exchanger with a turbine directly on its steam outlet and nothing between them, which is how
  -- a player builds it. The positions are computed from the two prototypes' own connection geometry
  -- rather than written down -- if they are wrong the turbine simply gets no steam, and the check
  -- says so.
  local chain_exchanger = must(surface.create_entity({
    name = HC_EXCHANGER, position = { 70.5, 40.5 }, force = force,
  }), HC_EXCHANGER)
  feed(surface, force, chain_exchanger, "water", nil)
  feed(surface, force, chain_exchanger, ENERGY, nil)

  local steam_out = chain_exchanger.fluidbox.get_pipe_connections(box_of(chain_exchanger, "steam"))[1]
  local chain_turbine = must(surface.create_entity({
    name = HC_TURBINE,
    -- The turbine's connections are symmetric about its centre, three tiles either way, so its
    -- south connection lands on the exchanger's outlet when its centre is four tiles beyond it.
    position = { steam_out.target_position.x, steam_out.target_position.y - 3 },
    force = force,
  }), HC_TURBINE)
  local chain_pole = power(surface, force, { 78, 40 }, 500e6)

  storage.rig = {
    hc_turbine = hc_turbine, turbine = turbine,
    hc_exchanger = hc_exchanger, exchanger = exchanger,
    chain_exchanger = chain_exchanger, chain_turbine = chain_turbine,
    pole = pole, chain_pole = chain_pole,
  }
  storage.steam = { hc = 0, ordinary = 0 }
  log("HC-RIG built")
end)

-- Drain both measured exchangers and keep the running total, in fluid units.
script.on_event(defines.events.on_tick, function()
  local r = storage.rig
  if not r then return end
  for key, exchanger in pairs({ hc = r.hc_exchanger, ordinary = r.exchanger }) do
    local index = box_of(exchanger, "steam")
    local produced = index and exchanger.fluidbox[index]
    if produced then
      storage.steam[key] = storage.steam[key] + produced.amount
      exchanger.fluidbox[index] = nil
    end
  end
end)

script.on_nth_tick(CHECK_AT, function()
  if game.tick == 0 or storage.done then return end
  storage.done = true
  local r = storage.rig
  local seconds = CHECK_AT / 60

  -- ------------------------------------------------------------ the arithmetic, off the prototypes
  --
  -- The check the whole ticket is written around. Steam's own numbers are read from the fluid rather
  -- than written down, so this stays true if base ever changes them.
  local steam = prototypes.fluid["steam"]
  local joules_per_unit = (500 - steam.default_temperature) * steam.heat_capacity

  local function derived(name)
    local p = prototypes.entity[name]
    return p.fluid_usage_per_tick * 60
      * (p.maximum_temperature - steam.default_temperature) * steam.heat_capacity
      * (p.effectivity or 1)
  end

  -- Vanilla first, as the control on the formula itself. If this line is wrong then every figure
  -- below it is measuring the formula rather than the machine.
  near(derived(TURBINE), prototypes.entity[TURBINE].max_power_output * 60, 1e-6,
    "the output formula reproduces vanilla's steam turbine", "W")
  near(derived(HC_TURBINE), prototypes.entity[HC_TURBINE].max_power_output * 60, 1e-6,
    "and rf-hc-turbine's declared max_power_output matches the steam it drinks", "W")

  -- ------------------------------------------------------------ measured, running
  local statistics = r.pole.electric_network_statistics
  local function produced(name)
    return statistics and statistics.get_flow_count({
      name = name, category = "output",
      precision_index = defines.flow_precision_index.one_minute,
    }) or 0
  end
  local hc_power, ordinary_power = produced(HC_TURBINE), produced(TURBINE)

  record(hc_power > 0 and ordinary_power > 0, "both turbines are generating",
    string.format("hc %.4g, ordinary %.4g", hc_power, ordinary_power))
  -- THE ACCEPTANCE CRITERION. A turbine whose max_power_output had been left at vanilla's would sit
  -- at a ratio of one here while consuming ten times the steam, and nothing else in this rig would
  -- notice.
  near(hc_power / ordinary_power, 10, 0.02,
    "and the high-capacity one really is ten times the ordinary one", "x")

  -- ------------------------------------------------------------ the exchangers, measured
  --
  -- A boiler's energy_consumption is what it puts into the fluid, so the steam it can make is that
  -- divided by the joules a unit carries. Compared against the prototype rather than a constant.
  local function expected_steam(name)
    return prototypes.entity[name].get_max_energy_usage() * 60 / joules_per_unit
  end
  local hc_steam = storage.steam.hc / seconds
  local ordinary_steam = storage.steam.ordinary / seconds

  near(hc_steam, expected_steam(HC_EXCHANGER), 0.02,
    "rf-hc-exchanger makes the steam its energy consumption says it should", "units/s")
  near(ordinary_steam, expected_steam(EXCHANGER), 0.02,
    "and rf-heat-exchanger still makes its own", "units/s")
  near(hc_steam / ordinary_steam, 10, 0.02,
    "so the high-capacity exchanger is ten ordinary ones", "x")

  -- ------------------------------------------------------------ building count
  --
  -- The ticket's second criterion, stated as the arithmetic a player actually does: how many
  -- machines it takes to absorb one ignited D-T reactor, which sells on the order of 320 MW.
  local reactor_mw = 320
  -- Called with no arguments, not with the prototype as self: Factorio hands these out already
  -- bound, so passing the prototype makes it the quality argument and the engine answers "Invalid
  -- QualityID" rather than anything about the call.
  local function megawatts(name, getter)
    return prototypes.entity[name][getter]() * 60 / 1e6
  end
  local hc_pair = reactor_mw / megawatts(HC_EXCHANGER, "get_max_energy_usage")
    + reactor_mw / megawatts(HC_TURBINE, "get_max_power_output")
  local ordinary_pair = reactor_mw / megawatts(EXCHANGER, "get_max_energy_usage")
    + reactor_mw / megawatts(TURBINE, "get_max_power_output")
  record(hc_pair * 5 < ordinary_pair,
    "one ignited D-T reactor needs far fewer buildings on the high-capacity pair",
    string.format("%.1f buildings against %.1f", hc_pair, ordinary_pair))

  -- ------------------------------------------------------------ the pair, coupled
  local chain_statistics = r.chain_pole.electric_network_statistics
  local chained = chain_statistics and chain_statistics.get_flow_count({
    name = HC_TURBINE, category = "output",
    precision_index = defines.flow_precision_index.one_minute,
  }) or 0
  local status = "unknown"
  for name, value in pairs(defines.entity_status) do
    if value == r.chain_turbine.status then status = name end
  end
  record(chained > 0 and r.chain_turbine.status == defines.entity_status.working,
    "a turbine plumbed straight onto an exchanger runs on its steam",
    string.format("flow %.4g, status %s", chained, status))

  -- ------------------------------------------------------------ quality
  --
  -- The predecessor's author warned that "certain buildings in this mod get insanely overpowered
  -- with quality" and named none; rfp-hc-turbine is the obvious suspect, since quality is the one
  -- thing that scales a generator's output without scaling the steam it drinks.
  --
  -- REPORTED, NOT ASSERTED. What quality should do to this tier is a balance decision and ADR 0003
  -- tolerates Space Age rather than targeting it, so this rig's job is to put the number on the
  -- record rather than to bound it.
  if WITH_QUALITY then
    for _, quality in ipairs({ "normal", "uncommon", "rare", "epic", "legendary" }) do
      if prototypes.quality[quality] then
        local hc = prototypes.entity[HC_TURBINE].get_max_power_output(quality)
        local ordinary = prototypes.entity[TURBINE].get_max_power_output(quality)
        note("quality " .. quality, string.format(
          "rf-hc-turbine %.4g MW, steam-turbine %.4g MW, ratio %.3f",
          hc * 60 / 1e6, ordinary * 60 / 1e6, hc / ordinary))
      end
    end
  end

  local report = storage.report
  report.lines[#report.lines + 1] = string.format("%s: %d checks, %d failures",
    report.failures == 0 and "PASS" or "FAIL", #report.lines, report.failures)
  for _, line in ipairs(report.lines) do log("HC-RIG " .. line) end
end)
'@
    Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') `
        -Value $lua.Replace('__TICKS__', "$Ticks").Replace('__QUALITY__', $(if ($Quality) { 'true' } else { 'false' }))
}

$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }

try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    $enabled = if ($Quality) { @('quality') } else { @() }
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled $enabled -Mods ($ourMods + $rigName)
    Write-Rig

    $save = Join-Path $temp 'hc.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', "$($Ticks + 60)", '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'HC-RIG (ok|FAIL|PASS|note)' |
        ForEach-Object { ($_ -split 'HC-RIG ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the rig reported nothing; it never reached its check tick.' }

    foreach ($line in $reported) { Write-Host "  $line" }

    $verdict = $reported | Where-Object { $_ -match '^(PASS|FAIL): ' } | Select-Object -Last 1
    if (-not $verdict)              { throw 'the rig produced no verdict line.' }
    if ($verdict -notmatch '^PASS') { throw "the high-capacity pair is broken: $verdict" }

    Write-Host ''
    Write-Host 'OK - both machines deliver what they declare, and each is ten times its ordinary'
    Write-Host '     counterpart measured rather than asserted.'
}
finally {
    if ($KeepTemp) { Write-Host ''; Write-Host "temp kept at: $temp" }
    Remove-ModJunctions -ModDirectory $modDir
    if (-not $KeepTemp) { Remove-TempDirectory -Path $temp -Label 'check-hc' }
}
