#Requires -Version 7
<#
.SYNOPSIS
    Checks that a running D-D reactor breeds tritium and helium-3, that they can be captured and
    stored, and that Core's gas mixer turns them back into reactor fuel. Discharges #27.

.DESCRIPTION
    The reactors are the breeder (CONTEXT.md, ADR 0010): half of every D-D reaction leaves a triton
    behind and half leaves a helium-3. tests/test-reactor-logic.lua asserts the arithmetic; this
    asserts that the arithmetic reaches a pipe.

    THE MODULE SEAM, EXERCISED RATHER THAN ASSERTED

    #27 exists to prove the seam ADR 0010 defines: rf-tritium and rf-helium-3 are realistic-fusion-refreshed-core
    prototypes, and the thing that produces them is in realistic-fusion-refreshed. The last case below is what
    actually tests that -- a Core machine consuming, through an ordinary pipe, a fluid a Power
    reactor made. If the seam were wrong in either direction that recipe would not run.

    WHY THERE IS A COLLECTOR AT ALL

    A boiler has exactly two fluid boxes and rf-reactor spends both: plasma in and out on the
    input-output box ADR 0011's fluid coupling rests on, reactor energy on the other. By-products
    need a third and a fourth, so they need another entity. rf-isotope-collector is bolted to the
    reactor and filled by control.lua from the same reaction count the energy output comes from --
    so what it collects follows the simulation rather than a recipe's fixed ratio.

    WHAT IS BUILT

      bolted     A reactor with a collector against its south face, both outputs piped to storage
                 tanks. Both by-products must arrive, in equal measure, and must reach the tanks.
      cool       The same reactor and collector, given plasma at the temperature a heater injects
                 it at and no power to raise it. It must breed far less, which is what says the
                 rate came from the simulation rather than from a fixed ratio.
      spare      A reactor with two collectors, whose paired one is destroyed halfway through. It
                 has to find the other. Nothing raises an event when an entity is removed, so this
                 is the case where a reactor can silently stop breeding with a perfectly good
                 collector sitting against it.
      bare       A reactor with no collector. It must run exactly as well as the other one: the
                 by-products are computed either way and simply vent, so bolting a collector on
                 later starts collecting at once rather than dumping a backlog.
      mixer      Core's rf-gas-mixer running rf-d-t-mixing on the deuterium chain's output and the
                 reactor's, which is the seam end to end.

.PARAMETER FactorioExe
    Path to Factorio.exe. Defaults to $env:FACTORIO_EXE, then the Steam install on this machine.

.PARAMETER Ticks
    Ticks to run before checking. The default is long enough for the reactor to be fusing hard
    rather than merely warm, which is what makes the equal-measure check meaningful.

.PARAMETER KeepTemp
    Keep the save, the rig mod and the captured output.

.EXAMPLE
    pwsh -File scripts/check-breeding.ps1
#>
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [ValidateRange(600, 200000)] [int] $Ticks = 7200,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/factorio-lib.ps1"

$repoRoot = Split-Path $PSScriptRoot -Parent
$ourMods  = @('realistic-fusion-refreshed-core', 'realistic-fusion-refreshed')
$rigName  = 'rf-breeding-rig'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-breed-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

function Write-Rig {
    @{
        name = $rigName; version = '0.0.1'; title = 'D-D breeding check'
        author = 'check-breeding.ps1'; factorio_version = '2.0'
        dependencies = @('base >= 2.0.77', 'realistic-fusion-refreshed', 'realistic-fusion-refreshed-core')
    } | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

    $feed = Write-PlasmaFeed -RigDirectory $rigDir

    $lua = @'
-- Generated by scripts/check-breeding.ps1. Nothing here ships.

local CHECK_AT = __TICKS__

local PLASMA   = "rf-d-d-plasma"
local TRITIUM  = "rf-tritium"
local HELIUM3  = "rf-helium-3"
local FEED     = "__PLASMAFEED__"

-- How far around a collector to look for what its reactor bred. Wide enough to take in its pipe
-- run and both tanks, and well short of the next cell sixty tiles away.
local BOLTED = 25

local lines = {}
local failures = 0

local function record(ok, name, detail)
  if not ok then failures = failures + 1 end
  lines[#lines + 1] = string.format("%s  %s%s", ok and "ok  " or "FAIL", name,
    detail and ("  -- " .. detail) or "")
end

local function must(entity, what)
  if not entity then error(what .. " refused") end
  return entity
end

local function amount_of(entity, index)
  local contents = entity.fluidbox[index]
  return contents and contents.amount or 0
end

local function box_of(entity, fluid)
  for index = 1, #entity.fluidbox do
    local filter = entity.fluidbox.get_filter(index)
    if filter and filter.name == fluid then return index end
  end
  return nil
end

--- Total of one fluid across every box of an entity, whatever box it landed in.
local function holds(entity, fluid)
  local total = 0
  for index = 1, #entity.fluidbox do
    local contents = entity.fluidbox[index]
    if contents and contents.name == fluid then total = total + contents.amount end
  end
  return total
end

--- Everything within `radius` of an entity that is holding one fluid.
--
-- What was bred is not what the collector is holding: it drains into its pipe run as fast as
-- control.lua fills it, so the box alone reports a thousandth of the total and looks exactly like
-- breeding being broken.
--
-- get_fluid_segment_contents would have been the tidy way to ask and returns nil here, which is a
-- fact worth recording rather than working around silently: only an input-output box joins the
-- fluid segment it is plumbed to (#47, ADR 0011). The collector's two boxes are declared "output",
-- so they push into the pipe's segment without belonging to it, and there is no segment to ask.
local function nearby_holds(entity, fluid, radius)
  local at = entity.position
  local total = 0
  for _, found in pairs(entity.surface.find_entities_filtered({
    area = { { at.x - radius, at.y - radius }, { at.x + radius, at.y + radius } },
  })) do
    total = total + holds(found, fluid)
  end
  return total
end

--- Place an entity so that one of its fluid connections lands on a chosen tile.
--
-- A storage tank is three by three and carries four connections at fixed offsets rather than one
-- on every edge tile, so butting it against the end of a pipe run lines up only by luck. Asked
-- where its connection actually points and moved by the difference, the way bench-mod-links does.
local function place_facing(surface, force, name, target, seed)
  local probe = must(surface.create_entity({ name = name, position = seed, force = force }), name)
  local at = probe.fluidbox.get_pipe_connections(1)[1].target_position
  local position = { seed[1] + (target[1] - at.x), seed[2] + (target[2] - at.y) }
  probe.destroy()
  return must(surface.create_entity({ name = name, position = position, force = force }), name)
end

local function power(surface, force, at)
  must(surface.create_entity({ name = "substation", position = at, force = force }), "substation")
  local eei = must(surface.create_entity({
    name = "electric-energy-interface", position = { at[1] + 2.5, at[2] + 0.5 }, force = force,
  }), "power source")
  eei.power_production = 4e6
end

local function pipe_run(surface, force, from, step, count)
  for i = 0, count - 1 do
    local at = { from[1] + step[1] * i, from[2] + step[2] * i }
    if not surface.find_entity("pipe", at) then
      must(surface.create_entity({ name = "pipe", position = at, force = force }),
        string.format("pipe at (%g, %g)", at[1], at[2]))
    end
  end
end

--- A reactor on a plasma feed, at `ox`. Geometry is read off the prototypes rather than written
--- down: #49 is what happens when a rig remembers a machine's size and the machine changes.
local function reactor_at(surface, force, ox, temperature)
  local reactor = must(surface.create_entity({
    name = "rf-reactor", position = { ox, 0.5 }, force = force, raise_built = true,
  }), "rf-reactor")
  local west = reactor.fluidbox.get_pipe_connections(1)[1].target_position
  local feed = must(surface.create_entity({
    name = FEED, position = { west.x, west.y }, force = force,
  }), "plasma feed")
  feed.set_infinity_pipe_filter({
    name = PLASMA, percentage = 1, temperature = temperature, mode = "at-least",
  })
  return reactor
end

--- A collector bolted flush to a reactor's south face, and what it drains into.
--
-- Flush is computed from both selection boxes rather than written down: the collector has to land
-- inside the one-tile margin entity-management's attach() searches, and "nine tiles south" is
-- exactly the remembered constant #49 was about.
--
-- raise_built, and building it second is the point: a player bolts the collector on after the
-- reactor, and it is the build event that pairs them. Placing it silently would exercise a path no
-- player can take and miss the one they do.
local function bolt_on(surface, force, reactor, tank_seed)
  local rbox = prototypes.entity["rf-reactor"].selection_box
  local cbox = prototypes.entity["rf-isotope-collector"].selection_box
  -- Turned south so its helium-3 outlet faces away from the reactor rather than into it.
  local collector = must(surface.create_entity({
    name = "rf-isotope-collector",
    position = {
      reactor.position.x,
      reactor.position.y + rbox.right_bottom.y + (cbox.right_bottom.y - cbox.left_top.y) / 2,
    },
    force = force, direction = defines.direction.south, raise_built = true,
  }), "rf-isotope-collector")

  -- Both by-products out to ordinary tanks through ordinary pipes: they are cold gases, not
  -- plasma, so nothing about them is contained (#26) and this is what says so.
  local tanks, boxes = {}, {}
  for nth, fluid in ipairs({ TRITIUM, HELIUM3 }) do
    local index = box_of(collector, fluid)
    if not index then error("the collector has no box filtered to " .. fluid) end
    boxes[fluid] = index
    local at = collector.fluidbox.get_pipe_connections(index)[1].target_position
    local step = { at.x - collector.position.x, at.y - collector.position.y }
    local length = math.max(math.abs(step[1]), math.abs(step[2]))
    step = { step[1] / length, step[2] / length }
    local RUN = 3
    pipe_run(surface, force, { at.x, at.y }, step, RUN)
    -- The tank's connection has to land on the tile just past the last pipe, so it is placed by
    -- probing rather than by arithmetic on its size.
    tanks[fluid] = place_facing(surface, force, "storage-tank",
      { at.x + step[1] * (RUN - 1), at.y + step[2] * (RUN - 1) },
      { tank_seed[1] + 6 * nth, tank_seed[2] })
  end
  return collector, tanks, boxes
end

script.on_init(function()
  local surface = game.surfaces[1]
  local force   = game.forces.player
  force.research_all_technologies()

  surface.request_to_generate_chunks({ 0, 0 }, 8)
  surface.force_generate_chunk_requests()
  local tiles = {}
  for x = -180, 140 do
    for y = -30, 40 do tiles[#tiles + 1] = { name = "landfill", position = { x, y } } end
  end
  surface.set_tiles(tiles)
  for _, e in pairs(surface.find_entities_filtered({ area = { { -180, -30 }, { 140, 40 } } })) do
    if e.type ~= "character" then e.destroy() end
  end

  -- ------------------------------------------------------------------ bolted
  local reactor = reactor_at(surface, force, 0.5, 6e8)
  power(surface, force, { 12, 5 })

  local collector, tanks, boxes = bolt_on(surface, force, reactor, { 40.5, 25.5 })

  -- ------------------------------------------------------------------ cool
  --
  -- The same reactor and the same collector, given plasma at the temperature a heater injects it
  -- at and no power to raise it. It is the check that breeding follows the simulation rather than a
  -- fixed ratio -- which is the reason the by-products come out of control.lua at all instead of
  -- out of an extraction recipe. A recipe would breed the same in both cells.
  local cool = reactor_at(surface, force, -60.5, 1e6)
  local cool_collector = bolt_on(surface, force, cool, { -40.5, 25.5 })

  -- ------------------------------------------------------------------ spare
  --
  -- A reactor with TWO collectors, the second one bolted on beside the first. It is paired to the
  -- lower unit_number, which is the one built first; halfway through the run that one is destroyed
  -- and the reactor has to find the other.
  --
  -- Nothing raises an event when an entity is removed, so this is the case where a reactor can
  -- silently stop breeding while a perfectly good collector sits against it. Found on review.
  local spare = reactor_at(surface, force, -120.5, 6e8)
  power(surface, force, { -108, 5 })
  local first = bolt_on(surface, force, spare, { -100.5, 25.5 })
  -- On the NORTH face, where the first one is on the south. Not for symmetry: put side by side on
  -- the same face, the second collector's outlet lands on the first one's pipe run and drains into
  -- its tanks, so what it holds is a steady-state trickle rather than a total and the check reads
  -- as though almost nothing arrived. Nothing is plumbed to it here, so it simply fills.
  --
  -- North is free in this rig -- the reactor's energy outlet is there and nothing is connected to
  -- it -- and the collector's own outlets point away from the reactor.
  local rbox = prototypes.entity["rf-reactor"].selection_box
  local cbox = prototypes.entity["rf-isotope-collector"].selection_box
  local second = must(surface.create_entity({
    name = "rf-isotope-collector",
    position = {
      spare.position.x,
      spare.position.y + rbox.left_top.y - (cbox.right_bottom.y - cbox.left_top.y) / 2,
    },
    force = force, raise_built = true,
  }), "the spare collector")
  if second.unit_number < first.unit_number then
    error("the spare rig assumes the first collector has the lower unit_number")
  end

  -- ------------------------------------------------------------------ bare
  local bare = reactor_at(surface, force, 60.5, 6e8)
  power(surface, force, { 72, 5 })

  -- ------------------------------------------------------------------ mixer
  --
  -- Core's machine, on Core's recipe, consuming one fluid from Core's chain and one a Power
  -- reactor bred. Fed by infinity pipes so this measures the recipe rather than the throughput of
  -- whatever is upstream.
  local mixer = must(surface.create_entity({
    name = "rf-gas-mixer", position = { 120.5, 0.5 }, force = force,
  }), "rf-gas-mixer")
  mixer.set_recipe("rf-d-t-mixing")
  power(surface, force, { 126, 5 })
  for _, fluid in ipairs({ "rf-deuterium", TRITIUM }) do
    local index = box_of(mixer, fluid)
    if not index then error("the mixer has no box filtered to " .. fluid) end
    for _, connection in pairs(mixer.fluidbox.get_pipe_connections(index)) do
      local supply = must(surface.create_entity({
        name = "infinity-pipe", position = connection.target_position, force = force,
      }), "supply for " .. fluid)
      supply.set_infinity_pipe_filter({ name = fluid, percentage = 1, mode = "at-least" })
    end
  end

  storage.rig = {
    reactor = reactor, collector = collector, bare = bare, mixer = mixer,
    cool = cool, cool_collector = cool_collector,
    spare = spare, first_collector = first, second_collector = second,
    tritium_tank = tanks[TRITIUM], helium_tank = tanks[HELIUM3],
    tritium_box = boxes[TRITIUM], helium_box = boxes[HELIUM3],
  }
  log("BREED-RIG built")
end)

-- Halfway through, take away the collector the spare reactor is paired to. Nothing raises an
-- event for this, which is the whole point of the case.
script.on_nth_tick(math.floor(CHECK_AT / 2), function()
  if game.tick == 0 or storage.pulled then return end
  storage.pulled = true
  storage.rig.first_collector.destroy()
end)

script.on_nth_tick(CHECK_AT, function()
  if game.tick == 0 or storage.done then return end
  storage.done = true
  local r = storage.rig

  -- ------------------------------------------------------------ the reactor breeds
  local plasma = r.reactor.fluidbox[1]
  record(plasma ~= nil and plasma.temperature > 1e8,
    "the reactor is fusing rather than merely warm",
    plasma and string.format("%.4g C", plasma.temperature) or "no plasma")

  -- Everything around the collector, not just its own box. The radius stops well short of the bare
  -- reactor sixty tiles away and of the mixer, which is fed tritium from an infinity pipe and would
  -- otherwise be counted as something this reactor bred.
  local tritium = nearby_holds(r.collector, TRITIUM, BOLTED)
  local helium  = nearby_holds(r.collector, HELIUM3, BOLTED)
  record(tritium > 0, "a running reactor breeds tritium", string.format("%.6g", tritium))
  record(helium > 0, "a running reactor breeds helium-3", string.format("%.6g", helium))

  -- The 50/50 branch, end to end. The two are produced in equal measure every step, so any gap
  -- here is something the collector or the plumbing did, not the physics.
  record(math.abs(tritium - helium) <= 1e-6 * math.max(tritium, helium, 1),
    "the two by-products arrive in equal measure",
    string.format("%.6g vs %.6g", tritium, helium))

  -- Neither may turn into the other. The collector is a boiler and a boiler converts its input box
  -- into its output box -- which is why both of its boxes are declared "output", leaving it
  -- nothing to convert. If that ever regresses this is what notices.
  record(amount_of(r.collector, r.tritium_box) == holds(r.collector, TRITIUM)
     and amount_of(r.collector, r.helium_box) == holds(r.collector, HELIUM3),
    "neither by-product has turned into the other inside the collector")
  record(holds(r.tritium_tank, HELIUM3) == 0 and holds(r.helium_tank, TRITIUM) == 0,
    "each by-product reached its own tank and only its own")

  -- ------------------------------------------------------------ captured and stored
  record(holds(r.tritium_tank, TRITIUM) > 0, "tritium reaches an ordinary storage tank",
    string.format("%.6g", holds(r.tritium_tank, TRITIUM)))
  record(holds(r.helium_tank, HELIUM3) > 0, "helium-3 reaches an ordinary storage tank",
    string.format("%.6g", holds(r.helium_tank, HELIUM3)))

  -- ------------------------------------------------------------ breeding follows the simulation
  --
  -- The claim the whole design turns on, and the reason the by-products come out of control.lua
  -- rather than out of an extraction recipe: what a reactor breeds depends on what it actually
  -- fused. The cool cell is the same reactor and the same collector, given plasma at the
  -- temperature a heater injects it at and no power to raise it. A fixed recipe ratio would breed
  -- the same in both; the simulation must not.
  local cool_plasma = r.cool.fluidbox[1]
  record(cool_plasma ~= nil and cool_plasma.temperature < 1e8,
    "the cool reactor really is cool",
    cool_plasma and string.format("%.4g C", cool_plasma.temperature) or "no plasma")

  local cool_bred = nearby_holds(r.cool_collector, TRITIUM, BOLTED)
  -- An order of magnitude, not merely "less". Anything that merely tracked temperature loosely
  -- would pass a strict inequality; the cross-section curve is steep enough that this should be a
  -- rout, and it is what says the rate came from the reactivity data rather than from a constant.
  record(cool_bred * 10 < tritium, "a cool reactor breeds far less than a hot one",
    string.format("%.6g vs %.6g units of tritium", cool_bred, tritium))

  -- ------------------------------------------------------------ losing a collector
  record(not r.first_collector.valid, "the spare reactor's first collector really was destroyed")
  local spare_bred = holds(r.second_collector, TRITIUM)
  record(spare_bred > 0,
    "a reactor re-pairs to a second collector when the one it was using is destroyed",
    string.format("%.6g units of tritium in the survivor", spare_bred))

  -- ------------------------------------------------------------ a reactor with no collector
  local bare_plasma = r.bare.fluidbox[1]
  record(bare_plasma ~= nil and bare_plasma.temperature > 1e8,
    "a reactor with no collector runs exactly as well",
    bare_plasma and string.format("%.4g C", bare_plasma.temperature) or "no plasma")
  record(r.bare.fluidbox[2] ~= nil and r.bare.fluidbox[2].amount > 0,
    "and still produces reactor energy",
    r.bare.fluidbox[2] and string.format("%.6g", r.bare.fluidbox[2].amount) or "nothing")

  -- ------------------------------------------------------------ the module seam
  local mix = holds(r.mixer, "rf-d-t-mix")
  local status = "unknown"
  for name, value in pairs(defines.entity_status) do
    if value == r.mixer.status then status = name end
  end
  record(mix > 0, "Core's gas mixer turns a Power reactor's tritium into D-T fuel",
    string.format("%.6g units of rf-d-t-mix, status %s", mix, status))

  lines[#lines + 1] = string.format("%s: %d checks, %d failures",
    failures == 0 and "PASS" or "FAIL", #lines, failures)
  for _, line in ipairs(lines) do log("BREED-RIG " .. line) end
end)
'@
    Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') `
        -Value $lua.Replace('__PLASMAFEED__', $feed).Replace('__TICKS__', "$Ticks")
}

$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }

try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled @() -Mods ($ourMods + $rigName)
    Write-Rig

    $save = Join-Path $temp 'breeding.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', "$($Ticks + 60)", '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'BREED-RIG (ok|FAIL|PASS)' |
        ForEach-Object { ($_ -split 'BREED-RIG ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the rig reported nothing; it never reached its check tick.' }

    foreach ($line in $reported) { Write-Host "  $line" }

    $verdict = $reported | Where-Object { $_ -match '^(PASS|FAIL): ' } | Select-Object -Last 1
    if (-not $verdict)              { throw 'the rig produced no verdict line.' }
    if ($verdict -notmatch '^PASS') { throw "D-D breeding is broken: $verdict" }

    Write-Host ''
    Write-Host 'OK - the reactors breed, the by-products can be stored, and Core mixes them back into fuel.'
}
finally {
    if ($KeepTemp) { Write-Host ''; Write-Host "temp kept at: $temp" }
    Remove-ModJunctions -ModDirectory $modDir
    if (-not $KeepTemp) { Remove-TempDirectory -Path $temp -Label 'check-breeding' }
}
