#Requires -Version 7
<#
.SYNOPSIS
    Checks that plasma cannot enter a vanilla pipe, that the plasma-safe set carries it end to end,
    and that ordinary fluids are untouched. Discharges #26.

.DESCRIPTION
    CONTEXT.md's rule is that plasma must not travel through vanilla pipes. ADR 0010 says the 1.1
    original enforced that in control.lua -- 160 lines whose only job was hunting down
    plasma-carrying vanilla pipes and destroying them -- and that v1 does the same.

    v1 does not do the same, and this is the note explaining why.

    2.0 gives every pipe connection a connection_category, and two connections join only when theirs
    match. The plasma set names a category of its own, so a vanilla pipe laid beside a plasma line
    simply does not connect, the way it already refuses to join a heat pipe. That is better than the
    original's answer on every axis that matters: the plasma never enters rather than being noticed
    after it has, it costs nothing per tick, and nobody's pipe is destroyed under them. There is no
    runtime enforcement in this mod at all, and control.lua is untouched by #26.

    The cost is that "handled deliberately and visibly" becomes "made impossible", and impossible is
    harder to see than a destroyed pipe. The pipe not joining is the feedback, and the item
    descriptions say so in words.

    WHAT IS BUILT

      contained   A plasma line, with a vanilla pipe laid against it. The two must not join and the
                  vanilla pipe must stay empty.
      tunnel      A live plasma pipe-to-ground with a vanilla one facing it five tiles away, which
                  is well inside the range they would bridge if the categories matched. Laying the
                  vanilla one merely NEAR a plasma line would prove nothing -- entities two tiles
                  apart cannot join whatever their categories say, so that assertion would pass
                  with containment removed.
      chain       Feed -> plasma pipe -> plasma pump -> underground plasma pipe -> reactor. Plasma
                  has to arrive, which is one assertion covering the whole set: anything in that run
                  that failed to connect would leave the reactor starved.
      ordinary    A vanilla pipe on the reactor's reactor-energy output, and a vanilla infinity pipe
                  feeding the heater its deuterium. Both are ordinary fluids and both must work
                  exactly as before -- containment is per box, and this is what says so.

.PARAMETER FactorioExe
    Path to Factorio.exe. Defaults to $env:FACTORIO_EXE, then the Steam install on this machine.

.PARAMETER KeepTemp
    Keep the save, the rig mod and the captured output.

.EXAMPLE
    pwsh -File scripts/check-containment.ps1
#>
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/factorio-lib.ps1"

$repoRoot = Split-Path $PSScriptRoot -Parent
$ourMods  = @('RealisticFusionCore', 'RealisticFusion')
$rigName  = 'rf-containment-rig'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-cont-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

function Write-Rig {
    @{
        name = $rigName; version = '0.0.1'; title = 'Plasma containment check'
        author = 'check-containment.ps1'; factorio_version = '2.0'
        dependencies = @('base >= 2.0.77', 'RealisticFusion')
    } | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

    $feed = Write-PlasmaFeed -RigDirectory $rigDir

    $lua = @'
-- Generated by scripts/check-containment.ps1. Nothing here ships.

local PLASMA = "rf-d-d-plasma"
local ENERGY = "rf-reactor-energy"
local FEED   = "__PLASMAFEED__"

local lines = {}
local failures = 0

local function record(ok, name, detail)
  if not ok then failures = failures + 1 end
  lines[#lines + 1] = string.format("%s  %s%s", ok and "ok  " or "FAIL", name,
    detail and ("  -- " .. detail) or "")
end

local function must(entity, what)
  if not entity then error(what .. " refused") end
  return entity
end

local function amount_of(entity, index)
  local contents = entity.fluidbox[index]
  return contents and contents.amount or 0
end

local function box_of(entity, fluid)
  for index = 1, #entity.fluidbox do
    local filter = entity.fluidbox.get_filter(index)
    if filter and filter.name == fluid then return index end
  end
  return nil
end

--- Does any connection on this box reach the given entity?
--
-- An index past the end is answered "no" rather than raised. Callers below ask about box 2 on
-- entities that may only have one -- a pump has a single fluid box holding both its connections --
-- and those reads are guarded by an `or` that short-circuits only while the FIRST term is true. So
-- an unguarded index would raise precisely when containment had regressed, killing the rig instead
-- of letting it print the FAIL line it exists to print.
local function joins(entity, index, other)
  if index > #entity.fluidbox then return false end
  for _, connection in pairs(entity.fluidbox.get_pipe_connections(index)) do
    if connection.target and connection.target.owner == other then return true end
  end
  return false
end

-- `at` is the substation's centre and must be a whole number: a 2x2 entity sits on a tile boundary,
-- where the 1x1 interface beside it sits on a tile centre. create_entity would snap a half-tile
-- position rather than refuse it, which is how the two would silently end up on different grids.
local function power(surface, force, at)
  if at[1] % 1 ~= 0 or at[2] % 1 ~= 0 then
    error(string.format("power() wants a whole-number position, got (%g, %g)", at[1], at[2]))
  end
  must(surface.create_entity({ name = "substation", position = at, force = force }), "substation")
  local eei = must(surface.create_entity({
    name = "electric-energy-interface", position = { at[1] + 2.5, at[2] + 0.5 }, force = force,
  }), "power source")
  eei.power_production = 4e6
end

script.on_init(function()
  local surface = game.surfaces[1]
  local force   = game.forces.player
  force.research_all_technologies()

  surface.request_to_generate_chunks({ 0, 0 }, 6)
  surface.force_generate_chunk_requests()
  local tiles = {}
  for x = -40, 80 do
    for y = -30, 30 do tiles[#tiles + 1] = { name = "landfill", position = { x, y } } end
  end
  surface.set_tiles(tiles)
  for _, e in pairs(surface.find_entities_filtered({ area = { { -40, -30 }, { 80, 30 } } })) do
    if e.type ~= "character" then e.destroy() end
  end

  storage.rig = {}

  -- ------------------------------------------------------------------ the chain
  --
  -- Feed -> underground plasma pipe -> plasma pump -> plasma pipe -> reactor, laid west from the
  -- reactor's own connection. Plasma arriving at the far end is one assertion that covers the whole
  -- set: any component in the run that failed to join would leave the reactor starved.
  local reactor = must(surface.create_entity({
    name = "rf-reactor", position = { 0.5, 0.5 }, force = force, raise_built = true,
  }), "rf-reactor")
  power(surface, force, { 9, 5 })

  local west = reactor.fluidbox.get_pipe_connections(1)[1].target_position
  local pipe_near = must(surface.create_entity({
    name = "rf-pipe", position = { west.x, west.y }, force = force }), "rf-pipe (near)")
  local pipe_far = must(surface.create_entity({
    name = "rf-pipe", position = { west.x - 1, west.y }, force = force }), "rf-pipe (far)")

  -- A 1x2 entity turned east covers two tiles across, so its centre sits on a tile boundary.
  local pump = must(surface.create_entity({
    name = "rf-pump", position = { west.x - 2.5, west.y }, force = force,
    direction = defines.direction.east,
  }), "rf-pump")

  local under_near = must(surface.create_entity({
    name = "rf-pipe-to-ground", position = { west.x - 4, west.y }, force = force,
    direction = defines.direction.east,
  }), "rf-pipe-to-ground (near)")
  local under_far = must(surface.create_entity({
    name = "rf-pipe-to-ground", position = { west.x - 8, west.y }, force = force,
    direction = defines.direction.west,
  }), "rf-pipe-to-ground (far)")

  -- The pump needs its own supply. The reactor is fifteen tiles across and the pump sits ten tiles
  -- beyond its far edge, which is outside the reach of the substation covering the reactor -- and an
  -- unpowered pump moves nothing while every joint in the chain still reports as connected.
  power(surface, force, { math.floor(west.x) - 3, math.floor(west.y) + 6 })

  local feed = must(surface.create_entity({
    name = FEED, position = { west.x - 9, west.y }, force = force,
  }), "plasma feed")
  feed.set_infinity_pipe_filter({ name = PLASMA, percentage = 1, temperature = 6e8, mode = "at-least" })

  -- A vanilla pipe on the reactor's OTHER box, which carries an ordinary fluid and must still work.
  local energy_box = box_of(reactor, ENERGY)
  local energy_at = reactor.fluidbox.get_pipe_connections(energy_box)[1].target_position
  local energy_pipe = must(surface.create_entity({
    name = "pipe", position = { energy_at.x, energy_at.y }, force = force,
  }), "vanilla pipe on the energy output")

  -- ------------------------------------------------------------------ the contained line
  --
  -- A plasma line of its own, with an ordinary pipe laid against its end.
  local island = must(surface.create_entity({
    name = FEED, position = { 40.5, 0.5 }, force = force,
  }), "island feed")
  island.set_infinity_pipe_filter({ name = PLASMA, percentage = 1, temperature = 6e8, mode = "at-least" })
  local plasma_pipe = must(surface.create_entity({
    name = "rf-pipe", position = { 41.5, 0.5 }, force = force,
  }), "island plasma pipe")
  local vanilla_pipe = must(surface.create_entity({
    name = "pipe", position = { 42.5, 0.5 }, force = force,
  }), "vanilla pipe beside the plasma line")
  -- ------------------------------------------------------------------ the tunnel
  --
  -- The underground case needs its own row, and the reason is the whole point of it. An underground
  -- pipe laid *beside* a plasma line is a test of nothing: two entities two tiles apart cannot join
  -- whatever their categories say, so the assertion would pass with containment removed. The claim
  -- worth checking is the one entities.lua actually makes -- that a vanilla pipe-to-ground cannot
  -- tunnel into a plasma line from out of sight -- and that needs the two undergrounds facing each
  -- other across open ground, at a range they would certainly bridge if the categories matched.
  --
  -- direction is the ABOVEGROUND connection's facing, so these point away from each other and their
  -- tunnel ends point in.
  local tunnel_feed = must(surface.create_entity({
    name = FEED, position = { 40.5, 8.5 }, force = force,
  }), "tunnel feed")
  tunnel_feed.set_infinity_pipe_filter({ name = PLASMA, percentage = 1, temperature = 6e8, mode = "at-least" })
  local plasma_underground = must(surface.create_entity({
    name = "rf-pipe-to-ground", position = { 41.5, 8.5 }, force = force,
    direction = defines.direction.west,
  }), "plasma pipe-to-ground on the tunnel row")
  local vanilla_underground = must(surface.create_entity({
    name = "pipe-to-ground", position = { 46.5, 8.5 }, force = force,
    direction = defines.direction.east,
  }), "vanilla pipe-to-ground facing the plasma line")

  -- ------------------------------------------------------------------ the heater
  --
  -- Fed deuterium through an ORDINARY infinity pipe, which is the point: only the plasma side is
  -- contained, so the machine's inputs are plumbed the way any other machine's are.
  local heater = must(surface.create_entity({
    name = "rf-heater", position = { 60.5, 0.5 }, force = force,
  }), "rf-heater")
  local categories = prototypes.entity["rf-heater"].crafting_categories
  for name, recipe in pairs(prototypes.recipe) do
    if categories[recipe.category] then heater.set_recipe(name) break end
  end
  power(surface, force, { 66, 6 })

  local deuterium_box = box_of(heater, "rf-deuterium")
  local deuterium_at = heater.fluidbox.get_pipe_connections(deuterium_box)[1].target_position
  local deuterium_feed = must(surface.create_entity({
    name = "infinity-pipe", position = { deuterium_at.x, deuterium_at.y }, force = force,
  }), "vanilla infinity pipe for deuterium")
  deuterium_feed.set_infinity_pipe_filter({
    name = "rf-deuterium", percentage = 1, mode = "at-least",
  })

  storage.rig = {
    reactor = reactor, pump = pump, feed = feed,
    pipe_near = pipe_near, pipe_far = pipe_far,
    under_near = under_near, under_far = under_far,
    energy_pipe = energy_pipe,
    plasma_pipe = plasma_pipe, vanilla_pipe = vanilla_pipe,
    plasma_underground = plasma_underground, vanilla_underground = vanilla_underground,
    heater = heater, deuterium_feed = deuterium_feed,
  }
  log("CONT-RIG built")
end)

script.on_nth_tick(600, function()
  if game.tick == 0 or storage.done then return end
  storage.done = true
  local r = storage.rig

  -- ------------------------------------------------------------ plasma cannot enter a vanilla pipe
  record(not joins(r.plasma_pipe, 1, r.vanilla_pipe),
    "an ordinary pipe laid against a plasma pipe does not join it")
  record(amount_of(r.vanilla_pipe, 1) == 0,
    "the ordinary pipe beside a live plasma line is still empty",
    string.format("%g", amount_of(r.vanilla_pipe, 1)))

  -- The tunnel row. The first of these is what makes the other two mean anything: an empty vanilla
  -- underground proves containment only if there was plasma on the far side to leak.
  record(amount_of(r.plasma_underground, 1) > 0,
    "the plasma underground pipe is live, so there is something for the tunnel to carry",
    string.format("%g", amount_of(r.plasma_underground, 1)))
  record(not joins(r.plasma_underground, 1, r.vanilla_underground),
    "an ordinary underground pipe cannot tunnel into a plasma line, facing it across open ground")
  record(amount_of(r.vanilla_underground, 1) == 0,
    "and so the ordinary underground pipe is still empty",
    string.format("%g", amount_of(r.vanilla_underground, 1)))

  -- ------------------------------------------------------------ the set carries plasma end to end
  -- Joint by joint, so a break names itself instead of showing up only as a starved reactor at the
  -- far end.
  record(joins(r.reactor, 1, r.pipe_near), "the reactor joins the plasma pipe")
  record(joins(r.pipe_near, 1, r.pipe_far), "plasma pipe joins plasma pipe")
  record(joins(r.pipe_far, 1, r.pump), "the plasma pipe joins the pump")
  record(joins(r.pump, 1, r.under_near) or joins(r.pump, 2, r.under_near),
    "the pump joins the underground plasma pipe")
  record(joins(r.under_near, 1, r.under_far), "the two underground plasma pipes join each other")
  record(joins(r.under_far, 1, r.feed), "the far underground pipe joins the feed")

  local plasma = r.reactor.fluidbox[1]
  record(plasma ~= nil and plasma.amount > 0,
    "plasma reaches the reactor through pipe, pump and underground pipe",
    plasma and string.format("%g units at %.4g C", plasma.amount, plasma.temperature) or "nothing")
  record(plasma ~= nil and plasma.temperature > 1e8,
    "it arrives at the temperature it was fed, so nothing was lost on the way",
    plasma and string.format("%.4g C", plasma.temperature) or "nothing")
  local status = "unknown"
  for name, value in pairs(defines.entity_status) do
    if value == r.pump.status then status = name end
  end
  record(r.pump.status == defines.entity_status.working,
    "the plasma pump is powered and working", status)

  -- ------------------------------------------------------------ ordinary fluids are untouched
  record(joins(r.reactor, 2, r.energy_pipe),
    "an ordinary pipe still joins the reactor's reactor-energy output")
  record(amount_of(r.energy_pipe, 1) > 0,
    "and carries reactor energy",
    string.format("%g", amount_of(r.energy_pipe, 1)))
  record(joins(r.heater, 1, r.deuterium_feed) or joins(r.heater, 2, r.deuterium_feed),
    "an ordinary pipe still feeds the heater its deuterium")

  local produced = 0
  for index = 1, #r.heater.fluidbox do
    local contents = r.heater.fluidbox[index]
    if contents and contents.name == PLASMA then produced = produced + contents.amount end
  end
  record(produced > 0, "and the heater makes plasma from it", string.format("%g", produced))

  lines[#lines + 1] = string.format("%s: %d checks, %d failures",
    failures == 0 and "PASS" or "FAIL", #lines, failures)
  for _, line in ipairs(lines) do log("CONT-RIG " .. line) end
end)
'@
    Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') `
        -Value $lua.Replace('__PLASMAFEED__', $feed)
}

$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }

try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled @() -Mods ($ourMods + $rigName)
    Write-Rig

    $save = Join-Path $temp 'containment.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', '1500', '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'CONT-RIG (ok|FAIL|PASS)' |
        ForEach-Object { ($_ -split 'CONT-RIG ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the rig reported nothing; it never reached its check tick.' }

    foreach ($line in $reported) { Write-Host "  $line" }

    $verdict = $reported | Where-Object { $_ -match '^(PASS|FAIL): ' } | Select-Object -Last 1
    if (-not $verdict)              { throw 'the rig produced no verdict line.' }
    if ($verdict -notmatch '^PASS') { throw "plasma containment is broken: $verdict" }

    Write-Host ''
    Write-Host 'OK - plasma stays in the plasma set, and ordinary fluids are untouched.'
}
finally {
    if ($KeepTemp) { Write-Host ''; Write-Host "temp kept at: $temp" }
    Remove-ModJunctions -ModDirectory $modDir
    if (-not $KeepTemp) { Remove-TempDirectory -Path $temp -Label 'check-containment' }
}
