#Requires -Version 7
<#
.SYNOPSIS
    Checks that a lithium blanket bolted to a running reactor breeds tritium from lithium, that it
    stops when either the lithium or the reactor stops, and that removing it leaves the reactor
    working. Discharges #30.

.DESCRIPTION
    Blanket breeding is the second of the two routes CONTEXT.md names, and the one real D-T
    machines are designed around: the plasma cannot confine its neutrons, so a shell of lithium
    around it catches them and breeds tritium. tests/test-reactor-logic.lua asserts the arithmetic;
    this asserts that the arithmetic reaches a pipe, spends an item, and stops when it should.

    WHY THE TRITIUM COMES OUT OF THE COLLECTOR

    The blanket is a plain container -- lithium is an item, so it needs an inventory and nothing
    else -- and what it breeds leaves through the rf-isotope-collector already bolted to the same
    reactor. prototypes/entities.lua says why: no 2.0.77 prototype is simply "inventory plus fluid
    box", and the two that come close bring machinery that would have to be neutered. The visible
    consequence is that a blanket without a collector is idle, which is the `orphan` cell below.

    THE CONTROL THAT MAKES THIS MEAN ANYTHING

    A D-T reactor breeds NOTHING on its own -- its products table is empty, because the alpha is
    helium-4 and the neutron is already what the mod sells as reactor energy. So every unit of
    tritium the `fitted` cell collects came from the blanket, and the `bare` cell must collect
    exactly zero. That is a far stronger statement than "more with than without", and it is only
    available on this tier.

    WHAT IS BUILT

      fitted     A D-T reactor with a collector and a blanket loaded with lithium. It must breed
                 tritium into the collector, and must spend lithium doing it.
      bare       The same D-T reactor and collector with no blanket at all. It must collect
                 nothing, which is what says the tritium above came from the blanket.
      empty      A blanketed D-T reactor whose blanket was never loaded. Breeds nothing, and the
                 reactor runs exactly as well.
      orphan     A loaded blanket on a reactor with NO collector. Its lithium must be untouched:
                 a blanket with nowhere to put what it breeds stays idle rather than spending
                 items for nothing.
      throttled  A blanketed reactor whose collector is drained far more slowly than the blanket
                 can fill it. Every item spent must be accounted for by a triton still in the
                 collector or drawn out of it -- a blanket must not buy tritium that is being
                 discarded. Drained rather than merely unplumbed, because a saturated box has
                 exactly zero headroom and exercises an early return instead of the cap.
      pulled     A blanketed reactor whose blanket is destroyed halfway through. The reactor has
                 to go on running and go on producing energy.
      d-d        A D-D reactor with a collector and a loaded blanket. It must collect MORE tritium
                 than helium-3 -- the by-product route and the blanket route arriving in the same
                 box -- where an unblanketed D-D reactor collects them in equal measure.

.PARAMETER FactorioExe
    Path to Factorio.exe. Defaults to $env:FACTORIO_EXE, then the Steam install on this machine.

.PARAMETER Ticks
    Ticks to run before checking. The default is long enough for a D-T reactor to have ignited and
    for a blanket to have worked through several lithium items.

.PARAMETER KeepTemp
    Keep the save, the rig mod and the captured output.

.EXAMPLE
    pwsh -File scripts/check-blanket.ps1
#>
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [ValidateRange(600, 200000)] [int] $Ticks = 7200,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/factorio-lib.ps1"

$repoRoot = Split-Path $PSScriptRoot -Parent
$ourMods  = Get-RepoMods
$rigName  = 'rf-blanket-rig'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-blanket-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

function Write-Rig {
    @{
        name = $rigName; version = '0.0.1'; title = 'Lithium blanket check'
        author = 'check-blanket.ps1'; factorio_version = '2.0'
        dependencies = @('base >= 2.0.77', 'realistic-fusion-refreshed', 'realistic-fusion-refreshed-core')
    } | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

    $feed = Write-PlasmaFeed -RigDirectory $rigDir

    $lua = @'
-- Generated by scripts/check-blanket.ps1. Nothing here ships.

local CHECK_AT = __TICKS__

local DT       = "rf-d-t-plasma"
local DD       = "rf-d-d-plasma"
local TRITIUM  = "rf-tritium"
local HELIUM3  = "rf-helium-3"
local LITHIUM  = "rf-lithium"
local BLANKET  = "rf-lithium-blanket"
local FEED     = "__PLASMAFEED__"

-- How much lithium each loaded blanket starts with.
--
-- Comfortably MORE than the run can consume, and that is the point rather than generosity. An
-- ignited D-T reactor feeds its blanket about 19 units a second, so 500 ran dry inside the first
-- half minute -- which made every check below pass on a blanket that had stopped, and made the
-- item-per-unit identity a tautology about the 500 items it had rather than a measurement of the
-- rate. The first version of this rig did exactly that and hid a real throughput ceiling in
-- control.lua behind it.
local LOADED = 5000

-- How far around a collector to look for what its reactor bred. Wide enough for its pipe run and
-- tank, and well short of the next cell.
local NEARBY = 25

local lines = {}
local failures = 0

local function record(ok, name, detail)
  if not ok then failures = failures + 1 end
  lines[#lines + 1] = string.format("%s  %s%s", ok and "ok  " or "FAIL", name,
    detail and ("  -- " .. detail) or "")
end

local function must(entity, what)
  if not entity then error(what .. " refused") end
  return entity
end

local function holds(entity, fluid)
  local total = 0
  for index = 1, #entity.fluidbox do
    local contents = entity.fluidbox[index]
    if contents and contents.name == fluid then total = total + contents.amount end
  end
  return total
end

--- Everything within `radius` of an entity that is holding one fluid.
--
-- The collector drains into its pipe run as fast as control.lua fills it, so its own box reports a
-- fraction of the total. Same helper and same reason as check-breeding.ps1.
local function nearby_holds(entity, fluid, radius)
  local at = entity.position
  local total = 0
  for _, found in pairs(entity.surface.find_entities_filtered({
    area = { { at.x - radius, at.y - radius }, { at.x + radius, at.y + radius } },
  })) do
    total = total + holds(found, fluid)
  end
  return total
end

local function lithium_in(blanket)
  if not (blanket and blanket.valid) then return 0 end
  return blanket.get_inventory(defines.inventory.chest).get_item_count(LITHIUM)
end

local function power(surface, force, at)
  must(surface.create_entity({ name = "substation", position = at, force = force }), "substation")
  local eei = must(surface.create_entity({
    name = "electric-energy-interface", position = { at[1] + 2.5, at[2] + 0.5 }, force = force,
  }), "power source")
  eei.power_production = 4e6
end

local function pipe_run(surface, force, from, step, count)
  for i = 0, count - 1 do
    local at = { from[1] + step[1] * i, from[2] + step[2] * i }
    if not surface.find_entity("pipe", at) then
      must(surface.create_entity({ name = "pipe", position = at, force = force }),
        string.format("pipe at (%g, %g)", at[1], at[2]))
    end
  end
end

--- A reactor on a plasma feed, at `ox`. Geometry read off the prototypes rather than written down.
local function reactor_at(surface, force, ox, plasma, temperature)
  local reactor = must(surface.create_entity({
    name = "rf-reactor", position = { ox, 0.5 }, force = force, raise_built = true,
  }), "rf-reactor")
  local west = reactor.fluidbox.get_pipe_connections(1)[1].target_position
  local feed = must(surface.create_entity({
    name = FEED, position = { west.x, west.y }, force = force,
  }), "plasma feed")
  feed.set_infinity_pipe_filter({
    name = plasma, percentage = 1, temperature = temperature, mode = "at-least",
  })
  return reactor
end

--- A collector flush against a reactor's south face, with its tritium outlet piped to a tank.
--
-- Flush is computed from both selection boxes rather than written down, so the collector lands
-- inside the one-tile margin entity-management's attach() searches whatever either size becomes.
local function collector_on(surface, force, reactor, tank_seed)
  local rbox = prototypes.entity["rf-reactor"].selection_box
  local cbox = prototypes.entity["rf-isotope-collector"].selection_box
  local collector = must(surface.create_entity({
    name = "rf-isotope-collector",
    position = {
      reactor.position.x,
      reactor.position.y + rbox.right_bottom.y + (cbox.right_bottom.y - cbox.left_top.y) / 2,
    },
    force = force, direction = defines.direction.south, raise_built = true,
  }), "rf-isotope-collector")

  -- Only the tritium box is plumbed. Helium-3 is left to accumulate in the collector, which is
  -- where the d-d cell reads it from.
  local index
  for i = 1, #collector.fluidbox do
    local filter = collector.fluidbox.get_filter(i)
    if filter and filter.name == TRITIUM then index = i end
  end
  if not index then error("the collector has no box filtered to " .. TRITIUM) end

  -- No tank seed means no plumbing at all, which is the `blocked` cell: the tritium box fills to
  -- its capacity and stays there, and the blanket has to notice.
  if not tank_seed then return collector, nil, index end

  local at = collector.fluidbox.get_pipe_connections(index)[1].target_position
  local step = { at.x - collector.position.x, at.y - collector.position.y }
  local length = math.max(math.abs(step[1]), math.abs(step[2]))
  step = { step[1] / length, step[2] / length }
  pipe_run(surface, force, { at.x, at.y }, step, 3)

  -- The tank is placed by probing where its own connection lands, the way check-breeding does: a
  -- storage tank carries four connections at fixed offsets rather than one per edge tile.
  local probe = must(surface.create_entity({
    name = "storage-tank", position = tank_seed, force = force }), "storage tank probe")
  local pat = probe.fluidbox.get_pipe_connections(1)[1].target_position
  local target = { at.x + step[1] * 2, at.y + step[2] * 2 }
  probe.destroy()
  local tank = must(surface.create_entity({
    name = "storage-tank",
    position = { tank_seed[1] + (target[1] - pat.x), tank_seed[2] + (target[2] - pat.y) },
    force = force,
  }), "storage tank")
  return collector, tank, index
end

--- A blanket bolted to a reactor's north face, optionally loaded with lithium.
--
-- North because the collector has the south face. The reactor's energy outlet is there and nothing
-- is plumbed to it in this rig, so the tile is free.
--
-- raise_built, and built after the reactor on purpose: a player bolts the fitting on afterwards,
-- and it is the build event that pairs them. Placing it silently would exercise a path no player
-- can take and miss the one they do.
local function blanket_on(surface, force, reactor, lithium)
  local rbox = prototypes.entity["rf-reactor"].selection_box
  local bbox = prototypes.entity[BLANKET].selection_box
  local blanket = must(surface.create_entity({
    name = BLANKET,
    position = {
      reactor.position.x,
      reactor.position.y + rbox.left_top.y - (bbox.right_bottom.y - bbox.left_top.y) / 2,
    },
    force = force, raise_built = true,
  }), BLANKET)
  if lithium > 0 then
    blanket.get_inventory(defines.inventory.chest).insert({ name = LITHIUM, count = lithium })
  end
  return blanket
end

script.on_init(function()
  local surface = game.surfaces[1]
  local force   = game.forces.player

  -- Read BEFORE research_all_technologies, and recorded into storage rather than into an upvalue:
  -- on_init runs under --create and the benchmark then LOADS the save, so anything measured here
  -- and kept in a local is gone by the time the check tick arrives.
  local gate = {
    blanket_locked = not force.recipes[BLANKET].enabled,
    technology = force.technologies["rf-blanket-breeding"] ~= nil,
  }

  -- PREREQUISITE CLOSURE, checked before anything else is researched.
  --
  -- The rule technology/d-d.lua states: every ingredient of a recipe a technology unlocks has to
  -- be reachable inside that technology's own prerequisites, or a player researches a tier and
  -- cannot build it. Nothing enforced it, and #30's first draft broke it -- the recipe called for
  -- processing units, and nothing on the chain from rf-d-t-fusion, rf-tritium-breeding or
  -- rf-lithium-extraction reaches vanilla's processing-unit technology.
  --
  -- Invisible to every other rig here, because they all call research_all_technologies() and then
  -- ask whether the machine works. It does. The player just cannot get to it.
  local function research_closure(name, seen)
    if seen[name] then return end
    seen[name] = true
    local tech = force.technologies[name]
    if not tech then return end
    for prerequisite in pairs(tech.prerequisites) do research_closure(prerequisite, seen) end
    tech.researched = true
  end
  research_closure("rf-blanket-breeding", {})

  -- Every ingredient whose recipe shares its name, which is all of them here and is how vanilla
  -- names intermediate recipes. An ingredient with no same-named recipe is not checked rather than
  -- silently passed -- the count below is what says whether anything was actually looked at.
  gate.ingredients = {}
  for _, ingredient in pairs(prototypes.recipe[BLANKET].ingredients) do
    local recipe = force.recipes[ingredient.name]
    if recipe then
      gate.ingredients[#gate.ingredients + 1] = { name = ingredient.name, enabled = recipe.enabled }
    end
  end
  gate.blanket_unlocked = force.recipes[BLANKET].enabled

  force.research_all_technologies()

  surface.request_to_generate_chunks({ 0, 0 }, 10)
  surface.force_generate_chunk_requests()
  local tiles = {}
  for x = -260, 200 do
    for y = -40, 40 do tiles[#tiles + 1] = { name = "landfill", position = { x, y } } end
  end
  surface.set_tiles(tiles)
  for _, e in pairs(surface.find_entities_filtered({ area = { { -260, -40 }, { 200, 40 } } })) do
    if e.type ~= "character" then e.destroy() end
  end

  -- ------------------------------------------------------------------ fitted
  local fitted = reactor_at(surface, force, 0.5, DT, 1e6)
  power(surface, force, { 12, 8 })
  local fitted_collector, fitted_tank = collector_on(surface, force, fitted, { 30.5, 25.5 })
  local fitted_blanket = blanket_on(surface, force, fitted, LOADED)

  -- ------------------------------------------------------------------ bare
  --
  -- The control. Same reactor, same collector, no blanket. A D-T reactor breeds nothing of its
  -- own, so this must collect exactly zero tritium.
  local bare = reactor_at(surface, force, -60.5, DT, 1e6)
  power(surface, force, { -48, 8 })
  local bare_collector, bare_tank = collector_on(surface, force, bare, { -30.5, 25.5 })

  -- ------------------------------------------------------------------ empty
  local empty = reactor_at(surface, force, -120.5, DT, 1e6)
  power(surface, force, { -108, 8 })
  local empty_collector = collector_on(surface, force, empty, { -90.5, 25.5 })
  local empty_blanket = blanket_on(surface, force, empty, 0)

  -- ------------------------------------------------------------------ orphan
  --
  -- A loaded blanket with no collector to breed into. It must not spend a single lithium.
  local orphan = reactor_at(surface, force, -180.5, DT, 1e6)
  power(surface, force, { -168, 8 })
  local orphan_blanket = blanket_on(surface, force, orphan, LOADED)

  -- ------------------------------------------------------------------ throttled
  --
  -- A collector being drained far more slowly than the blanket can fill it, which is the case a
  -- player actually meets: one pipe to a consumer that cannot keep up. The blanket must pay only
  -- for tritium that has somewhere to go.
  --
  -- Drained rather than simply left unplumbed, and that distinction is the whole cell. An
  -- unplumbed collector saturates at exactly zero headroom, where blanket_breed returns early --
  -- so it exercises the early return and NOT the cap, and passes with the cap deleted. Found by
  -- deleting it. Throttling leaves a small positive headroom on every step, which is the only
  -- state the cap is responsible for, and the state a real factory sits in.
  --
  -- Argued the other way first -- overflow is discarded everywhere in this mod -- until it was
  -- pointed out that everything else that backs up costs nothing, where this costs an item a
  -- player mined and belted here, at about nineteen a second.
  local throttled = reactor_at(surface, force, 180.5, DT, 1e6)
  power(surface, force, { 192, 8 })
  local throttled_collector, _, throttled_box = collector_on(surface, force, throttled, nil)
  local throttled_blanket = blanket_on(surface, force, throttled, LOADED)

  -- ------------------------------------------------------------------ pulled
  local pulled = reactor_at(surface, force, -240.5, DT, 1e6)
  power(surface, force, { -228, 8 })
  local pulled_collector = collector_on(surface, force, pulled, { -210.5, 25.5 })
  local pulled_blanket = blanket_on(surface, force, pulled, LOADED)

  -- ------------------------------------------------------------------ d-d, blanketed and not
  --
  -- Both routes in one box. A D-D reactor breeds tritium and helium-3 in equal measure; add a
  -- blanket and the tritium pulls ahead, because blanket tritium is deposited through the same
  -- collector. The unblanketed one beside it is what says the inequality is the blanket's doing.
  local dd = reactor_at(surface, force, 60.5, DD, 6e8)
  power(surface, force, { 72, 8 })
  local dd_collector = collector_on(surface, force, dd, { 90.5, 25.5 })
  local dd_blanket = blanket_on(surface, force, dd, LOADED)

  local dd_bare = reactor_at(surface, force, 120.5, DD, 6e8)
  power(surface, force, { 132, 8 })
  local dd_bare_collector = collector_on(surface, force, dd_bare, { 150.5, 25.5 })

  storage.gate = gate
  storage.rig = {
    fitted = fitted, fitted_collector = fitted_collector, fitted_tank = fitted_tank,
    fitted_blanket = fitted_blanket,
    bare = bare, bare_collector = bare_collector, bare_tank = bare_tank,
    empty = empty, empty_collector = empty_collector, empty_blanket = empty_blanket,
    orphan = orphan, orphan_blanket = orphan_blanket,
    throttled = throttled, throttled_collector = throttled_collector,
    throttled_box = throttled_box, throttled_blanket = throttled_blanket,
    pulled = pulled, pulled_collector = pulled_collector, pulled_blanket = pulled_blanket,
    dd = dd, dd_collector = dd_collector, dd_blanket = dd_blanket,
    dd_bare = dd_bare, dd_bare_collector = dd_bare_collector,
  }
  log("BLANKET-RIG built")
end)

-- The throttled cell's slow consumer, and the running total of what it took. Well under what the
-- blanket could produce, so the box stays near full and headroom stays small and positive -- which
-- is the only state control.lua's headroom cap is responsible for.
script.on_event(defines.events.on_tick, function()
  local collector = storage.rig and storage.rig.throttled_collector
  if not (collector and collector.valid) then return end
  storage.drained = (storage.drained or 0)
    + collector.remove_fluid({ name = TRITIUM, amount = 0.05 })
end)

-- Halfway through, destroy the blanket the `pulled` reactor is using. Nothing raises an event for
-- this, which is the point: the reactor has to carry on regardless.
script.on_nth_tick(math.floor(CHECK_AT / 2), function()
  if game.tick == 0 or storage.pulled then return end
  storage.pulled = true
  storage.rig.pulled_blanket.destroy()
end)

script.on_nth_tick(CHECK_AT, function()
  if game.tick == 0 or storage.done then return end
  storage.done = true
  local r = storage.rig

  -- ------------------------------------------------------------ the technology gate
  record(storage.gate.technology, "rf-blanket-breeding exists as a technology")
  record(storage.gate.blanket_locked,
    "the blanket is not buildable before it is researched")
  record(storage.gate.blanket_unlocked,
    "and is buildable once it and its prerequisites are")

  -- ------------------------------------------------------------ can it actually be built?
  local checked, missing = 0, {}
  for _, ingredient in pairs(storage.gate.ingredients) do
    checked = checked + 1
    if not ingredient.enabled then missing[#missing + 1] = ingredient.name end
  end
  record(checked > 0, "the blanket recipe's ingredients were checked at all",
    string.format("%d of them", checked))
  record(#missing == 0,
    "every ingredient is craftable inside rf-blanket-breeding's own prerequisites",
    #missing == 0 and string.format("%d checked", checked)
      or ("unreachable: " .. table.concat(missing, ", ")))

  -- ------------------------------------------------------------ it breeds
  local plasma = r.fitted.fluidbox[1]
  record(plasma ~= nil and plasma.name == DT and plasma.temperature > 1e8,
    "the fitted reactor is burning D-T",
    plasma and string.format("%s at %.4g C", plasma.name, plasma.temperature) or "no plasma")

  local bred = nearby_holds(r.fitted_collector, TRITIUM, NEARBY)
  record(bred > 0, "a blanket on a running D-T reactor breeds tritium", string.format("%.6g", bred))
  record(holds(r.fitted_tank, TRITIUM) > 0, "and it reaches an ordinary storage tank",
    string.format("%.6g", holds(r.fitted_tank, TRITIUM)))

  -- ------------------------------------------------------------ and pays for it
  local left = lithium_in(r.fitted_blanket)
  record(left < LOADED and left > 0, "the blanket spent lithium doing it, and did not run dry",
    string.format("%d of %d left", left, LOADED))

  -- One lithium item per unit of tritium is the identity M.blanket is built around, and it is
  -- checkable from outside because both numbers are visible here. Loose, because what the
  -- collector holds is what has been produced minus nothing -- but the blanket is also part way
  -- through the item it is currently burning, and the run ends mid-item.
  local spent = LOADED - left
  record(math.abs(bred - spent) <= 1 + 0.02 * spent,
    "one lithium item bred about one unit of tritium",
    string.format("%.6g units of tritium for %d items", bred, spent))

  -- ------------------------------------------------------------ the control
  --
  -- The claim the whole cell rests on: a D-T reactor breeds NOTHING without a blanket, so every
  -- unit above came from the blanket rather than from the reaction.
  local bare_plasma = r.bare.fluidbox[1]
  record(bare_plasma ~= nil and bare_plasma.temperature > 1e8,
    "the bare reactor is burning D-T just as hard",
    bare_plasma and string.format("%.4g C", bare_plasma.temperature) or "no plasma")
  record(nearby_holds(r.bare_collector, TRITIUM, NEARBY) == 0,
    "the same reactor with no blanket breeds no tritium at all",
    string.format("%.6g", nearby_holds(r.bare_collector, TRITIUM, NEARBY)))

  -- ------------------------------------------------------------ an empty blanket
  record(nearby_holds(r.empty_collector, TRITIUM, NEARBY) == 0,
    "a blanket that was never loaded breeds nothing")
  local empty_plasma = r.empty.fluidbox[1]
  record(empty_plasma ~= nil and empty_plasma.temperature > 1e8,
    "and its reactor runs exactly as well",
    empty_plasma and string.format("%.4g C", empty_plasma.temperature) or "no plasma")

  -- ------------------------------------------------------------ nowhere to put it
  record(lithium_in(r.orphan_blanket) == LOADED,
    "a blanket with no collector spends no lithium",
    string.format("%d of %d left", lithium_in(r.orphan_blanket), LOADED))

  -- ------------------------------------------------------------ more than the pipe can take
  --
  -- The case a player actually meets: a consumer that cannot keep up. Stated as conservation
  -- rather than as a bound anyone chose -- every lithium item the blanket spent has to be
  -- accounted for by a triton that is either still in the collector or has been drawn out of it.
  -- Anything above that was bought and thrown away.
  --
  -- Plus one, because the blanket may be part way through an item when the run ends.
  --
  -- What the bound is sized against: with control.lua's headroom cap deleted this cell spends
  -- about 2 100 items for the same few hundred units of tritium. It is not a tolerance.
  local throttled_held = holds(r.throttled_collector, TRITIUM)
  local drained = storage.drained or 0
  local capacity = r.throttled_collector.fluidbox.get_capacity(r.throttled_box)

  record(drained > 0 and throttled_held > 0.5 * capacity,
    "the throttled collector really is backed up and really is being drained",
    string.format("%.6g held of %.6g, %.6g drawn off", throttled_held, capacity, drained))

  local throttled_spent = LOADED - lithium_in(r.throttled_blanket)
  record(throttled_spent <= throttled_held + drained + 1,
    "a blanket buys no more tritium than its collector can take",
    string.format("%d items spent against %.6g held plus %.6g drained",
      throttled_spent, throttled_held, drained))

  -- ------------------------------------------------------------ losing the blanket
  record(not r.pulled_blanket.valid, "the pulled reactor's blanket really was destroyed")
  local pulled_plasma = r.pulled.fluidbox[1]
  record(pulled_plasma ~= nil and pulled_plasma.temperature > 1e8,
    "a reactor whose blanket is removed goes on running",
    pulled_plasma and string.format("%.4g C", pulled_plasma.temperature) or "no plasma")
  record(r.pulled.fluidbox[2] ~= nil and r.pulled.fluidbox[2].amount > 0,
    "and goes on producing reactor energy",
    r.pulled.fluidbox[2] and string.format("%.6g", r.pulled.fluidbox[2].amount) or "nothing")

  -- ------------------------------------------------------------ both routes in one box
  local dd_t = nearby_holds(r.dd_collector, TRITIUM, NEARBY)
  local dd_h = holds(r.dd_collector, HELIUM3)
  record(dd_t > dd_h, "a blanketed D-D reactor collects more tritium than helium-3",
    string.format("%.6g vs %.6g", dd_t, dd_h))

  local plain_t = nearby_holds(r.dd_bare_collector, TRITIUM, NEARBY)
  local plain_h = holds(r.dd_bare_collector, HELIUM3)
  record(math.abs(plain_t - plain_h) <= 1e-6 * math.max(plain_t, plain_h, 1),
    "where an unblanketed one collects them in equal measure",
    string.format("%.6g vs %.6g", plain_t, plain_h))
  record(dd_t > plain_t, "so the blanket is what put the extra tritium there",
    string.format("%.6g blanketed vs %.6g bare", dd_t, plain_t))

  -- The breeding ratio, measured end to end rather than asserted in Lua.
  --
  -- It is checkable here and nowhere else, and only on this tier, because of a coincidence worth
  -- stating: D-D releases one neutron on half its reactions and one helium-3 on the same half, so
  -- the helium-3 in that collector IS the neutron count in the same units. Blanket tritium over
  -- helium-3 is therefore exactly tritium_per_neutron.
  --
  -- 1.1 is written out here rather than read from reactor-logic, and that is deliberate: a check
  -- that fetches the constant it is checking passes whatever the constant becomes. Editing
  -- M.blanket.tritium_per_neutron is meant to fail this rig and make someone say so out loud.
  --
  -- Two per cent, because the blanket is part way through a charge when the run ends. Wider than
  -- that and it would have passed the one-item-per-step ceiling this rig was written to catch.
  -- The denominator has to be a count rather than a full box, and that is not a formality. The
  -- collector's helium-3 box is deliberately left unplumbed here, deposit() clamps to its capacity
  -- and discards the rest, and at this rate it fills somewhere around 43 000 ticks -- well inside
  -- what -Ticks accepts. Anyone raising it to give the reactors longer would otherwise get a
  -- saturated denominator, a ratio far above 1.1, and a failure pointing at the blanket instead of
  -- at the rig. Capacity is read off the prototype rather than written down.
  local capacity = 0
  for i = 1, #r.dd_collector.fluidbox do
    local filter = r.dd_collector.fluidbox.get_filter(i)
    if filter and filter.name == HELIUM3 then capacity = r.dd_collector.fluidbox.get_capacity(i) end
  end
  record(dd_h < capacity,
    "the helium-3 the ratio is measured against has not saturated its box",
    string.format("%.6g of %.6g -- raise the box or lower -Ticks, not the blanket", dd_h, capacity))

  local dd_blanket_bred = dd_t - dd_h
  local ratio = dd_blanket_bred / dd_h
  record(math.abs(ratio - 1.1) <= 0.02,
    "the blanket breeds 1.1 tritons per neutron in game, as the model says",
    string.format("%.4f  (%.6g bred against %.6g neutrons)", ratio, dd_blanket_bred, dd_h))

  -- ------------------------------------------------------------ is it worth building?
  --
  -- The acceptance criterion in words: blanket output has to be meaningful against the by-product
  -- route, or the tier is a longer walk to the same place. Compared against a D-D reactor's own
  -- by-product yield over the same run, because that is what a player would otherwise be building
  -- more of.
  --
  -- An order of magnitude, not merely "more". The gap is structural rather than tuned -- a D-T
  -- reactor at this feed makes far more reactions than a D-D one and a neutron on every one of
  -- them, where D-D makes a triton on half -- so anything close to parity means the blanket is
  -- being throttled by something rather than breeding at the rate the plasma supports.
  record(bred > 10 * plain_t,
    "a blanketed D-T reactor out-breeds a D-D reactor's by-products by an order of magnitude",
    string.format("%.6g against %.6g units over the same run", bred, plain_t))

  lines[#lines + 1] = string.format("%s: %d checks, %d failures",
    failures == 0 and "PASS" or "FAIL", #lines, failures)
  for _, line in ipairs(lines) do log("BLANKET-RIG " .. line) end
end)
'@
    Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') `
        -Value $lua.Replace('__PLASMAFEED__', $feed).Replace('__TICKS__', "$Ticks")
}

$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }

try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled @() -Mods ($ourMods + $rigName)
    Write-Rig

    $save = Join-Path $temp 'blanket.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', "$($Ticks + 60)", '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'BLANKET-RIG (ok|FAIL|PASS)' |
        ForEach-Object { ($_ -split 'BLANKET-RIG ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the rig reported nothing; it never reached its check tick.' }

    foreach ($line in $reported) { Write-Host "  $line" }

    $verdict = $reported | Where-Object { $_ -match '^(PASS|FAIL): ' } | Select-Object -Last 1
    if (-not $verdict)              { throw 'the rig produced no verdict line.' }
    if ($verdict -notmatch '^PASS') { throw "blanket breeding is broken: $verdict" }

    Write-Host ''
    Write-Host 'OK - a lithium blanket breeds tritium from a running reactor, buys none its collector'
    Write-Host '     cannot take, and taking it off leaves the reactor working.'
}
finally {
    if ($KeepTemp) { Write-Host ''; Write-Host "temp kept at: $temp" }
    Remove-ModJunctions -ModDirectory $modDir
    if (-not $KeepTemp) { Remove-TempDirectory -Path $temp -Label 'check-blanket' }
}
