#Requires -Version 7
<#
.SYNOPSIS
    Checks that a reactor actually reports itself -- status line, both signals, on a real wire.
    Discharges the half of #25 that unit tests cannot reach.

.DESCRIPTION
    tests/test-circuit-output.lua covers everything above publish(): what the two signal values
    should be, which of the three states a result means, that every status key is in the locale
    file. It is pure arithmetic and it runs outside Factorio, which is the whole reason
    circuit-output.lua is split where it is.

    Below publish() none of that is true, and none of it was checked. A reactor is a boiler, and
    BoilerPrototype carries no circuit connector at all, so the signals go out through a companion
    constant combinator created at the reactor's own position. Every part of that arrangement can
    fail without anything erroring: the combinator can go missing, its section can be empty, the
    values can be stale, the wire can be out of reach, or -- the one that actually happened -- the
    whole thing can work while being impossible to attach a wire to, because the reactor wins the
    cursor over the entity that carries the connector (ADR 0012).

    So this builds three reactors in the three states the ticket names, wires each one's combinator
    to a second combinator ten tiles away, and reads the values back off the far end of that wire.
    Reading at the far end is the point: it is the difference between "the mod set some filters"
    and "a player can act on this".

    WHAT EACH REACTOR IS FOR

      running   Plasma pinned hot by an infinity pipe, and powered. Should fuse.
      idle      Plasma pinned at the temperature a heater injects at, and deliberately on no
                electric network, so it cannot climb. Holding plasma, not fusing.
      starved   No plasma line at all.

    Three states, three reactors, one save -- which is also what makes the aggregate check possible:
    running and idle sit at temperatures three orders of magnitude apart, so if either one's wire
    carried a figure for "the reactors" rather than for itself, they could not both be right.

    WHAT IT CANNOT CHECK

    That a wire drag lands on the combinator rather than on the reactor. That is a property of
    Factorio's mouse selection, it needs a LuaPlayer, and a headless run has none -- so it was
    measured in a client instead (ADR 0012 records both the wrong first answer and the measurement).
    Everything downstream of the wire existing is checked here.

.PARAMETER FactorioExe
    Path to Factorio.exe. Defaults to $env:FACTORIO_EXE, then the Steam install on this machine.

.PARAMETER KeepTemp
    Keep the save, the rig mod and the captured output.

.EXAMPLE
    pwsh -File scripts/check-observability.ps1
#>
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/factorio-lib.ps1"

$repoRoot = Split-Path $PSScriptRoot -Parent
$ourMods  = @('realistic-fusion-refreshed-core', 'realistic-fusion-refreshed')
$rigName  = 'rf-observability-rig'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-obs-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

function Write-Rig {
    @{
        name = $rigName; version = '0.0.1'; title = 'Reactor observability check'
        author = 'check-observability.ps1'; factorio_version = '2.0'
        dependencies = @('base >= 2.0.77', 'realistic-fusion-refreshed')
    } | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

    # The shipped plasma set carries its own pipe connection category (#26), so a vanilla
    # infinity-pipe can no longer feed a reactor. The rig declares one that can.
    $feed = Write-PlasmaFeed -RigDirectory $rigDir

    $lua = @'
-- Generated by scripts/check-observability.ps1. Nothing here ships.

local COMBINATOR = "rf-reactor-signals"
local TEMPERATURE = { type = "virtual", name = "rf-signal-plasma-temperature", quality = "normal" }
local Q_FACTOR    = { type = "virtual", name = "rf-signal-q-factor", quality = "normal" }
local RED = defines.wire_connector_id.circuit_red

-- Three reactors, twenty-five tiles apart so a fifteen-tile building and its wiring never touch the
-- next one. powered = false is how the idle case is held idle: with no network the reactor cannot
-- heat, so plasma injected at a heater's temperature stays there.
local CASES = {
  { name = "running", plasma = 6e8, powered = true  },
  { name = "idle",    plasma = 1e6, powered = false },
  { name = "starved", plasma = nil, powered = true  },
}

local lines = {}
local failures = 0

local function record(ok, name, detail)
  if not ok then failures = failures + 1 end
  lines[#lines + 1] = string.format("%s  %s%s", ok and "ok  " or "FAIL", name,
    detail and ("  -- " .. detail) or "")
end

script.on_init(function()
  local surface = game.surfaces[1]
  local force   = game.forces.player

  surface.request_to_generate_chunks({ 40, 0 }, 5)
  surface.force_generate_chunk_requests()
  local tiles = {}
  for x = -20, 110 do
    for y = -20, 20 do tiles[#tiles + 1] = { name = "landfill", position = { x, y } } end
  end
  surface.set_tiles(tiles)
  for _, e in pairs(surface.find_entities_filtered({ area = { { -20, -20 }, { 110, 20 } } })) do
    if e.type ~= "character" then e.destroy() end
  end

  storage.cases = {}
  for index, case in ipairs(CASES) do
    local ox = (index - 1) * 25
    local reactor = surface.create_entity({
      name = "rf-reactor", position = { ox + 0.5, 0.5 }, force = force, raise_built = true,
    })
    if not reactor then error("rf-reactor refused for " .. case.name) end

    if case.powered then
      local sub = surface.create_entity({ name = "substation", position = { ox + 9, 5 }, force = force })
      if not sub then error("substation refused for " .. case.name) end
      local eei = surface.create_entity({
        name = "electric-energy-interface", position = { ox + 11.5, 5.5 }, force = force,
      })
      if not eei then error("power source refused for " .. case.name) end
      eei.power_production = 2e6
    end

    if case.plasma then
      -- Placed where the reactor says its plasma connection points, not where arithmetic on the
      -- footprint says it should. The arithmetic is a remembered constant by another name, and it
      -- is what left the reactor benchmark quietly feeding empty ground after the 15x15 resize
      -- (#49).
      local connections = reactor.fluidbox.get_pipe_connections(1)
      if #connections == 0 then error("rf-reactor's plasma box has no connections") end
      local feed = surface.create_entity({
        name = "__PLASMAFEED__", position = connections[1].target_position, force = force,
      })
      if not feed then error("infinity-pipe refused for " .. case.name) end
      feed.set_infinity_pipe_filter({
        name = "rf-d-d-plasma", percentage = 1, temperature = case.plasma, mode = "at-least",
      })
      -- A feed that lines up with nothing looks exactly like a reactor that is meant to be starved.
      local joined = false
      for _, connection in pairs(reactor.fluidbox.get_pipe_connections(1)) do
        if connection.target then joined = true end
      end
      if not joined then error("the plasma feed for " .. case.name .. " reaches nothing") end
    end

    -- The far end of the wire: an ordinary constant combinator a player could have placed, ten
    -- tiles clear of the reactor's own edge.
    local probe = surface.create_entity({
      name = "constant-combinator", position = { ox + 10.5, 0.5 }, force = force,
    })
    if not probe then error("probe combinator refused for " .. case.name) end

    storage.cases[#storage.cases + 1] = { case = case, reactor = reactor, probe = probe, ox = ox }
  end

  log("OBS-RIG built")
end)

-- control.lua reports every REPORT_EVERY simulation steps, so the first wire values exist within a
-- couple of dozen ticks. Everything below runs once, well after that.
-- Wiring and reading are two passes a full tick apart, and that is not caution.
-- LuaCircuitNetwork reports the signals of the *previous* tick, so a wire connected and read in the
-- same handler carries nothing -- which is indistinguishable from a mod that never published.
local function wire_everything()
  local surface = game.surfaces[1]
  for _, entry in ipairs(storage.cases) do
    local name = entry.case.name
    local found = surface.find_entities_filtered({
      name = COMBINATOR, position = entry.reactor.position,
    })
    record(#found == 1, name .. ": exactly one signals combinator at the reactor",
      string.format("%d", #found))
    local combinator = found[1]
    if combinator then
      record(storage.seen_combinators[tostring(combinator.unit_number)] == nil,
        name .. ": the combinator is this reactor's own, not one shared between reactors")
      storage.seen_combinators[tostring(combinator.unit_number)] = true

      -- A wire a player could have dragged: reach checked rather than forced.
      local from = combinator.get_wire_connector(RED, true)
      local to   = entry.probe.get_wire_connector(RED, true)
      record(from ~= nil and to ~= nil, name .. ": both ends offer a red circuit connector")
      if from and to then
        record(from.connect_to(to), name .. ": the wire reaches the probe ten tiles away")
      end

      -- What the reactor publishes, asked of the combinator rather than of the network. The two
      -- are not the same question: Factorio leaves a zero-valued signal off the network entirely,
      -- so a starved reactor -- whose temperature and Q are both legitimately 0 -- puts nothing on
      -- the wire at all. Whether it *published* both is still answerable, and is the thing that
      -- would break if a signal were dropped.
      local behavior = combinator.get_control_behavior()
      local section = behavior and behavior.sections_count > 0 and behavior.get_section(1)
      local declared = {}
      for _, filter in pairs(section and section.filters or {}) do
        if filter.value then declared[filter.value.name] = true end
      end
      record(declared[TEMPERATURE.name] and declared[Q_FACTOR.name] or false,
        name .. ": the reactor publishes both signals, whatever their values")
    end
  end
end

local function verify()
  local seen_labels = {}
  local temperatures = {}
  for _, entry in ipairs(storage.cases) do
    local name = entry.case.name
    local reactor = entry.reactor

    -- The status line, read back off the entity rather than recomputed.
    local status = reactor.custom_status
    local label = status and status.label and status.label[1]
    record(label == "rf-reactor-status." .. name,
      name .. ": the status line says " .. name, tostring(label))
    if label then
      record(seen_labels[label] == nil, name .. ": the three states are three different lines", label)
      seen_labels[label] = true
    end

    -- And the values, read at the FAR end of the wire connected a pass ago.
    local network = entry.probe.get_circuit_network(RED)
    record(network ~= nil, name .. ": the probe is on a circuit network")
    if network then
      local temperature = network.get_signal(TEMPERATURE)
      local q = network.get_signal(Q_FACTOR)
      temperatures[name] = temperature

      local plasma = reactor.fluidbox[1]
      local actual = plasma and plasma.temperature or 0

      if name == "starved" then
        record(temperature == 0, "starved: reports no temperature", tostring(temperature))
      else
        -- Within a few percent, not to the degree. The wire carries what the reactor published at
        -- its last report -- control.lua reports every fifth simulation step, not every tick -- so a
        -- reactor whose plasma is still moving reads slightly stale. Demanding equality here would be
        -- demanding that the reporting cadence be one tick, which is the thing it deliberately is
        -- not.
        --
        -- THE IDLE CASE GETS ITS OWN BOUND SINCE #52, and the reason is the point rather than the
        -- number. This block used to say "the idle one is slowly cooling" and hold both cases to 5%.
        -- It is not slowly cooling any more: with the radiation term carried, a plasma below fusion
        -- temperature radiates away far more than it holds -- around 350 kW against 200 kJ of
        -- thermal content at 5e4 C -- so it falls to the floor in well under a second and can more
        -- than halve between one report and the next. That is the term working, not the signal
        -- breaking: the running reactor is still held to 5%, and the same assertion catches a wire
        -- that has stopped tracking its own reactor in every case where the plasma is not in free
        -- fall.
        --
        -- The bound is a factor rather than a percentage because the quantity is no longer a drift.
        local drift = math.abs(temperature - actual) / actual
        local bound = (name == "idle") and 4.0 or 0.05
        record(drift < bound,
          name .. ": the temperature on the wire is this reactor's own plasma, to within the report cadence",
          string.format("wire %d, plasma %.6g, %.2f%% apart (bound %.0f%%)",
            temperature, actual, drift * 100, bound * 100))
      end

      if name == "running" then
        record(q > 0, "running: a Q factor reaches the wire", tostring(q))
      end
    end
  end

  -- The aggregate check. These two are three orders of magnitude apart; one number could not
  -- describe both.
  local running, idle = temperatures["running"], temperatures["idle"]
  record(running and idle and running > idle * 10,
    "each reactor reports itself, not an aggregate of both",
    string.format("running %s, idle %s", tostring(running), tostring(idle)))

  lines[#lines + 1] = string.format("%s: %d checks, %d failures",
    failures == 0 and "PASS" or "FAIL", #lines, failures)
  for _, line in ipairs(lines) do log("OBS-RIG " .. line) end
end

-- Tick 0 fires every interval, and at tick 0 nothing has happened yet: the infinity pipes have not
-- filled and no reactor has ever been stepped, so all three would report "starved" and read exactly
-- like a broken mod. Then one pass to wire, and a later one to read.
script.on_nth_tick(120, function()
  if game.tick == 0 then return end
  if not storage.wired then
    storage.seen_combinators = {}
    storage.wired = true
    wire_everything()
    return
  end
  if storage.done then return end
  storage.done = true
  verify()
end)
'@
    Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') `
        -Value $lua.Replace('__PLASMAFEED__', $feed)
}

$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }

try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled @() -Mods ($ourMods + $rigName)
    Write-Rig

    $save = Join-Path $temp 'obs.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', '400', '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'OBS-RIG (ok|FAIL|PASS|FAIL:)' |
        ForEach-Object { ($_ -split 'OBS-RIG ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the rig reported nothing; it never reached its check tick.' }

    foreach ($line in $reported) { Write-Host "  $line" }

    $verdict = $reported | Where-Object { $_ -match '^(PASS|FAIL): ' } | Select-Object -Last 1
    if (-not $verdict)          { throw 'the rig produced no verdict line.' }
    if ($verdict -notmatch '^PASS') { throw "reactor observability is broken: $verdict" }

    Write-Host ''
    Write-Host 'OK - status line, both signals, and a wire a player could have dragged.'
}
finally {
    if ($KeepTemp) { Write-Host ''; Write-Host "temp kept at: $temp" }
    Remove-ModJunctions -ModDirectory $modDir
    if (-not $KeepTemp) { Remove-TempDirectory -Path $temp -Label 'check-observability' }
}
