<#
.SYNOPSIS
    Checks that the confinement ladder is per force: four forces on one map, same reactor, same
    plasma, same power, different research -- and four different temperatures. Discharges #53.

.DESCRIPTION
    #53's first acceptance criterion is that confinement time varies per force and that two forces
    with different research simulate differently, "proven in game rather than asserted". That is
    exactly what the Lua tests cannot do: they drive reactor-logic directly and can hand it any spec
    they like, so they prove the arithmetic and say nothing about whether control.lua ever gives a
    reactor its owner's number. This does.

    WHAT IS BUILT

    Four rf-reactors, far enough apart that no two share a power network, one per force. Each is
    given a full box of D-D plasma at 2.422e8 C -- the temperature an UNRESEARCHED reactor settles
    at, which makes the first force a flat control line rather than another curve. Each force gets
    its own substation and power interface, because an electric network does not cross forces.

      rf-none       nothing researched                          30 s of confinement
      rf-half       every rung but the top                      50 s
      rf-upgraded   every rung but the top, AND THEN the top     50 s, then 60 s from tick 3600
      rf-uttermost  the whole ladder from the start             60 s

    rf-half is what makes rf-upgraded mean anything. The two are identical for the first minute and
    identical in every other respect for the whole run, so the only thing that can separate them by
    the end is the research granted in between -- which is the on_research_finished handler in
    control.lua, and the per-force cache it drops.

    The plasma is topped back up to a full box every second, temperature preserved. Without that
    the four reactors burn their fuel at four different rates, a thinner plasma runs hotter, and the
    experiment would be measuring two things at once.

    WHAT IS ASSERTED

      * the four temperatures are strictly ordered by confinement time
      * the unresearched force does not move: it starts at its own equilibrium and stays there,
        which is the control that says the other three moved because of research
      * every event control.lua drops its cache on exists in this engine version, which the mod's
        own tolerant wiring cannot tell you
      * rf-half and rf-upgraded agree while they hold the same research
      * and separate after the grant, by far more than they differ before it

    A FORCE PART WAY THROUGH THE LADDER IN AN EXISTING SAVE gets what its research says, and that
    is proven by the shape of every rig here rather than by an assertion of its own: on_init builds
    and researches, the save is written, and a SECOND Factorio run loads that save and takes every
    reading. Nothing about a force's confinement time is stored in the save -- control.lua derives
    it from force.technologies on demand -- so a reading taken after a reload is a reading taken
    from research the save carried, which is the criterion.

    WHAT IT DOES NOT COVER: the load-time guard against the temperature clamp. That one refuses to
    load, so a rig that loads cannot exercise it; it is negative-tested in tests/test-reactor-logic.lua
    by breaking a ladder and requiring the answer to change.

.PARAMETER FactorioExe
    Path to Factorio.exe. Defaults to $env:FACTORIO_EXE, then the Steam install on this machine.

.PARAMETER KeepTemp
    Keep the save, the rig mod and the captured output.

.EXAMPLE
    pwsh -File scripts/check-confinement.ps1
#>

#Requires -Version 7
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/factorio-lib.ps1"

$repoRoot = Split-Path $PSScriptRoot -Parent
$ourMods  = Get-RepoMods
$rigName  = 'rf-confinement-rig'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-conf-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

function Write-Rig {
    @{
        name = $rigName; version = '0.0.1'; title = 'Confinement ladder check'
        author = 'check-confinement.ps1'; factorio_version = '2.0'
        dependencies = @('base >= 2.0.77', 'realistic-fusion-refreshed')
    } | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

    $lua = @'
-- Generated by scripts/check-confinement.ps1. Nothing here ships.

local PLASMA = "rf-d-d-plasma"
local FULL   = 1000
-- Where an unresearched D-D reactor settles, so rf-none is a flat line rather than a fourth curve.
-- tests/test-reactor-logic.lua pins it; if it moves, this rig reports the control drifting and
-- names the number, which is the right way round.
local SEED_C = 2.422e8

-- One minute of game time per phase, at sixty ticks a second.
local PHASE_TICKS = 3600

local lines = {}
local failures = 0

local function record(ok, name, detail)
  if not ok then failures = failures + 1 end
  lines[#lines + 1] = string.format("%s  %s%s", ok and "ok  " or "FAIL", name,
    detail and ("  -- " .. detail) or "")
end

local function must(entity, what)
  if not entity then error(what .. " refused") end
  return entity
end

-- The ladder, discovered from the prototypes rather than counted here, so a rung added to
-- scripts/reactor-logic.lua is picked up instead of silently ignored.
local function ladder()
  local rungs = {}
  for level = 1, 20 do
    local name = "rf-plasma-confinement-" .. level
    if not prototypes.technology[name] then break end
    rungs[#rungs + 1] = name
  end
  return rungs
end

--- Research the first `count` rungs for a force.
local function grant(force, rungs, count)
  for level = 1, count do
    force.technologies[rungs[level]].researched = true
  end
end

-- `at` is the substation's centre and must be a whole number: a 2x2 entity sits on a tile boundary
-- where the 1x1 interface beside it sits on a tile centre, and create_entity would snap a half-tile
-- position rather than refuse it.
local function power(surface, force, at)
  must(surface.create_entity({ name = "substation", position = at, force = force }), "substation")
  local eei = must(surface.create_entity({
    name = "electric-energy-interface", position = { at[1] + 2.5, at[2] + 0.5 }, force = force,
  }), "power source")
  -- Joules per TICK, not watts (scripts/check-brownout.ps1 measured that and says so). 2e6 is
  -- 120 MW against one reactor's 50, so nothing here is ever short of power.
  eei.power_production = 2e6
end

--- One force, one reactor, one power network.
local function cell(surface, name, x, rungs, researched)
  local force = game.create_force(name)
  grant(force, rungs, researched)

  local reactor = must(surface.create_entity({
    name = "rf-reactor", position = { x, 0.5 }, force = force, raise_built = true,
  }), "rf-reactor for " .. name)
  power(surface, force, { math.floor(x) + 9, 5 })

  reactor.fluidbox[1] = { name = PLASMA, amount = FULL, temperature = SEED_C }
  return { force = force, reactor = reactor, name = name }
end

script.on_init(function()
  local surface = game.surfaces[1]

  surface.request_to_generate_chunks({ 50, 0 }, 8)
  surface.force_generate_chunk_requests()
  local tiles = {}
  for x = -20, 120 do
    for y = -20, 20 do tiles[#tiles + 1] = { name = "landfill", position = { x, y } } end
  end
  surface.set_tiles(tiles)
  for _, e in pairs(surface.find_entities_filtered({ area = { { -20, -20 }, { 120, 20 } } })) do
    if e.type ~= "character" then e.destroy() end
  end

  local rungs = ladder()
  if #rungs < 3 then
    error(string.format(
      "this rig needs a confinement ladder of at least three rungs and found %d. If the ladder in " ..
      "scripts/reactor-logic.lua was shortened, the experiment below needs rewriting rather than " ..
      "adjusting.", #rungs))
  end

  storage.rungs = rungs
  storage.cells = {
    none      = cell(surface, "rf-none",      0.5,  rungs, 0),
    half      = cell(surface, "rf-half",      30.5, rungs, #rungs - 1),
    upgraded  = cell(surface, "rf-upgraded",  60.5, rungs, #rungs - 1),
    uttermost = cell(surface, "rf-uttermost", 90.5, rungs, #rungs),
  }
  log("CONF-RIG built")
end)

--- This reactor's plasma temperature, or nil if it has none.
local function temperature(c)
  local plasma = c.reactor.fluidbox[1]
  return plasma and plasma.temperature or nil
end

-- Held full, so the only difference between the four reactors is their research. A reactor left to
-- drain burns its fuel at a rate that depends on how hot it is, a thinner plasma settles hotter,
-- and the four curves would separate for two reasons instead of one.
script.on_nth_tick(60, function()
  for _, c in pairs(storage.cells) do
    local plasma = c.reactor.fluidbox[1]
    if plasma and plasma.amount < FULL then
      c.reactor.fluidbox[1] = { name = plasma.name, amount = FULL, temperature = plasma.temperature }
    end
  end
end)

script.on_nth_tick(PHASE_TICKS, function()
  if game.tick == 0 or storage.done then return end
  local c = storage.cells

  -- ---------------------------------------------------------------- phase one: research as built
  if not storage.phase_one then
    storage.phase_one = {}
    for key, one in pairs(c) do storage.phase_one[key] = temperature(one) end
    local p = storage.phase_one

    for key, one in pairs(c) do
      record(p[key] ~= nil, string.format("%s still holds plasma", one.name))
    end

    -- THE CONTROL. An unresearched reactor was seeded at its own equilibrium, so it should not have
    -- moved. If it has, every other line here is measuring something else as well as research.
    record(p.none and math.abs(p.none - SEED_C) / SEED_C < 0.02,
      "the unresearched reactor sits where it was seeded, so it is a control and not a curve",
      p.none and string.format("%.5g C against %.5g C seeded", p.none, SEED_C) or "no plasma")

    -- THE EVENTS THAT DROP THE CACHE, checked by name because control.lua wires them TOLERANTLY:
    -- a name this engine version does not define is simply skipped, which is right for forward
    -- compatibility and completely silent about a typo. On 2.0.77 all five exist, and if one ever
    -- stops existing this says which rather than leaving a force stuck on old research.
    for _, name in ipairs({ "on_research_finished", "on_research_reversed",
                            "on_technology_effects_reset", "on_force_reset", "on_forces_merged" }) do
      record(defines.events[name] ~= nil,
        string.format("defines.events.%s exists, so control.lua really wires it", name))
    end

    -- THE TICKET'S FIRST CRITERION. Four forces, one prototype, one map, four temperatures.
    record(p.none and p.half and p.half > p.none * 1.2,
      "a force part way up the ladder runs hotter than one with nothing researched",
      string.format("%.5g C against %.5g C", p.half or 0, p.none or 0))
    record(p.half and p.uttermost and p.uttermost > p.half * 1.05,
      "and a force with the whole ladder runs hotter still",
      string.format("%.5g C against %.5g C", p.uttermost or 0, p.half or 0))

    -- The pair that the second phase turns on. Identical research, so identical physics -- to the
    -- last digit, because Factorio is deterministic and nothing separates these two yet.
    record(p.half and p.upgraded and math.abs(p.upgraded - p.half) / p.half < 1e-9,
      "the two forces holding the same research are indistinguishable",
      string.format("%.9g C against %.9g C", p.upgraded or 0, p.half or 0))

    -- ------------------------------------------------------------ and now research the top rung
    --
    -- On one of the pair only. Everything else about them stays equal, so whatever separates them
    -- from here is control.lua noticing that a force's research changed.
    c.upgraded.force.technologies[storage.rungs[#storage.rungs]].researched = true
    log("CONF-RIG granted the top rung to rf-upgraded")
    return
  end

  -- ---------------------------------------------------------------- phase two: research mid-save
  storage.done = true
  local p, q = storage.phase_one, {}
  for key, one in pairs(c) do q[key] = temperature(one) end

  record(q.none and math.abs(q.none - SEED_C) / SEED_C < 0.02,
    "the control is still where it started after two minutes",
    q.none and string.format("%.5g C", q.none) or "no plasma")

  -- THE INVALIDATION. Researching the top rung on a live save has to reach the simulation, and the
  -- force that did it has to pull away from the one that did not.
  record(q.upgraded and q.half and q.upgraded > q.half * 1.05,
    "researching the top rung mid-save separates two forces that were identical",
    string.format("%.5g C against %.5g C, having been equal a minute ago", q.upgraded or 0, q.half or 0))
  record(q.upgraded and q.half and p.upgraded and p.half
    and (q.upgraded - q.half) > (p.upgraded - p.half) + 1e6,
    "and the separation appeared after the grant rather than being there all along",
    string.format("%.4g C apart now, %.4g C apart before",
      (q.upgraded or 0) - (q.half or 0), (p.upgraded or 0) - (p.half or 0)))

  -- Still ordered the right way -- the force that has held the top rung all along is ahead of the
  -- one that has just been given it -- AND the gap is closing, which is the half with a margin on
  -- it. The two now hold identical research and are relaxing toward one equilibrium from different
  -- sides of it, so the ordering is a monotonicity property rather than a measurement and would
  -- eventually come down to float noise; the shrinking gap is what actually says the newly
  -- researched force caught the physics of the other one rather than merely being behind it.
  local gap_before = (p.uttermost or 0) - (p.upgraded or 0)
  local gap_now    = (q.uttermost or 0) - (q.upgraded or 0)
  record(q.uttermost and q.upgraded and q.uttermost > q.upgraded and gap_now < gap_before * 0.8,
    "the force that had the top rung all along is still ahead, and the other is closing on it",
    string.format("%.5g C against %.5g C -- %.4g C apart, having been %.4g C apart",
      q.uttermost or 0, q.upgraded or 0, gap_now, gap_before))

  lines[#lines + 1] = string.format("%s: %d checks, %d failures",
    failures == 0 and "PASS" or "FAIL", #lines, failures)
  for _, line in ipairs(lines) do log("CONF-RIG " .. line) end
end)
'@
    Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') -Value $lua
}

$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }

try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled @() -Mods ($ourMods + $rigName)
    Write-Rig

    $save = Join-Path $temp 'confinement.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    # Two phases of a minute each, plus a margin so the second phase tick is certainly reached.
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', '7500', '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'CONF-RIG (ok|FAIL|PASS)' |
        ForEach-Object { ($_ -split 'CONF-RIG ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the rig reported nothing; it never reached its check tick.' }

    foreach ($line in $reported) { Write-Host "  $line" }

    $verdict = $reported | Where-Object { $_ -match '^(PASS|FAIL): ' } | Select-Object -Last 1
    if (-not $verdict)              { throw 'the rig produced no verdict line.' }
    if ($verdict -notmatch '^PASS') { throw "the confinement ladder is not per force: $verdict" }

    Write-Host ''
    Write-Host 'OK - confinement time follows the force that owns the reactor, across a save/load,'
    Write-Host '     and research finished mid-save reaches the simulation.'
}
finally {
    if ($KeepTemp) { Write-Host ''; Write-Host "temp kept at: $temp" }
    Remove-ModJunctions -ModDirectory $modDir
    if (-not $KeepTemp) { Remove-TempDirectory -Path $temp -Label 'check-confinement' }
}
