#Requires -Version 7
<#
.SYNOPSIS
    Probes whether a boiler's FLUID ENERGY SOURCE box can be chained -- whether one heat exchanger
    can pass reactor energy through to the next, the way a row of steam turbines passes steam.

.DESCRIPTION
    A PROBE, NOT A CHECK. Every line it prints is a measurement, and a negative answer is as much of
    a result as a positive one -- exit 0 means it ran and reported, never that the answer was the
    hoped-for one. Nothing here ships and nothing here decides: the layout is Truls's to choose.

    THE QUESTION AND WHY IT IS OPEN. A lit D-T reactor sells about 322 MW (measured by
    scripts/check-brownout.ps1) and one rf-heat-exchanger takes 40 MW, so a reactor needs eight of
    them. rf-hc-exchanger exists for exactly that reason at 400 MW, and one covers a whole reactor
    -- but a player who has not researched it, or who wants the ordinary machine, has to plumb eight.
    Whether those eight can be laid in a row that feeds itself, rather than each dropped on a
    manifold, is what this asks.

    THE DATA STAGE ALREADY SAID YES, WHICH IS WORTH NOTHING. Setting flow_direction = "input-output"
    on rf-heat-exchanger's energy_source.fluid_box loads cleanly against 2.0.77 -- tried, and
    load-check passes. So did the reactor-as-crafting-machine that probe-native-heat.ps1's header
    records: it loaded perfectly and then moved no fluid at all. A prototype the engine accepts is
    not a prototype the engine plumbs, and the difference is only visible at runtime.

    WHAT IT MEASURES, per variant:

      1. Whether two of them laid end to end join into ONE fluid system. That is structural: if the
         engine does not join the boxes, nothing else matters.
      2. Whether fluid put into the first actually REACHES the second. A shared system id is still
         only a claim until something flows along it.
      3. Whether the second one then BURNS it -- status and steam out. Reaching the box is not the
         same as being usable as fuel, and this is the step the crafting-machine attempt failed.

    Variants are rig-only prototypes, deepcopied from rf-heat-exchanger and named outside the rf-
    set, so the shipped machine is untouched and control.lua never sees them.

    Findings belong in docs/research/. Kept committed so the next engine version can be asked the
    same question.
#>
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [int]    $Ticks = 600,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
. "$repoRoot/scripts/factorio-lib.ps1"

$ourMods = @('realistic-fusion-refreshed-core', 'realistic-fusion-refreshed')
$rigName = 'rf-exchanger-chaining-probe'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-chain-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

@{
    name = $rigName; version = '0.0.1'; title = 'Exchanger chaining probe'
    author = 'probe-exchanger-chaining.ps1'; factorio_version = '2.0'
    dependencies = @('base >= 2.0.77', 'realistic-fusion-refreshed', 'realistic-fusion-refreshed-core')
} | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

# ---------------------------------------------------------------------------- the rig's prototypes
$data = @'
-- Generated by probe-exchanger-chaining.ps1. Nothing here ships.
--
-- Each variant is rf-heat-exchanger with its ENERGY box's connections replaced. Everything else --
-- volumes, filters, the water and steam boxes, energy_consumption -- is the shipped machine's, so
-- what differs between rows is only the thing being asked about.
--
-- Named outside the rf- set on purpose: control.lua keys its reactor table by entity name, so these
-- are invisible to the simulation.

local VARIANTS = {
  -- The shipped arrangement: energy in on the west long face only, flow_direction "input". The
  -- control row. Two of these end to end should NOT join, and if they do the question is wrong.
  { name = "chainprobe-shipped", conns = {
      { flow_direction = "input", direction = defines.direction.west, position = { -2, 0 } },
  } },

  -- Energy in on the west face AND in/out on both short ends, which is the arrangement being asked
  -- about: the first takes energy from the reactor along its long face, and passes it up the column
  -- through the ends.
  { name = "chainprobe-ends", conns = {
      { flow_direction = "input",        direction = defines.direction.west,  position = { -2, 0 } },
      { flow_direction = "input-output", direction = defines.direction.north, position = { -1, -7 } },
      { flow_direction = "input-output", direction = defines.direction.south, position = { -1, 7 } },
  } },

  -- Ends only, no long face. Isolates whether the west connection matters to the joining at all.
  { name = "chainprobe-ends-only", conns = {
      { flow_direction = "input-output", direction = defines.direction.north, position = { -1, -7 } },
      { flow_direction = "input-output", direction = defines.direction.south, position = { -1, 7 } },
  } },
}

local made = {}
for _, v in ipairs(VARIANTS) do
  local e = table.deepcopy(data.raw["boiler"]["rf-heat-exchanger"])
  e.name = v.name
  e.minable = { mining_time = 0.5, result = nil }
  e.energy_source = table.deepcopy(e.energy_source)
  e.energy_source.fluid_box = table.deepcopy(e.energy_source.fluid_box)
  e.energy_source.fluid_box.pipe_connections = v.conns
  made[#made + 1] = e
end
data:extend(made)
'@
Set-Content -Path (Join-Path $rigDir 'data.lua') -Value $data -Encoding utf8

# ---------------------------------------------------------------------------- the rig's control
$control = @'
-- Generated by probe-exchanger-chaining.ps1. Nothing here ships.

local VARIANTS = { "chainprobe-shipped", "chainprobe-ends", "chainprobe-ends-only" }
local ENERGY   = "rf-reactor-energy"

-- Tagged so the caller can pick these out of a benchmark log that is mostly not ours.
local function say(line) localised_print('CHAINPROBE ' .. line) end

--- Which fluidbox index carries the energy source's fluid, found rather than assumed.
--
-- A boiler in output-to-separate-pipe mode has water, steam and its energy source, and the order is
-- the engine's business. Asking each box what it filters is the only way to be sure which is which.
local function energy_index(entity)
  for i = 1, #entity.fluidbox do
    local filters = entity.fluidbox.get_filter(i)
    if filters and filters.name == ENERGY then return i end
  end
  return nil
end

--- entity.status is a number; this is its name. There is no status_string in 2.0.77.
local function status_name(entity)
  if not (entity and entity.valid) then return "?" end
  local s = entity.status
  if s == nil then return "none" end
  for k, v in pairs(defines.entity_status) do
    if v == s then return k end
  end
  return tostring(s)
end

local function place(surface, force, name, x, y)
  local e = surface.create_entity({ name = name, position = { x, y }, force = force, raise_built = true })
  if not e then error("could not place " .. name .. " at " .. x .. "," .. y) end
  return e
end

script.on_nth_tick(30, function()
  if storage.done then return end
  storage.done = true

  local surface = game.surfaces[1]
  local force   = game.forces.player
  surface.always_day = true

  for _, e in pairs(surface.find_entities_filtered({ area = { { -80, -80 }, { 80, 80 } } })) do
    if e.type ~= "character" then e.destroy() end
  end

  say("")
  say("--- can one exchanger pass reactor energy to the next? ------------------")
  say(string.format("%-24s %-10s %-12s %-14s %-10s %s",
    "variant", "joined", "reached 2nd", "2nd status", "1st held", "note"))

  local x = -60
  for _, name in ipairs(VARIANTS) do
    -- Two end to end: fifteen tall, so the second sits fifteen tiles north of the first and their
    -- short ends meet.
    local first  = place(surface, force, name, x, 0)
    local second = place(surface, force, name, x, -15)

    local i1 = energy_index(first)
    local i2 = energy_index(second)
    if not i1 or not i2 then
      say(string.format("%-24s %-10s %-12s %-14s %s", name, "-", "-", "-", "no energy box found"))
    else
      -- Whether the two boxes are actually joined, asked through the connections themselves rather
      -- than a system id: get_fluid_system_id is not a 2.0.77 method, and get_pipe_connections is
      -- what the shipped rigs already use. A connection whose target's owner is the other machine
      -- is the engine saying it plumbed them together.
      local joined = false
      for _, c in ipairs(first.fluidbox.get_pipe_connections(i1)) do
        if c.target and c.target.owner and c.target.owner.unit_number == second.unit_number then
          joined = true
        end
      end

      -- Fill only the FIRST one, which is the whole point: whatever the second ends up holding got
      -- there by travelling.
      first.fluidbox[i1] = { name = ENERGY, amount = 200 }

      -- Water in and somewhere for steam to go, so the machine can actually run rather than sitting
      -- blocked -- a blocked boiler burns nothing and would look like a chaining failure.
      local wi
      for i = 1, #first.fluidbox do
        local f = first.fluidbox.get_filter(i)
        if f and f.name == "water" then wi = i end
      end
      if wi then
        first.fluidbox[wi]  = { name = "water", amount = 200 }
        second.fluidbox[wi] = { name = "water", amount = 200 }
      end

      storage.cases = storage.cases or {}
      storage.cases[#storage.cases + 1] =
        { name = name, first = first, second = second, i1 = i1, i2 = i2, joined = joined }
    end
    x = x + 20
  end

  -- THE CONTROL, and the probe is worth little without it. Two shipped-arrangement exchangers set
  -- apart with a run of rf-pipe joining their WEST faces, and the pipe filled rather than the
  -- machine. If fluid reaches the second here but not in the rows above, then what fails is
  -- box-to-box transfer specifically, and not the way this probe puts fluid into things.
  do
    local a = place(surface, force, "chainprobe-shipped", 40, 0)
    local b = place(surface, force, "chainprobe-shipped", 40, -15)
    -- VANILLA pipe, not rf-pipe. rf-pipe's connections carry the plasma category (#26), so it
    -- cannot carry rf-reactor-energy at all -- the first version of this control used it and
    -- measured the containment rule rather than the question. Reactor energy is an ordinary fluid
    -- and travels in ordinary pipes, which is the whole point of ADR 0018.
    --
    -- The run sits one tile west of the machines: their energy connection is on the west face at
    -- local x = -2, which is absolute x = 38, so the pipe it reaches for is at 37.
    local pipes = {}
    for y = -15, 0 do
      pipes[#pipes + 1] = place(surface, force, "pipe", 37, y)
    end

    local ia = energy_index(a)
    local ib = energy_index(b)
    for _, pipe in ipairs(pipes) do
      pipe.fluidbox[1] = { name = ENERGY, amount = 100 }
    end
    storage.control = { a = a, b = b, ia = ia, ib = ib, pipes = pipes }
  end

  storage.report_at = game.tick + 300
end)

script.on_event(defines.events.on_tick, function()
  if not storage.report_at then return end

  -- KEEP THE FIRST ONE FED, which the first version of this probe did not and was wrong for. Its
  -- energy box holds 200 units and the machine burns 40 MW of 1 MJ units -- 0.667 a tick -- so over
  -- 300 ticks it consumed exactly the 200 it was given, and "nothing reached the second" measured
  -- the first running dry rather than anything about chaining. Topping it up every tick means there
  -- is always fluid there to travel if the engine will carry it.
  for _, c in ipairs(storage.cases or {}) do
    if c.first.valid then
      local box = c.first.fluidbox[c.i1]
      if not box or box.amount < 150 then
        c.first.fluidbox[c.i1] = { name = "rf-reactor-energy", amount = 200 }
      end
    end
  end

  if game.tick < storage.report_at then return end
  storage.report_at = nil

  for _, c in ipairs(storage.cases or {}) do
    local box = c.second.valid and c.second.fluidbox[c.i2] or nil
    local held = box and box.amount or 0
    local src = c.first.valid and c.first.fluidbox[c.i1] or nil
    local kept = src and src.amount or 0
    say(string.format("%-24s %-10s %-12.4g %-14s %-10.4g %s",
      c.name,
      c.joined and "yes" or "no",
      held,
      status_name(c.second),
      kept,
      (held > 0) and "energy travelled" or "nothing arrived"))
  end

  local c = storage.control
  if c and c.a.valid and c.b.valid then
    -- Keep the run charged for the same reason the machines above are kept charged.
    for _, pipe in ipairs(c.pipes) do
      if pipe.valid then pipe.fluidbox[1] = { name = "rf-reactor-energy", amount = 100 } end
    end
    local ba = c.a.fluidbox[c.ia]
    local bb = c.b.fluidbox[c.ib]
    say(string.format("%-24s %-10s %-12.4g %-14s %-10.4g %s",
      "shipped + a pipe run", "n/a",
      bb and bb.amount or 0, status_name(c.b), ba and ba.amount or 0,
      ((bb and bb.amount or 0) > 0) and "energy travelled" or "nothing arrived"))
  end

  say("")
  say("done")
  game.set_game_state({ game_finished = true, player_won = true, can_continue = false })
end)
'@
Set-Content -Path (Join-Path $rigDir 'control.lua') -Value $control -Encoding utf8

# ---------------------------------------------------------------------------- run it
$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }
try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    $enabled = Resolve-BundledSelection -Requested @() -Bundled $bundled
    Write-Host "bundled enabled: $(if ($enabled) { $enabled -join ', ' } else { 'none (base 2.0 only)' })"
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled $enabled -Mods ($ourMods + $rigName)

    $save = Join-Path $temp 'chain.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', [string]($Ticks + 120),
        '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'CHAINPROBE ' |
        ForEach-Object { ($_ -split 'CHAINPROBE ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the probe reported nothing.' }
    $reported | ForEach-Object { Write-Host $_ }
    if ($reported[-1] -ne 'done') {
        Write-Host ''
        Write-Host 'NOTE: the run ended before the report. Raise -Ticks or the benchmark budget.'
    }
}
finally {
    if (-not $KeepTemp) {
        Remove-ModJunctions -ModDirectory $modDir
        Remove-TempDirectory -Path $temp -Label 'probe-exchanger-chaining'
    } else { Write-Host "kept: $temp" }
}

Write-Host ''
Write-Host 'Probe finished. Exit 0 means it ran and reported, not that the answer was yes.'
