<#
.SYNOPSIS
    Probes whether a boiler's FLUID ENERGY SOURCE box can be chained -- whether one heat exchanger
    can pass reactor energy through to the next, the way a row of steam turbines passes steam.

.DESCRIPTION
    A PROBE, NOT A CHECK. Every line it prints is a measurement, and a negative answer is as much of
    a result as a positive one -- exit 0 means it ran and reported, never that the answer was the
    hoped-for one. Nothing here ships and nothing here decides: the layout is Truls's to choose.

    THE QUESTION AND WHY IT IS OPEN. A lit D-T reactor sells about 322 MW (measured by
    scripts/check-brownout.ps1) and one rf-heat-exchanger takes 40 MW, so a reactor needs eight of
    them. rf-hc-exchanger exists for exactly that reason at 400 MW, and one covers a whole reactor
    -- but a player who has not researched it, or who wants the ordinary machine, has to plumb eight.
    Whether those eight can be laid in a row that feeds itself, rather than each dropped on a
    manifold, is what this asks.

    THE DATA STAGE ALREADY SAID YES, WHICH IS WORTH NOTHING. Setting flow_direction = "input-output"
    on rf-heat-exchanger's energy_source.fluid_box loads cleanly against 2.0.77 -- tried, and
    load-check passes. So did the reactor-as-crafting-machine that probe-native-heat.ps1's header
    records: it loaded perfectly and then moved no fluid at all. A prototype the engine accepts is
    not a prototype the engine plumbs, and the difference is only visible at runtime.

    WHAT IT MEASURES, per variant:

      1. Whether two of them laid end to end join into ONE fluid system. That is structural: if the
         engine does not join the boxes, nothing else matters.
      2. Whether fluid put into the first actually REACHES the second. A shared system id is still
         only a claim until something flows along it.
      3. Whether the second one then BURNS it -- status and steam out. Reaching the box is not the
         same as being usable as fuel, and this is the step the crafting-machine attempt failed.

    Variants are rig-only prototypes, deepcopied from rf-heat-exchanger and named outside the rf-
    set, so the shipped machine is untouched and control.lua never sees them.

    WHAT IT FOUND, 2026-09-06 (#111): they chain, under two conditions. The fuel has to ARRIVE
    through a connection -- fuel written into a fluid ENERGY SOURCE's box with fluidbox[i] = {...}
    never leaves it, which is specific to that kind of box and not true of an ordinary output box
    -- and every connection on that box has to be input-output, because one declared plain "input"
    stops fuel leaving by the others. An earlier version of this probe met neither condition and
    reported five ways that exchangers cannot chain, contradicting #82 and ADR 0018. They were
    wrong and the ADR was right.

    AND A ROW OF EIGHT (#275). Everything above measures TWO machines. Eight is the shape a lit D-T
    reactor needs and the shape ADR 0018 describes, and its rate has never been measured. The last
    section lays eight of the machine #275 decides on, feeds energy into the first one's long face
    through a single connection the way a reactor bolts, and reports what each of the eight holds.

    It asks water as well, and that constraint is NEW rather than merely unmeasured: once the
    machines bolt short end to short end, every interior water connection is consumed by a joint,
    so a row is fed water at its two ends and nowhere else. Eight machines at 40 MW want about
    3,300 units of water a second through those two connections.

    Findings belong in docs/research/. Kept committed so the next engine version can be asked the
    same question.
#>

#Requires -Version 7
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [int]    $Ticks = 600,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
. "$repoRoot/scripts/factorio-lib.ps1"

$ourMods = Get-RepoMods
$rigName = 'rf-exchanger-chaining-probe'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-chain-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

@{
    name = $rigName; version = '0.0.1'; title = 'Exchanger chaining probe'
    author = 'probe-exchanger-chaining.ps1'; factorio_version = '2.0'
    dependencies = @('base >= 2.0.77', 'realistic-fusion-refreshed', 'realistic-fusion-refreshed-core')
} | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

# ---------------------------------------------------------------------------- the rig's prototypes
$data = @'
-- Generated by probe-exchanger-chaining.ps1. Nothing here ships.
--
-- Each variant is rf-heat-exchanger with its ENERGY box's connections replaced. Everything else --
-- volumes, filters, the water and steam boxes, energy_consumption -- is the shipped machine's, so
-- what differs between rows is only the thing being asked about.
--
-- Named outside the rf- set on purpose: control.lua keys its reactor table by entity name, so these
-- are invisible to the simulation.

local VARIANTS = {
  -- The shipped arrangement: energy in on the west long face only, flow_direction "input". The
  -- control row. Two of these end to end should NOT join, and if they do the question is wrong.
  { name = "chainprobe-shipped", conns = {
      { flow_direction = "input", direction = defines.direction.west, position = { -2, 0 } },
  } },

  -- Energy in on the west face AND in/out on both short ends, which is the arrangement being asked
  -- about (of the pinned pre-#275 frame; see pre_275_frame below): the first takes energy from the reactor along its long face, and passes it up the column
  -- through the ends.
  { name = "chainprobe-ends", conns = {
      { flow_direction = "input",        direction = defines.direction.west,  position = { -2, 0 } },
      { flow_direction = "input-output", direction = defines.direction.north, position = { -1, -7 } },
      { flow_direction = "input-output", direction = defines.direction.south, position = { -1, 7 } },
  } },

  -- Ends only, no long face. Isolates whether the west connection matters to the joining at all.
  { name = "chainprobe-ends-only", conns = {
      { flow_direction = "input-output", direction = defines.direction.north, position = { -1, -7 } },
      { flow_direction = "input-output", direction = defines.direction.south, position = { -1, 7 } },
  } },

  -- ALL THREE input-output, which is the shape probe-energy-containment.ps1 chains and the shape
  -- ADR 0018's Decision item 4 describes. It differs from "ends" by ONE FIELD: the west face is
  -- input-output here and plain "input" there. That one field is what the fed-by-a-pipe row below
  -- turned out to hang on (#111), and no row in this probe combined it with fuel ARRIVING through
  -- a connection until then.
  { name = "chainprobe-all-io", conns = {
      { flow_direction = "input-output", direction = defines.direction.west,  position = { -2, 0 } },
      { flow_direction = "input-output", direction = defines.direction.north, position = { -1, -7 } },
      { flow_direction = "input-output", direction = defines.direction.south, position = { -1, 7 } },
  } },

  -- CATEGORISED, which is what #82 actually tested and what ADR 0018 records as chaining. That probe
  -- put a connection_category on the energy box -- it existed to prove the engine reads the field in
  -- that nested position at all -- and reported "two of them chain with fuel crossing to the second".
  -- This row is the only remaining difference between that result and the uncategorised rows above,
  -- so it is the one that says whether the category is what makes a chain work.
  { name = "chainprobe-categorised", category = "rf-probe-chain-energy", conns = {
      { flow_direction = "input-output", direction = defines.direction.west,  position = { -2, 0 } },
      { flow_direction = "input-output", direction = defines.direction.north, position = { -1, -7 } },
      { flow_direction = "input-output", direction = defines.direction.south, position = { -1, 7 } },
  } },

  -- THE SHAPE #275 DECIDED, used by the row-of-eight section rather than by the pair table above.
  --
  -- Declared in the pre-#275 frame like every other row here (see pre_275_frame below). #275 then
  -- shipped the machine fifteen wide by five tall with energy on the north long face; that is a
  -- presentation change and the topology is identical, so this frame measures the same machine with
  -- no collision box to rotate. Read the pair off against each other: energy on the long face plus
  -- both short-end tiles, all input-output, and water moved OFF the short-end centre to Truls's
  -- `_ e _ w _` so an energy tile has a place there.
  --
  -- It differs from chainprobe-all-io by the WATER positions and nothing else, which is what makes
  -- the two comparable: if a row starves where a pair did not, the joints are the reason and not
  -- the declaration.
  { name = "chainprobe-row",
    conns = {
      { flow_direction = "input-output", direction = defines.direction.west,  position = { -2, 0 } },
      { flow_direction = "input-output", direction = defines.direction.north, position = { -1, -7 } },
      { flow_direction = "input-output", direction = defines.direction.south, position = { -1, 7 } },
    },
    water = {
      { flow_direction = "input-output", direction = defines.direction.north, position = { 1, -7 } },
      { flow_direction = "input-output", direction = defines.direction.south, position = { 1, 7 } },
    } },
}


-- THE FRAME EVERY COORDINATE IN THIS FILE IS DECLARED IN IS THE ONE #275 REPLACED. Every position
-- here is a five-wide-by-fifteen-tall tile centre with the energy face WEST, which is what the
-- shipped machine was when these rows were written and their findings recorded. ADR 0031 turned the
-- shipped rf-heat-exchanger fifteen wide by five tall with the energy face north, so a plain copy of
-- it no longer fits these coordinates -- a connection outside the collision box is a prototype the
-- engine refuses, and a probe that cannot load answers nothing. The frame is therefore pinned back
-- onto the copy here, boxes and all three fluid boxes, so the probe still measures the shape its
-- research note describes. IT MEASURES THAT SHAPE, NOT THE SHIPPED ONE: rebuilding the rows on the
-- shipped frame is a consequence ADR 0031 lists, and scripts/check-hc.ps1's plant section is the
-- gate on the shipped geometry. The rendered 15x5 sheets are left on it and draw wrong; a probe
-- does not look.
local function pre_275_frame(e)
  e.collision_box = { { -2.25, -7.25 }, { 2.25, 7.25 } }
  e.selection_box = { { -2.5, -7.5 }, { 2.5, 7.5 } }
  e.fluid_box = table.deepcopy(e.fluid_box)
  e.fluid_box.pipe_connections = {
    { flow_direction = "input-output", direction = defines.direction.north, position = { 0, -7 } },
    { flow_direction = "input-output", direction = defines.direction.south, position = { 0, 7 } },
  }
  e.output_fluid_box = table.deepcopy(e.output_fluid_box)
  e.output_fluid_box.pipe_connections = {
    { flow_direction = "output", direction = defines.direction.east, position = { 2, 0 } },
  }
  e.energy_source = table.deepcopy(e.energy_source)
  e.energy_source.fluid_box = table.deepcopy(e.energy_source.fluid_box)
  e.energy_source.fluid_box.pipe_connections = {
    { flow_direction = "input", direction = defines.direction.west, position = { -2, 0 } },
  }
  return e
end

local made = {}
for _, v in ipairs(VARIANTS) do
  local e = pre_275_frame(table.deepcopy(data.raw["boiler"]["rf-heat-exchanger"]))
  e.name = v.name
  e.minable = { mining_time = 0.5, result = nil }
  e.energy_source.fluid_box.pipe_connections = v.conns
  if v.water then
    e.fluid_box = table.deepcopy(e.fluid_box)
    e.fluid_box.pipe_connections = v.water
  end
  if v.category then
    for _, c in ipairs(e.energy_source.fluid_box.pipe_connections) do
      c.connection_category = v.category
    end
  end
  made[#made + 1] = e
end
data:extend(made)
'@
Set-Content -Path (Join-Path $rigDir 'data.lua') -Value $data -Encoding utf8

# ---------------------------------------------------------------------------- the rig's control
$control = @'
-- Generated by probe-exchanger-chaining.ps1. Nothing here ships.

local VARIANTS = { "chainprobe-shipped", "chainprobe-ends", "chainprobe-ends-only",
                   "chainprobe-all-io", "chainprobe-categorised" }
local ENERGY   = "rf-reactor-energy"

-- Tagged so the caller can pick these out of a benchmark log that is mostly not ours.
local function say(line) localised_print('CHAINPROBE ' .. line) end

--- Which fluidbox index carries `fluid`, found rather than assumed.
--
-- A boiler in output-to-separate-pipe mode has water, steam and its energy source, and the order is
-- the engine's business. Asking each box what it filters is the only way to be sure which is which.
local function index_of(entity, fluid)
  for i = 1, #entity.fluidbox do
    local filters = entity.fluidbox.get_filter(i)
    if filters and filters.name == fluid then return i end
  end
  return nil
end

local function energy_index(entity) return index_of(entity, ENERGY) end

--- An infinity pipe on every FREE target tile of `index`, and never on a tile something stands on.
--
-- create_entity does not collision-check, so without the occupancy test this buries a pipe under a
-- machine. Skipping is right rather than merely safe: two exchangers fifteen tiles apart join
-- through their water boxes, so a column is fed along itself from whichever end is free.
-- A NIL RETURN FROM create_entity USED TO BE SWALLOWED HERE, AND IT COST A RUN. The function
-- returns nil on ground it cannot build on, and the row-of-eight section reaches 105 tiles north,
-- outside the starting area, on a benchmark map whose terrain comes from a fresh seed every run. So
-- a lake under one machine's steam target refused that pipe, the machine backed up and reported
-- full_output, and the run looked like a chaining result rather than a puddle. Two runs of the same
-- rig disagreed and only the pipe tally noticed.
--
-- The refusal count is returned rather than raised: whether a missing pipe matters is the caller's
-- business -- a pair row and a chained row want different things -- but no caller may be unable to
-- find out.
local function unbound(surface, force, entity, index, filter)
  local made, refused = 0, 0
  for _, connection in ipairs(entity.fluidbox.get_pipe_connections(index)) do
    if #surface.find_entities_filtered({ position = connection.target_position }) == 0 then
      local pipe = surface.create_entity({
        name = "infinity-pipe", position = connection.target_position, force = force,
      })
      if pipe then
        pipe.set_infinity_pipe_filter(filter)
        made = made + 1
      else
        refused = refused + 1
      end
    end
  end
  return made, refused
end

--- An infinity pipe on ONE connection of `index`, chosen geometrically rather than by array order.
--
-- The row section needs energy to arrive on the LONG face and nowhere else, because that is the
-- face a reactor bolts to and the whole question is whether the short-end joints carry it onward.
-- unbound() would also feed the row's free short end, which answers a different question.
--
-- `side` is derived from where the connection POINTS rather than from a declared direction:
-- pipe_connections.direction is a data-stage field and get_pipe_connections does not return it.
-- Deriving it is also what stops this rig doing tile arithmetic of its own, which is the mistake
-- ADR 0018 records as producing a false negative on the question that decided it.
local function feed_one(surface, force, entity, index, side, filter)
  if not index then return nil end
  for _, connection in ipairs(entity.fluidbox.get_pipe_connections(index)) do
    local dx = connection.target_position.x - entity.position.x
    local dy = connection.target_position.y - entity.position.y
    local sideways = math.abs(dx) > math.abs(dy)
    local matches = (side == "west" and sideways and dx < 0)
                 or (side == "east" and sideways and dx > 0)
    if matches and #surface.find_entities_filtered({ position = connection.target_position }) == 0 then
      local pipe = surface.create_entity({
        name = "infinity-pipe", position = connection.target_position, force = force,
      })
      if pipe then pipe.set_infinity_pipe_filter(filter) end
      return pipe
    end
  end
  return nil
end

--- Water in and steam out, so the machine can actually RUN.
--
-- WHAT THIS DID AND DID NOT FIX (#111), because the difference matters. The first version filled
-- water once by Lua and gave steam nowhere to go, so every machine here ran dry within seconds and
-- every row reported `no_input_fluid` -- INCLUDING the control row that fluid did reach. That made
-- the status column meaningless and it hid a second fault: the control's feed run was charged only
-- once, which stopped mattering the moment its machines actually started burning.
--
-- It did NOT change a single "reached the 2nd" figure. Plumbing these machines properly was
-- necessary to read the rig honestly and it was not the reason the rows said no; the two rows at
-- the bottom of on_nth_tick are.
--
-- Infinity pipes rather than a per-tick Lua top-up, and that was measured rather than preferred:
-- writing water in and nilling the steam box out every tick left every row at zero, the control
-- included. probe-energy-containment.ps1 plumbs its rig this way and its machines reach `working`.
--
-- BOTH MACHINES OF A PAIR MUST EXIST before either is plumbed, or the skip above has nothing to
-- skip and a pipe ends up buried under the neighbour.
-- Returns how many pipes the ground refused, so a caller that cares can say so. Nothing above the
-- row section reads it, deliberately: those rows sit inside the starting area and have never lost a
-- pipe. The row of eight does not, and it has.
local function plumb(surface, force, entity)
  local water = index_of(entity, "water")
  local steam = index_of(entity, "steam")
  local refused = 0
  if water then
    local _, r = unbound(surface, force, entity, water,
      { name = "water", percentage = 1, mode = "at-least" })
    refused = refused + r
  end
  if steam then
    local _, r = unbound(surface, force, entity, steam,
      { name = "steam", percentage = 0, mode = "at-most" })
    refused = refused + r
  end
  return refused
end

--- entity.status is a number; this is its name. There is no status_string in 2.0.77.
local function status_name(entity)
  if not (entity and entity.valid) then return "?" end
  local s = entity.status
  if s == nil then return "none" end
  for k, v in pairs(defines.entity_status) do
    if v == s then return k end
  end
  return tostring(s)
end

local function place(surface, force, name, x, y)
  local e = surface.create_entity({ name = name, position = { x, y }, force = force, raise_built = true })
  if not e then error("could not place " .. name .. " at " .. x .. "," .. y) end
  return e
end

script.on_nth_tick(30, function()
  if storage.done then return end
  storage.done = true

  local surface = game.surfaces[1]
  local force   = game.forces.player
  surface.always_day = true

  for _, e in pairs(surface.find_entities_filtered({ area = { { -80, -80 }, { 80, 80 } } })) do
    if e.type ~= "character" then e.destroy() end
  end

  say("")
  say("--- can one exchanger pass reactor energy to the next? ------------------")
  say(string.format("%-24s %-10s %-12s %-14s %-10s %s",
    "variant", "joined", "reached 2nd", "2nd status", "1st held", "note"))

  local x = -60
  for _, name in ipairs(VARIANTS) do
    -- Two end to end: fifteen tall, so the second sits fifteen tiles north of the first and their
    -- short ends meet.
    local first  = place(surface, force, name, x, 0)
    local second = place(surface, force, name, x, -15)

    local i1 = energy_index(first)
    local i2 = energy_index(second)
    if not i1 or not i2 then
      say(string.format("%-24s %-10s %-12s %-14s %s", name, "-", "-", "-", "no energy box found"))
    else
      -- Whether the two boxes are actually joined, asked through the connections themselves rather
      -- than a system id: get_fluid_system_id is not a 2.0.77 method, and get_pipe_connections is
      -- what the shipped rigs already use. A connection whose target's owner is the other machine
      -- is the engine saying it plumbed them together.
      local joined = false
      for _, c in ipairs(first.fluidbox.get_pipe_connections(i1)) do
        if c.target and c.target.owner and c.target.owner.unit_number == second.unit_number then
          joined = true
        end
      end

      -- Fill only the FIRST one, which is the whole point: whatever the second ends up holding got
      -- there by travelling.
      first.fluidbox[i1] = { name = ENERGY, amount = 200 }

      -- Water in and somewhere for steam to go, so the machine can actually run rather than
      -- sitting stopped -- a stopped boiler pulls no fuel and would look like a chaining failure.
      plumb(surface, force, first)
      plumb(surface, force, second)

      storage.cases = storage.cases or {}
      storage.cases[#storage.cases + 1] =
        { name = name, first = first, second = second, i1 = i1, i2 = i2, joined = joined }
    end
    x = x + 20
  end

  -- FED THROUGH A CONNECTION RATHER THAN INJECTED, which is the case #82 actually measured and this
  -- probe first did not. ADR 0018 records #82 finding that two categorised exchangers bolted face to
  -- face DO chain "with fuel crossing to the second", and every row above says nothing crosses.
  --
  -- THESE TWO ROWS ARE WHERE THE DISAGREEMENT WAS SETTLED (#111), and they differ by ONE FIELD.
  -- Both are fed from a pipe run on the first machine's west face; both have input-output on the
  -- two short ends the pair joins through. "ends" declares the west face "input" and nothing
  -- crosses; "all-io" declares it "input-output" and the second fills and runs. So the box does
  -- forward fuel, and what stops it is a connection on that box which is receive-only.
  --
  -- Together with the injected rows above, that is the whole answer: fuel WRITTEN into a fluid
  -- energy source's box never moves, and fuel that ARRIVES through a connection moves on if every
  -- connection on the box is input-output.
  storage.fed = {}
  for _, row in ipairs({ { name = "chainprobe-ends", x = 60 },
                         { name = "chainprobe-all-io", x = 80 } }) do
    local first  = place(surface, force, row.name, row.x, 0)
    local second = place(surface, force, row.name, row.x, -15)
    -- Its west energy connection is at local (-2, 0), so absolute (row.x - 2), and reaches for
    -- one tile further west again.
    local feed = {}
    for y = -2, 2 do feed[#feed + 1] = place(surface, force, "pipe", row.x - 3, y) end

    plumb(surface, force, first)
    plumb(surface, force, second)

    for _, pipe in ipairs(feed) do
      pipe.fluidbox[1] = { name = ENERGY, amount = 100 }
    end
    storage.fed[#storage.fed + 1] = { name = row.name, first = first, second = second,
      i2 = energy_index(second), i1 = energy_index(first), pipes = feed }
  end

  -- THE CONTROL, and the probe is worth little without it. Two shipped-arrangement exchangers set
  -- apart with a run of rf-pipe joining their WEST faces, and the pipe filled rather than the
  -- machine. If fluid reaches the second here but not in the rows above, then what fails is
  -- box-to-box transfer specifically, and not the way this probe puts fluid into things.
  do
    local a = place(surface, force, "chainprobe-shipped", 40, 0)
    local b = place(surface, force, "chainprobe-shipped", 40, -15)
    -- VANILLA pipe, not rf-pipe. rf-pipe's connections carry the plasma category (#26), so it
    -- cannot carry rf-reactor-energy at all -- the first version of this control used it and
    -- measured the containment rule rather than the question. Reactor energy is an ordinary fluid
    -- and travels in ordinary pipes, which is the whole point of ADR 0018.
    --
    -- The run sits one tile west of the machines: their energy connection is on the west face at
    -- local x = -2, which is absolute x = 38, so the pipe it reaches for is at 37.
    local pipes = {}
    for y = -15, 0 do
      pipes[#pipes + 1] = place(surface, force, "pipe", 37, y)
    end

    plumb(surface, force, a)
    plumb(surface, force, b)

    local ia = energy_index(a)
    local ib = energy_index(b)
    for _, pipe in ipairs(pipes) do
      pipe.fluidbox[1] = { name = ENERGY, amount = 100 }
    end
    storage.control = { a = a, b = b, ia = ia, ib = ib, pipes = pipes }
  end

  -- ------------------------------------------------------------------------- a row of EIGHT
  --
  -- WHY EIGHT, AND WHY IT IS A DIFFERENT QUESTION FROM THE PAIRS ABOVE. A lit D-T reactor sells
  -- about 322 MW (check-brownout.ps1) and one exchanger takes 40 MW, so eight is the shape ADR 0018
  -- describes and the one #275 ships. Every measurement in this file and in
  -- probe-energy-containment.ps1 has used TWO machines. Both ADR 0018's Consequences and
  -- docs/research/exchanger-chaining.md record the row of eight as unmeasured.
  --
  -- TWO THINGS ARE ASKED AND ONE OF THEM IS NEW.
  --
  -- Energy arrives on the FIRST machine's long face only -- one connection, the way a reactor bolts
  -- -- and has to reach the eighth through seven short-end joints.
  --
  -- Water is the new constraint, and chaining is what creates it. Once the machines bolt short end
  -- to short end, every interior water connection is consumed by a joint, so the row can be fed
  -- water at its two ends and nowhere else. That is not arranged here; it is what unbound() does on
  -- its own, because it skips occupied tiles. Calling it on all eight water boxes leaves pipes
  -- exactly where a player could reach one. Arithmetic off this repo's own figure --
  -- rf-hc-turbine's 600 units/s of 500 C steam is 58.2 MW, so 40 MW is 412 units/s -- puts eight
  -- machines at about 3,300 units/s arriving through those two connections.
  --
  -- THE ENERGY SOURCE IS DELIBERATELY UNLIMITED: an infinity pipe rather than a reactor, because a
  -- real one sells 322 MW against eight machines wanting 320 and would confound "the joints cannot
  -- carry it" with "the reactor cannot supply it". This section asks the joints.
  do
    local X, N, PITCH = 120, 8, 15

    -- Chunks are generated lazily and this column reaches y = -105, well past anything else in the
    -- rig. create_entity does not generate terrain, so a machine on an ungenerated chunk fails in a
    -- way that reads as a placement error rather than as a missing map.
    surface.request_to_generate_chunks({ X, -(N * PITCH) / 2 }, 12)
    surface.force_generate_chunk_requests()

    -- LAND UNDER THE WHOLE SECTION, AND IT IS A FIX RATHER THAN A PRECAUTION. Found on this
    -- section's second run: a benchmark map is created with a fresh seed every time, this column
    -- sits outside the starting area where lakes are, and generated terrain is therefore an
    -- uncontrolled variable in a rig whose only job is to control variables. One run placed all
    -- eight steam pipes and the next placed seven, so the same rig reported two different answers
    -- for the eighth machine.
    --
    -- Paving it removes the variable instead of detecting it. The refusal count out of plumb()
    -- below is the detector, and after this it should always read zero -- a rig that both paves and
    -- counts says so when the paving stops being enough.
    local tiles = {}
    for x = X - 8, X + 48 do
      for y = -(N - 1) * PITCH - 14, 14 do
        tiles[#tiles + 1] = { name = "grass-1", position = { x, y } }
      end
    end
    surface.set_tiles(tiles)

    -- AND CLEAR WHAT STANDS ON IT, which paving does not. set_tiles removes only entities that
    -- COLLIDE with the new tile, so a lake's fish go and a forest's trees stay. unbound() then does
    -- exactly what it promises -- skips a target tile something stands on -- and a tree in the steam
    -- column silently costs one machine its steam outlet, after which it backs up to full_output
    -- and reads as a chaining result.
    --
    -- MEASURED, not guessed: with paving alone the refusal count read 0 while the steam tally read
    -- 7, which is the pair of numbers that says "not refused by the ground, already occupied". Two
    -- consecutive runs lost a different machine each time -- row 8, then row 2.
    --
    -- The rig's opening sweep clears {-80,-80} to {80,80}, and this section sits outside it.
    for _, e in pairs(surface.find_entities_filtered({
        area = { { X - 8, -(N - 1) * PITCH - 14 }, { X + 48, 14 } } })) do
      if e.type ~= "character" then e.destroy() end
    end

    local row = {}
    for i = 1, N do row[i] = place(surface, force, "chainprobe-row", X, -(i - 1) * PITCH) end

    -- THE CONTROL, and the row is worth nothing without it: the same prototype, the same water and
    -- steam plumbing, joined to no neighbour and given no energy feed. It must read zero. #111 was
    -- caused by rigs whose controls could not fail, and the sibling probe's chain row had none at
    -- all until that ticket added one.
    local aloof = place(surface, force, "chainprobe-row", X + 40, 0)

    -- EVERY MACHINE BEFORE ANY PLUMBING, or unbound() has nothing to skip and buries a pipe under
    -- the neighbour -- the same ordering rule plumb() carries above.
    local refused = 0
    for _, e in ipairs(row) do refused = refused + plumb(surface, force, e) end
    refused = refused + plumb(surface, force, aloof)

    local energy = feed_one(surface, force, row[1], energy_index(row[1]), "west",
      { name = ENERGY, percentage = 1, mode = "at-least" })

    -- COUNTED RATHER THAN REASONED, and this is the whole of the water question. "A chained row is
    -- fed water at its two ends" rests on unbound() skipping occupied tiles, which rests in turn on
    -- one machine's water target being the tile its neighbour's water connection stands on. Count
    -- the pipes it actually left instead of trusting that: two water, one energy, and one steam per
    -- machine. Any other tally and the rows below are measuring a differently plumbed row.
    local tally = { water = 0, energy = 0, steam = 0 }
    for _, p in ipairs(surface.find_entities_filtered({ name = "infinity-pipe",
        area = { { X - 6, -(N - 1) * PITCH - 12 }, { X + 6, 12 } } })) do
      local f = p.get_infinity_pipe_filter()
      if f and f.name == "water"  then tally.water  = tally.water + 1  end
      if f and f.name == "steam"  then tally.steam  = tally.steam + 1  end
      if f and f.name == ENERGY   then tally.energy = tally.energy + 1 end
    end

    -- FLUIDBOX INDICES RESOLVED HERE, not at report time, which is the convention every other
    -- report path in this file already follows -- the pair rows keep i1 and i2 from build time.
    -- It is not tidiness: index_of() walks entity.fluidbox with no validity guard of its own, so
    -- calling it on a destroyed entity throws and takes the WHOLE report down, every other row's
    -- output with it, rather than losing the one row that went missing.
    local ei, wi = {}, {}
    for i, e in ipairs(row) do ei[i], wi[i] = energy_index(e), index_of(e, "water") end

    storage.row = { machines = row, aloof = aloof, fed = energy ~= nil, tally = tally, n = N,
      refused = refused, ei = ei, wi = wi,
      aloof_ei = energy_index(aloof), aloof_wi = index_of(aloof, "water") }
  end

  storage.report_at = game.tick + 300
end)

script.on_event(defines.events.on_tick, function()
  if not storage.report_at then return end

  -- KEEP THE FIRST ONE FED, which the first version of this probe did not and was wrong for. Its
  -- energy box holds 200 units and the machine burns 40 MW of 1 MJ units -- 0.667 a tick -- so over
  -- 300 ticks it consumed exactly the 200 it was given, and "nothing reached the second" measured
  -- the first running dry rather than anything about chaining. Topping it up every tick means there
  -- is always fluid there to travel if the engine will carry it.
  for _, c in ipairs(storage.cases or {}) do
    if c.first.valid then
      local box = c.first.fluidbox[c.i1]
      if not box or box.amount < 150 then
        c.first.fluidbox[c.i1] = { name = "rf-reactor-energy", amount = 200 }
      end
    end
  end

  -- The feed runs for the fed-by-a-pipe rows AND for the control, charged every tick for the same
  -- reason as the boxes above. An earlier version topped these up inside the report block, which
  -- runs once and only after the gate below -- so the pipes sat empty for the whole run and the
  -- rows measured unfed machines. The control's run was the last one left doing that: harmless
  -- while its machines were stopped, and wrong the moment they were given water, because two
  -- burning exchangers empty a 100-unit segment in about seventy-five ticks.
  local charged = { storage.control }
  for _, f in ipairs(storage.fed or {}) do charged[#charged + 1] = f end
  for _, group in ipairs(charged) do
    for _, pipe in ipairs(group and group.pipes or {}) do
      if pipe.valid then pipe.fluidbox[1] = { name = "rf-reactor-energy", amount = 100 } end
    end
  end

  if game.tick < storage.report_at then return end
  storage.report_at = nil

  for _, c in ipairs(storage.cases or {}) do
    local box = c.second.valid and c.second.fluidbox[c.i2] or nil
    local held = box and box.amount or 0
    local src = c.first.valid and c.first.fluidbox[c.i1] or nil
    local kept = src and src.amount or 0
    say(string.format("%-24s %-10s %-12.4g %-14s %-10.4g %s",
      c.name,
      c.joined and "yes" or "no",
      held,
      status_name(c.second),
      kept,
      (held > 0) and "energy travelled" or "nothing arrived"))
  end

  local c = storage.control
  if c and c.a.valid and c.b.valid then
    local ba = c.a.fluidbox[c.ia]
    local bb = c.b.fluidbox[c.ib]
    say(string.format("%-24s %-10s %-12.4g %-14s %-10.4g %s",
      "shipped + a pipe run", "n/a",
      bb and bb.amount or 0, status_name(c.b), ba and ba.amount or 0,
      ((bb and bb.amount or 0) > 0) and "energy travelled" or "nothing arrived"))
  end

  for _, f in ipairs(storage.fed or {}) do
    if f.first.valid and f.second.valid then
      local held = f.second.fluidbox[f.i2]
      local src  = f.first.fluidbox[f.i1]
      say(string.format("%-24s %-10s %-12.4g %-14s %-10.4g %s",
        f.name:gsub("^chainprobe%-", "") .. ", fed by a pipe", "yes",
        held and held.amount or 0, status_name(f.second), src and src.amount or 0,
        ((held and held.amount or 0) > 0) and "energy travelled" or "nothing arrived"))
    end
  end

  local r = storage.row
  if r then
    say("")
    say("--- a row of EIGHT, energy arriving on the first one's long face only ---")
    say(string.format("%-26s %-12s %-12s %s", "machine", "energy held", "water held", "status"))
    -- Validity FIRST, then the index, then the box. status_name() already answers "?" for an
    -- invalid entity, so a missing machine reports as one row rather than as no report at all.
    for i, e in ipairs(r.machines) do
      local eb = (e.valid and r.ei[i]) and e.fluidbox[r.ei[i]] or nil
      local wb = (e.valid and r.wi[i]) and e.fluidbox[r.wi[i]] or nil
      say(string.format("%-26s %-12.4g %-12.4g %s",
        string.format("row %d of %d", i, #r.machines),
        eb and eb.amount or 0, wb and wb.amount or 0, status_name(e)))
    end

    local ab = (r.aloof.valid and r.aloof_ei) and r.aloof.fluidbox[r.aloof_ei] or nil
    local awb = (r.aloof.valid and r.aloof_wi) and r.aloof.fluidbox[r.aloof_wi] or nil
    say(string.format("%-26s %-12.4g %-12.4g %s", "control, joined to none",
      ab and ab.amount or 0, awb and awb.amount or 0, status_name(r.aloof)))

    say(string.format("row: the energy feed landed on the first machine's long face: %s",
      r.fed and "yes" or "NO -- every figure above is void"))
    say("row: the control must read 0 energy, or the eight above are the rig filling what it can")
    say(string.format("row: pipes the rig left -- water %d (must be 2, the row's two ends), "
      .. "energy %d (must be 1), steam %d (must be %d)",
      r.tally.water, r.tally.energy, r.tally.steam, r.n))
    say(string.format("row: pipes the GROUND refused: %d -- must be 0, and a nonzero reading voids "
      .. "any machine below that reads full_output, because its steam had nowhere to go",
      r.refused))
    say("row: two water pipes for eight machines IS the constraint, not a shortcut -- every")
    say("row: interior water connection is consumed by a joint and cannot be reached")
  end

  say("")
  say("done")
  game.set_game_state({ game_finished = true, player_won = true, can_continue = false })
end)
'@
Set-Content -Path (Join-Path $rigDir 'control.lua') -Value $control -Encoding utf8

# ---------------------------------------------------------------------------- run it
$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }
try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    $enabled = Resolve-BundledSelection -Requested @() -Bundled $bundled
    Write-Host "bundled enabled: $(if ($enabled) { $enabled -join ', ' } else { 'none (base 2.0 only)' })"
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled $enabled -Mods ($ourMods + $rigName)

    $save = Join-Path $temp 'chain.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', [string]($Ticks + 120),
        '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'CHAINPROBE ' |
        ForEach-Object { ($_ -split 'CHAINPROBE ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the probe reported nothing.' }
    $reported | ForEach-Object { Write-Host $_ }
    if ($reported[-1] -ne 'done') {
        Write-Host ''
        Write-Host 'NOTE: the run ended before the report. Raise -Ticks or the benchmark budget.'
    }
}
finally {
    if (-not $KeepTemp) {
        Remove-ModJunctions -ModDirectory $modDir
        Remove-TempDirectory -Path $temp -Label 'probe-exchanger-chaining'
    } else { Write-Host "kept: $temp" }
}

Write-Host ''
Write-Host 'Probe finished. Exit 0 means it ran and reported, not that the answer was yes.'
