#Requires -Version 7
<#
.SYNOPSIS
    Probe: what does the Quality mechanic actually scale on this mod's entities?

.DESCRIPTION
    Asserts nothing. Places one of each of this mod's entities at every quality level and reports
    the numbers the simulation reads at runtime -- fluid box capacities, electric buffer, energy
    usage, inventory size -- plus the generator/boiler throughput pair whose ratio is what would
    or would not be free energy.

    Findings are written up in docs/research/quality.md. Exit 0 means it ran and reported, never
    that the answer was the hoped-for one -- this is a probe, not a gate, so no check sweep and no
    load-check invokes it. Run with -SpaceAge to repeat the measurement with space-age enabled; the
    note's claim is that both runs agree.

    NOT YET VERIFIED IN THE TREE: landed from a scratchpad under #97, which is the ticket that
    checks it still reproduces the note's tables in both configurations.
#>
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [switch] $SpaceAge,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
. "$repoRoot/scripts/factorio-lib.ps1"

$ourMods = @('realistic-fusion-refreshed-core', 'realistic-fusion-refreshed')
$rigName = 'rf-quality-probe'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-q-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

@{
    name = $rigName; version = '0.0.1'; title = 'Quality probe'
    author = 'probe-quality.ps1'; factorio_version = '2.0'
    dependencies = @('base >= 2.0.77', 'realistic-fusion-refreshed', 'realistic-fusion-refreshed-core')
} | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

$lua = @'
-- Generated by probe-quality.ps1. Nothing here ships. Reports; asserts nothing.

local function say(fmt, ...) log("QPROBE " .. string.format(fmt, ...)) end

local OURS = {
  "rf-reactor", "rf-aneutronic-reactor", "rf-lithium-blanket", "rf-heater",
  "rf-heat-exchanger", "rf-hc-exchanger", "rf-hc-turbine", "rf-direct-energy-converter",
  "rf-isotope-collector", "rf-aneutronic-composite-tank", "rf-pipe", "rf-pump",
  "rf-electrolyser", "rf-deuterium-extractor", "rf-brine-concentrator", "rf-gas-mixer",
  "rf-lithium-extractor", "steam-turbine", "heat-exchanger", "steel-chest", "boiler",
}

script.on_nth_tick(60, function()
  if storage.done then return end
  storage.done = true

  -- ------------------------------------------------------------ the quality set
  local levels = {}
  for name, q in pairs(prototypes.quality) do
    levels[#levels + 1] = { name = name, level = q.level, hidden = q.hidden }
  end
  table.sort(levels, function(a, b)
    if a.level ~= b.level then return a.level < b.level end
    return a.name < b.name
  end)
  for _, q in ipairs(levels) do
    say("quality %-16s level=%d hidden=%s", q.name, q.level, tostring(q.hidden))
  end

  local order = {}
  for _, q in ipairs(levels) do
    if q.name ~= "quality-unknown" then order[#order + 1] = q.name end
  end

  -- ------------------------------------------------------------ prototype-side flags
  for _, name in ipairs(OURS) do
    local p = prototypes.entity[name]
    if not p then
      say("MISSING prototype %s", name)
    else
      say("proto %-30s type=%-20s q_energy=%s q_inv=%s q_slots=%s q_supply=%s q_mining=%s",
        name, p.type,
        tostring(p.quality_affects_energy_usage), tostring(p.quality_affects_inventory_size),
        tostring(p.quality_affects_module_slots), tostring(p.quality_affects_supply_area_distance),
        tostring(p.quality_affects_mining_radius))
      local eum, csm = {}, {}
      for k, v in pairs(p.energy_usage_quality_multiplier or {}) do eum[#eum + 1] = k .. "=" .. tostring(v) end
      for k, v in pairs(p.crafting_speed_quality_multiplier or {}) do csm[#csm + 1] = k .. "=" .. tostring(v) end
      table.sort(eum) table.sort(csm)
      if #eum > 0 then say("proto %-30s energy_usage_quality_multiplier %s", name, table.concat(eum, " ")) end
      if #csm > 0 then say("proto %-30s crafting_speed_quality_multiplier %s", name, table.concat(csm, " ")) end
    end
  end

  -- ------------------------------------------------------------ prototype getters per quality
  local function getter(name, fn)
    local p = prototypes.entity[name]
    if not p or type(p[fn]) ~= "function" then return end
    local parts, differs, first = {}, false, nil
    for _, q in ipairs(order) do
      local ok, v = pcall(function() return p[fn](q) end)
      local shown = ok and tostring(v) or ("ERR:" .. tostring(v))
      if first == nil then first = shown elseif shown ~= first then differs = true end
      parts[#parts + 1] = string.format("%s=%s", q, shown)
    end
    say("get %-28s %-28s %-6s %s", name, fn, differs and "SCALES" or "flat", table.concat(parts, " "))
  end

  for _, name in ipairs(OURS) do
    if prototypes.entity[name] then
      getter(name, "get_fluid_capacity")
      getter(name, "get_max_energy_usage")
      getter(name, "get_max_energy_production")
      getter(name, "get_max_power_output")
      getter(name, "get_fluid_usage_per_tick")
      getter(name, "get_crafting_speed")
      getter(name, "get_pumping_speed")
    end
  end

  for _, name in ipairs({ "rf-lithium-blanket", "steel-chest" }) do
    local p = prototypes.entity[name]
    if p then
      local parts = {}
      for _, q in ipairs(order) do
        local ok, v = pcall(function() return p.get_inventory_size(defines.inventory.chest, q) end)
        parts[#parts + 1] = string.format("%s=%s", q, ok and tostring(v) or ("ERR:" .. tostring(v)))
      end
      say("get %-28s %-28s        %s", name, "get_inventory_size(chest)", table.concat(parts, " "))
    end
  end

  -- electric energy source: buffer_capacity is a field, the flow limits are methods
  for _, name in ipairs({ "rf-reactor", "rf-aneutronic-reactor", "rf-heater", "rf-electrolyser" }) do
    local p = prototypes.entity[name]
    local s = p and p.electric_energy_source_prototype
    if s then
      local inp, outp = {}, {}
      for _, q in ipairs(order) do
        local ok, v = pcall(function() return s.get_input_flow_limit(q) end)
        inp[#inp + 1] = string.format("%s=%s", q, ok and tostring(v) or "ERR")
        local ok2, v2 = pcall(function() return s.get_output_flow_limit(q) end)
        outp[#outp + 1] = string.format("%s=%s", q, ok2 and tostring(v2) or "ERR")
      end
      say("src %-28s buffer_capacity=%.10g drain=%.10g", name, s.buffer_capacity, s.drain)
      say("src %-28s get_input_flow_limit   %s", name, table.concat(inp, " "))
      say("src %-28s get_output_flow_limit  %s", name, table.concat(outp, " "))
    end
  end

  -- ------------------------------------------------------------ placed entities
  local surface = game.create_surface("qprobe", {
    water = 0,
    starting_area = 0,
    autoplace_controls = {},
    default_enable_all_autoplace_controls = false,
    cliff_settings = { name = "cliff", cliff_elevation_0 = 1e9, cliff_elevation_interval = 1e9 },
    autoplace_settings = {
      entity = { treat_missing_as_default = false, settings = {} },
      decorative = { treat_missing_as_default = false, settings = {} },
      tile = { treat_missing_as_default = true, settings = {} },
    },
  })
  surface.request_to_generate_chunks({ 300, 0 }, 25)
  surface.force_generate_chunk_requests()
  local force = game.forces.player

  local placed = {
    { "rf-reactor", 2 }, { "rf-aneutronic-reactor", 2 }, { "rf-lithium-blanket", 0 },
    { "rf-heat-exchanger", 2 }, { "rf-hc-exchanger", 2 }, { "rf-hc-turbine", 1 },
    { "rf-direct-energy-converter", 1 }, { "rf-isotope-collector", 4 },
    { "rf-aneutronic-composite-tank", 1 }, { "rf-heater", 4 }, { "steam-turbine", 1 },
    { "rf-pipe", 1 },
  }
  local x = 0
  for _, row in ipairs(placed) do
    local name, boxes = row[1], row[2]
    local y = -200
    local caps, buffers, invs = {}, {}, {}
    for _, q in ipairs(order) do
      local ok, e = pcall(function()
        return surface.create_entity({
          name = name, position = { x, y }, force = force, quality = q, raise_built = false })
      end)
      if not ok or not e then
        caps[#caps + 1] = q .. "=PLACE-FAIL(" .. tostring(e) .. ")"
      else
        local parts = {}
        for i = 1, boxes do
          local ok2, c = pcall(function() return e.fluidbox.get_capacity(i) end)
          parts[#parts + 1] = ok2 and string.format("%.10g", c) or "ERR"
        end
        caps[#caps + 1] = string.format("%s=[%s]", q, table.concat(parts, ","))
        local ok3, buf = pcall(function() return e.electric_buffer_size end)
        if ok3 and buf then buffers[#buffers + 1] = string.format("%s=%.10g", q, buf) end
        local inv = e.get_inventory(defines.inventory.chest)
        if inv then invs[#invs + 1] = string.format("%s=%d", q, #inv) end
      end
      y = y + 60
    end
    say("placed %-28s fluidbox capacities  %s", name, table.concat(caps, " "))
    if #buffers > 0 then say("placed %-28s electric_buffer_size %s", name, table.concat(buffers, " ")) end
    if #invs > 0 then say("placed %-28s inventory size       %s", name, table.concat(invs, " ")) end
    x = x + 60
  end

  -- ------------------------------------------------------------ the ratio that would be free energy
  for _, fname in ipairs({ "rf-reactor-energy", "rf-aneutronic-reactor-energy", "steam" }) do
    local f = prototypes.fluid[fname]
    if f then
      say("fluid %-30s fuel_value=%.10g heat_capacity=%.10g default_temperature=%.10g max_temperature=%.10g",
        fname, f.fuel_value or 0, f.heat_capacity or 0, f.default_temperature or 0, f.max_temperature or 0)
    end
  end

  local function generator_ratio(ename, fname)
    local g, f = prototypes.entity[ename], prototypes.fluid[fname]
    if not g or not f then return end
    for _, q in ipairs(order) do
      local usage = g.get_fluid_usage_per_tick(q) or 0
      local cap   = (g.get_max_power_output(q) or 0) * 60
      local burns = g.burns_fluid
      local input_w
      if burns then
        input_w = usage * 60 * (f.fuel_value or 0)
      else
        input_w = usage * 60 * ((g.maximum_temperature or 0) - (f.default_temperature or 0)) * (f.heat_capacity or 0)
      end
      local eff = g.effectivity or 1
      say("GEN %-28s %-10s burns=%-5s usage/tick=%.10g input=%.6g W declared_cap=%.6g W eff=%.4g out/in=%.6f",
        ename, q, tostring(burns), usage, input_w, cap,
        eff, input_w > 0 and (math.min(cap, input_w * eff) / input_w) or -1)
    end
  end
  generator_ratio("rf-direct-energy-converter", "rf-aneutronic-reactor-energy")
  generator_ratio("rf-hc-turbine", "steam")
  generator_ratio("steam-turbine", "steam")

  for _, ename in ipairs({ "rf-heat-exchanger", "rf-hc-exchanger" }) do
    local ex = prototypes.entity[ename]
    if ex then
      local fs = ex.fluid_energy_source_prototype
      say("BOILER %-24s target_temperature=%s fluid_source_effectivity=%s burns_fluid=%s",
        ename, tostring(ex.target_temperature),
        tostring(fs and fs.effectivity), tostring(fs and fs.burns_fluid))
    end
  end

  say("done")
end)
'@
Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') -Value $lua
Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'data.lua') -Value '-- nothing'

$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }
try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    $want = if ($SpaceAge) { @('space-age') } else { @('quality') }
    $enabled = Resolve-BundledSelection -Requested $want -Bundled $bundled
    Write-Host "bundled enabled: $($enabled -join ', ')"
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled $enabled -Mods ($ourMods + $rigName)

    $save = Join-Path $temp 'q.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', '240', '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'QPROBE ' |
        ForEach-Object { ($_ -split 'QPROBE ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the probe reported nothing.' }
    $reported | ForEach-Object { Write-Host $_ }
}
finally {
    if (-not $KeepTemp) {
        Remove-ModJunctions -ModDirectory $modDir
        Remove-TempDirectory -Path $temp -Label 'probe-quality'
    } else { Write-Host "kept: $temp" }
}
