<#
.SYNOPSIS
    Probes what PrototypeHistory reports for the cases the 2.0.77 docs leave open. The rig behind
    docs/research/get-history-semantics.md.

.DESCRIPTION
    A PROBE, NOT A CHECK. Every line it prints is a measurement, and a negative answer is as much
    of a result as a positive one -- exit 0 means the probe ran and every row reported, never that
    the answers were the ones anybody hoped for. It must not be added to a check sweep or to
    load-check.ps1.

    WHY MEASURING IS THE ONLY WAY TO ASK

    docs/research/tech-tree-mod-attribution.md (#158) records that the engine tracks prototype
    provenance and exposes it at runtime as LuaPrototypes::get_history(type, name) -> { created,
    changed }. The concept page says one line about each field and nothing about the two corners a
    tool reading the field has to interpret:

      - What `created` reports when a mod REDEFINES an existing name via data:extend -- the silent
        replacement name-check.ps1 exists to catch. Original mod stays creator with the replacer in
        `changed`, or replacer becomes creator? Both readings fit the docs.
      - Whether a write that does not change the value ("same-value write"), or a mere read, lands
        the writing mod in `changed`.

    The attribution mechanism choice (#164) picked get_history as the extraction script's source of
    truth, so how to READ these fields is decision-relevant, and the docs do not answer. This rig
    asks the engine.

    WHAT IT REPORTS -- six items, one canary mod (rf-history-probe), base only:

      fresh       rf-histprobe-fresh    defined by the canary's data.lua from nothing
      redefined   iron-gear-wheel       wholesale data:extend under an existing base name (data.lua)
      modified    steel-plate           one field genuinely changed (data-updates.lua)
      samevalue   copper-plate          one field written back with its existing value (data-updates.lua)
      readonly    plastic-bar           one field read, nothing written (data-updates.lua)
      untouched   iron-plate            control; the canary never mentions it

    Each row prints `created` and the ordered `changed` list. The rig reads them in on_init, which
    --create fires, and reports two ways -- log lines for the console and a JSON file in
    script-output -- because a probe whose only output died with a crashed run would read as silence.

.PARAMETER FactorioExe
    Path to Factorio.exe. Defaults to $env:FACTORIO_EXE, then the Steam install on this machine.

.PARAMETER KeepTemp
    Keep the save, the canary mod and the captured output.

.EXAMPLE
    pwsh -File scripts/probe-get-history.ps1
#>

#Requires -Version 7
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/factorio-lib.ps1"

$rigName = 'rf-history-probe'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-histprobe-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

@{
    name = $rigName; version = '0.0.1'; title = 'PrototypeHistory probe'
    author = 'probe-get-history.ps1'; factorio_version = '2.0'; dependencies = @('base >= 2.0.77')
} | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

# The redefinition is deliberately a from-scratch table, not a copy of base's -- the question is
# what history says when a mod replaces a definition wholesale, so the replacement should owe
# nothing to the original. stack_size 543 is a marker with no meaning beyond "not base's value".
Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'data.lua') -Value @'
-- Generated by probe-get-history.ps1. Nothing here ships.
data:extend({
  {
    type = "item", name = "rf-histprobe-fresh",
    icon = "__base__/graphics/icons/iron-plate.png", icon_size = 64,
    stack_size = 1, subgroup = "raw-material", order = "z[histprobe]",
  },
  {
    type = "item", name = "iron-gear-wheel",
    icon = "__base__/graphics/icons/iron-gear-wheel.png", icon_size = 64,
    stack_size = 543, subgroup = "intermediate-product", order = "c[iron-gear-wheel]",
  },
})
'@

Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'data-updates.lua') -Value @'
-- Generated by probe-get-history.ps1. Nothing here ships.
data.raw.item["steel-plate"].stack_size = 999                                        -- modified
data.raw.item["copper-plate"].stack_size = data.raw.item["copper-plate"].stack_size  -- same-value write
local _ = data.raw.item["plastic-bar"].stack_size                                    -- read only
'@

Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') -Value @'
-- Generated by probe-get-history.ps1. Reports; asserts nothing.
script.on_init(function()
  local CASES = {
    { "fresh",     "rf-histprobe-fresh" },
    { "redefined", "iron-gear-wheel" },
    { "modified",  "steel-plate" },
    { "samevalue", "copper-plate" },
    { "readonly",  "plastic-bar" },
    { "untouched", "iron-plate" },
  }
  local rows = {}
  for _, c in ipairs(CASES) do
    local label, name = c[1], c[2]
    local ok, h = pcall(function() return prototypes.get_history("item", name) end)
    local row
    if ok and h then
      row = { case = label, name = name, created = h.created, changed = h.changed }
      log(string.format("HPROBE %-10s %-22s created=%-18s changed=[%s]",
        label, name, h.created, table.concat(h.changed, ", ")))
    else
      row = { case = label, name = name, error = tostring(h) }
      log(string.format("HPROBE %-10s %-22s ERROR %s", label, name, tostring(h)))
    end
    rows[#rows + 1] = row
  end
  helpers.write_file("rf-history-probe.json", helpers.table_to_json(rows))
  log("HPROBE done")
end)
'@

try {
    Write-ModList -ModDirectory $modDir -Bundled $bundled -Mods @($rigName)

    $save = Join-Path $temp 'history-probe.zip'
    $out = Invoke-FactorioStep -FactorioExe $FactorioExe -ModDirectory $modDir `
        -OutputDirectory $temp -Tag 'create' -Arguments @('--create', $save)

    $reported = @(Get-Content $out | Select-String -Pattern 'HPROBE ' |
        ForEach-Object { ($_ -split 'HPROBE ', 2)[1].TrimEnd() })

    # The log lines are the display; the JSON is the record the doc is read from. Requiring both
    # catches a run that crashed between the last log line and the write.
    $jsonPath = Join-Path $temp 'write-data/script-output/rf-history-probe.json'
    if (-not (Test-Path $jsonPath)) { throw "no rf-history-probe.json in script-output; on_init never finished." }
    if (-not ($reported | Where-Object { $_ -eq 'done' })) {
        throw 'the rig stopped before the end of its report; the rows above are incomplete.'
    }

    foreach ($line in $reported) { Write-Host "  $line" }
    Write-Host ''
    Write-Host 'OK - the probe ran and every row reported. The answers are measurements, not a'
    Write-Host '     verdict; docs/research/get-history-semantics.md is what they are read into.'
}
finally {
    if ($KeepTemp) { Write-Host ''; Write-Host "temp kept at: $temp" }
    else { Remove-TempDirectory -Path $temp -Label 'probe-get-history' }
}
exit 0
