#Requires -Version 7
<#
.SYNOPSIS
    Probe: what does target_temperature do to a boiler's own fluid conversion?

.DESCRIPTION
    Asserts nothing. #46 left one item undecided -- whether rf-reactor's target_temperature was the
    right number -- and it could not be settled by reading, because the documentation and this
    repository disagreed about what the field does.

    THAT QUESTION IS NOW ANSWERED and the target is 550 C, so this probe is kept for the reason
    CLAUDE.md keeps probes rather than for the decision it fed: it stays committed so the next engine
    version can be asked the same question. Its sweep still starts at 15 and 165 deliberately -- the
    shipped-at-the-time values are the ones a regression would show up against.

    The 2.0.77 BoilerPrototype docs make target_temperature "the temperature that the input fluid
    must reach to be moved to the output fluid box", which makes the conversion rate a function of
    energy_consumption divided by the fluid's rise to that target. prototypes/entities.lua records
    the opposite: a reactor seeded at 100 C, below the target, and one seeded at 1e6 C, far above
    it, "both lose plasma only at the rate the simulation burns it".

    THE ISOLATION IS THE WHOLE POINT. That measurement was taken on a real rf-reactor, where
    control.lua is also consuming plasma every step, so it cannot separate what the ENGINE moves
    from what the SIMULATION burns. This rig defines its own boilers instead: copies of rf-reactor
    under rig-only names, which scripts/entity-management.lua never registers and control.lua's
    SPECS therefore never sees. Nothing but the engine touches their plasma.

    Their energy source is void rather than electric, deliberately: power availability would be a
    second variable, and the question is what target_temperature and energy_consumption do.

    Findings are written up in docs/research/target-temperature.md. Exit 0 means it ran and
    reported, never that the answer was the hoped-for one -- this is a probe, not a gate, so no
    check sweep and no load-check invokes it.
#>
[CmdletBinding()]
param(
    [string] $FactorioExe,
    [int]    $Ticks = 600,
    [switch] $KeepTemp
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
. "$repoRoot/scripts/factorio-lib.ps1"

$ourMods = @('realistic-fusion-refreshed-core', 'realistic-fusion-refreshed')
$rigName = 'rf-target-temperature-probe'

$FactorioExe = Resolve-FactorioExe -Path $FactorioExe
$bundled     = Get-BundledMods -FactorioExe $FactorioExe

$temp   = Join-Path ([IO.Path]::GetTempPath()) ('rf-tt-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$modDir = Join-Path $temp 'mods'
$rigDir = Join-Path $modDir $rigName
New-Item -ItemType Directory -Path $rigDir -Force | Out-Null

@{
    name = $rigName; version = '0.0.1'; title = 'Target temperature probe'
    author = 'probe-target-temperature.ps1'; factorio_version = '2.0'
    dependencies = @('base >= 2.0.77', 'realistic-fusion-refreshed', 'realistic-fusion-refreshed-core')
} | ConvertTo-Json | Set-Content -Path (Join-Path $rigDir 'info.json') -Encoding utf8

# ---------------------------------------------------------------------------- the rig's prototypes
$data = @'
-- Generated by probe-target-temperature.ps1. Nothing here ships.
--
-- One boiler per (target_temperature, energy_consumption) pair, each a copy of rf-reactor so the
-- fluid boxes, volumes, filters and connection categories are the shipped ones. Named outside the
-- rf- reactor set on purpose: control.lua's SPECS is keyed by entity name, so these are invisible
-- to the simulation and their plasma is moved by the engine alone.

local TARGETS = { 15, 165, 500, 5000, 1000000 }
local DRAWS   = { { "1W", "1W" }, { "1MW", "1MW" }, { "50MW", "50MW" } }

local made = {}
for _, target in ipairs(TARGETS) do
  for _, draw in ipairs(DRAWS) do
    local e = table.deepcopy(data.raw["boiler"]["rf-reactor"])
    e.name = string.format("ttprobe-%d-%s", target, draw[1])
    e.target_temperature = target
    e.energy_consumption = draw[2]
    -- Void, so the only limits are energy_consumption and the target. An electric source would
    -- make "was there power" a second explanation for any rate that came out low.
    e.energy_source = { type = "void" }
    e.minable = nil
    e.placeable_by = nil
    -- No item and no recipe: the rig places these with create_entity, never a player.
    e.flags = { "not-blueprintable", "not-deconstructable", "hide-alt-info" }
    made[#made + 1] = e
  end
end
data:extend(made)
'@
Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'data.lua') -Value $data

# ---------------------------------------------------------------------------- the measurement
$lua = @'
-- Generated by probe-target-temperature.ps1. Reports; asserts nothing.

local function say(fmt, ...) log("TTPROBE " .. string.format(fmt, ...)) end

local TARGETS = { 15, 165, 500, 5000, 1000000 }
local DRAWS   = { "1W", "1MW", "50MW" }
local PLASMA  = "rf-d-d-plasma"

-- The shipped D-D equilibrium, so the headline sweep is run at the temperature a real reactor
-- actually sits at rather than at a round number.
local SHIPPED_C = 2.42e8

-- The input-temperature ladder, run against ONE variant so the only thing changing is how far the
-- plasma starts from the target. Run against the 165 variant, which was rf-reactor's target when
-- this was written: 100 C is below it and everything above it is above.
local INPUT_LADDER = { 100, 200, 1e6, SHIPPED_C, 2e9 }

local FILL = 1000  -- the reactor's declared box volume, so every run starts from a full box

local MEASURE_TICKS = __TICKS__

local subjects = {}   -- { entity, label, target, draw, input_c, converted, topped }

local function box_amount(fb, i)
  local ok, v = pcall(function() return fb[i] end)
  if not ok or not v then return 0, 0 end
  return v.amount or 0, v.temperature or 0
end

script.on_nth_tick(1, function(event)
  -- ------------------------------------------------------------------ set-up, once
  if not storage.ready then
    storage.ready = true
    storage.started = event.tick
    storage.rows = {}

    local surface = game.create_surface("ttprobe", {
      water = 0, starting_area = 0, autoplace_controls = {},
      default_enable_all_autoplace_controls = false,
      cliff_settings = { name = "cliff", cliff_elevation_0 = 1e9, cliff_elevation_interval = 1e9 },
      autoplace_settings = {
        entity = { treat_missing_as_default = false, settings = {} },
        decorative = { treat_missing_as_default = false, settings = {} },
        tile = { treat_missing_as_default = true, settings = {} },
      },
    })
    surface.request_to_generate_chunks({ 0, 0 }, 40)
    surface.force_generate_chunk_requests()
    storage.surface = surface.name
    local force = game.forces.player

    -- What the documented model needs, so the note can evaluate the formula rather than quote it.
    for _, fname in ipairs({ PLASMA, "rf-reactor-energy" }) do
      local f = prototypes.fluid[fname]
      say("fluid %-22s heat_capacity=%.10g default_temperature=%.10g max_temperature=%.10g fuel_value=%.10g",
        fname, f.heat_capacity or 0, f.default_temperature or 0, f.max_temperature or 0, f.fuel_value or 0)
    end

    -- The shipped reactor, for reference: this is the pair #46 is asking about.
    local ship = prototypes.entity["rf-reactor"]
    say("shipped rf-reactor target_temperature=%s boiler_mode=%s",
      tostring(ship.target_temperature), tostring(ship.boiler_mode))

    local x = 0
    local function place(name, label, target, draw, input_c)
      local proto = prototypes.entity[name]
      if not proto then say("MISSING prototype %s", name) return end
      local e = surface.create_entity({
        name = name, position = { x, 0 }, force = force, raise_built = false })
      x = x + 40
      if not e then say("PLACE-FAIL %s", name) return end
      subjects[#subjects + 1] = {
        entity = e, label = label, target = target, draw = draw, input_c = input_c,
        converted = 0, topped = 0, out_temp = -1, declared = proto.target_temperature,
      }
    end

    -- sweep A: every target against every draw, at the shipped plasma temperature
    for _, target in ipairs(TARGETS) do
      for _, draw in ipairs(DRAWS) do
        local name = string.format("ttprobe-%d-%s", target, draw)
        place(name, string.format("A t=%-8d %-5s", target, draw), target, draw, SHIPPED_C)
      end
    end

    -- sweep B: one variant, plasma started at five distances from the target
    for _, input_c in ipairs(INPUT_LADDER) do
      place("ttprobe-165-50MW",
        string.format("B in=%-10.3g", input_c), 165, "50MW", input_c)
    end

    -- sweep C: every target and draw again, but with the plasma BELOW every one of them, which is
    -- the only regime sweep A found any conversion in. Two things it is for. It measures the rate
    -- law across the whole matrix instead of at one point. And targets above 165 are targets above
    -- rf-reactor-energy's own max_temperature, so this is where the engine has to say what it does
    -- with an output it cannot hold -- clamp it, refuse it, or something else. control.lua's
    -- check_energy_outlets() guard added under #46 is betting on "refuse".
    for _, target in ipairs(TARGETS) do
      for _, draw in ipairs(DRAWS) do
        local name = string.format("ttprobe-%d-%s", target, draw)
        place(name, string.format("C t=%-8d %-5s", target, draw), target, draw, 14)
      end
    end

    say("placed %d subjects, measuring for %d ticks", #subjects, MEASURE_TICKS)
    storage.count = #subjects
    return
  end

  if storage.reported then return end

  -- ------------------------------------------------------------------ per-tick accounting
  -- Box 1 is topped back to a full box at its own input temperature every tick, so the measured
  -- rate is a steady state rather than a decaying one, and the top-up is itself the tally of what
  -- the engine took. Box 2 is drained every tick so it can never back up and stall the conversion.
  for _, s in ipairs(subjects) do
    local fb = s.entity.fluidbox
    local out_amount, out_temp = box_amount(fb, 2)
    if out_amount > 0 then
      s.converted = s.converted + out_amount
      if s.out_temp < 0 then s.out_temp = out_temp end
      fb[2] = nil
    end
    local in_amount = select(1, box_amount(fb, 1))
    if in_amount < FILL then
      s.topped = s.topped + (FILL - in_amount)
      fb[1] = { name = PLASMA, amount = FILL, temperature = s.input_c }
    end
  end

  -- ------------------------------------------------------------------ report, once
  if event.tick - storage.started >= MEASURE_TICKS then
    storage.reported = true
    local seconds = MEASURE_TICKS / 60
    say("--- converted over %d ticks (%.1f s) -----------------------------------", MEASURE_TICKS, seconds)
    say("%-22s %-10s %-8s %14s %14s %14s %10s",
      "case", "declared", "input C", "energy units", "plasma taken", "units/second", "out C")
    for _, s in ipairs(subjects) do
      say("%-22s %-10s %-8.3g %14.6g %14.6g %14.6g %10s",
        s.label, tostring(s.declared), s.input_c, s.converted, s.topped,
        s.converted / seconds, s.out_temp < 0 and "-" or string.format("%.6g", s.out_temp))
    end
    say("done")
  end
end)
'@
$lua = $lua.Replace('__TICKS__', [string]$Ticks)
Set-Content -Encoding utf8 -Path (Join-Path $rigDir 'control.lua') -Value $lua

$step = @{ FactorioExe = $FactorioExe; ModDirectory = $modDir; OutputDirectory = $temp }
try {
    New-ModJunctions -ModDirectory $modDir -RepoRoot $repoRoot -Mods $ourMods
    $enabled = Resolve-BundledSelection -Requested @() -Bundled $bundled
    Write-Host "bundled enabled: $(if ($enabled) { $enabled -join ', ' } else { 'none (base 2.0 only)' })"
    Write-ModList -ModDirectory $modDir -Bundled $bundled -EnabledBundled $enabled -Mods ($ourMods + $rigName)

    $save = Join-Path $temp 'tt.zip'
    Invoke-FactorioStep @step -Arguments @('--create', $save) -Tag 'create' | Out-Null
    $runOut = Invoke-FactorioStep @step -Tag 'run' -Arguments @(
        '--benchmark', $save, '--benchmark-ticks', [string]($Ticks + 120),
        '--benchmark-runs', '1', '--disable-audio')

    $reported = @(Get-Content $runOut | Select-String -Pattern 'TTPROBE ' |
        ForEach-Object { ($_ -split 'TTPROBE ', 2)[1].TrimEnd() })
    if ($reported.Count -eq 0) { throw 'the probe reported nothing.' }
    $reported | ForEach-Object { Write-Host $_ }
    if ($reported[-1] -ne 'done') {
        Write-Host ''
        Write-Host 'NOTE: the run ended before the report. Raise -Ticks or the benchmark budget.'
    }
}
finally {
    if (-not $KeepTemp) {
        Remove-ModJunctions -ModDirectory $modDir
        Remove-TempDirectory -Path $temp -Label 'probe-target-temperature'
    } else { Write-Host "kept: $temp" }
}
